// Generated by CoffeeScript 1.6.3
(function() {
  define(['angular', 'Admin/Resources/config/routing', 'Admin/Main/Service/AppState', 'Admin/Main/Service/DpApi', 'Admin/Main/DataService/EntityManager', 'Admin/Main/DataService/Departments'], function(angular, routing, Admin_Main_Service_AppState, Admin_Main_Service_DpApi, Admin_Main_DataService_EntityManager, Admin_Main_DataService_Departments) {
    var Admin_App, _ref, _ref1;
    Admin_App = angular.module('Admin_App', ['ui.router', 'ui.bootstrap', 'ui.select2']);
    Admin_App.service('AppState', [
      '$rootScope', '$state', function($rootScope, $state) {
        return new Admin_Main_Service_AppState($rootScope, $state);
      }
    ]);
    Admin_App.service('Api', [
      '$http', function($http) {
        return new Admin_Main_Service_DpApi($http, window.DP_BASE_API_URL, window.DP_API_TOKEN);
      }
    ]);
    Admin_App.factory('$exceptionHandler', [
      '$log', function($log) {
        return function(exception, cause) {
          throw exception;
        };
      }
    ]);
    Admin_App.service('em', [
      function() {
        return new Admin_Main_DataService_EntityManager();
      }
    ]);
    Admin_App.service('DepartmentData', [
      'em', 'Api', '$q', function(em, Api, $q) {
        return new Admin_Main_DataService_Departments(em, Api, $q);
      }
    ]);
    Admin_App.directive('dpStateMark', [
      '$rootScope', '$state', function($rootScope, $state) {
        return {
          restrict: 'A',
          link: function(scope, element, attrs) {
            var checkState, current_state_id, _ref;
            checkState = function(stateId, newStateId) {
              var stateIdRegex;
              if (!stateId || !newStateId) {
                return;
              }
              stateIdRegex = '^';
              stateIdRegex += stateId.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&");
              stateIdRegex += '\\b';
              if (newStateId.match(new RegExp(stateIdRegex))) {
                return true;
              } else {
                return false;
              }
            };
            if ((_ref = $state.current) != null ? _ref.name : void 0) {
              current_state_id = $state.current.name;
              if ($state.params.id) {
                current_state_id += '.' + $state.params.id;
              }
              if (checkState(attrs.dpStateMark, current_state_id)) {
                element.addClass('state-on active');
              }
            }
            return $rootScope.$on('dp_activeStateChange', function(ev, newStateId) {
              if (checkState(attrs.dpStateMark, newStateId)) {
                return element.addClass('state-on active');
              } else {
                return element.removeClass('state-on active');
              }
            }, true);
          }
        };
      }
    ]);
    Admin_App.directive('dpToggleSwitch', function() {
      return {
        restrict: 'A',
        require: 'ngModel',
        template: '<div ng-class="{\'switch-on\': model, \'switch-off\': !model}"><input type="checkbox" /></div>',
        replace: true,
        scope: {
          options: '@dpToggleSwitch',
          model: '=ngModel'
        },
        link: function(scope, element, attrs, ngModel) {
          var $wrap, options;
          if (scope.options) {
            options = scope.$eval(scope.options);
          } else {
            options = {};
          }
          $wrap = jQuery(element);
          $wrap.attr('data-off-label', options['off-label'] || "<i class='icon-remove'></i>");
          $wrap.attr('data-on-label', options['on-label'] || "<i class='icon-ok'></i>");
          $wrap.attr('data-off', options['off-class'] || "danger");
          $wrap.attr('data-on', options['on-class'] || "success");
          $wrap.addClass('dp-switch');
          if (scope["class"]) {
            $wrap.addClass(scope["class"]);
          }
          if (scope.model) {
            $wrap.find('input').get(0).checked = true;
            ngModel.$setViewValue(true);
          }
          $wrap.bootstrapSwitch();
          return $wrap.find('input').on('change', function() {
            var el;
            el = this;
            return scope.$apply(function() {
              var val;
              val = !!el.checked;
              ngModel.$setViewValue(val);
              return scope.model = val;
            });
          });
        }
      };
    });
    Admin_App.directive('dpTabBtn', function() {
      return {
        restrict: 'A',
        link: function(scope, element, attrs) {
          var id_segs, tab_group, tab_val;
          if (!scope.dp_tab_ids) {
            scope.dp_tab_ids = {};
          }
          id_segs = attrs['dpTabBtn'];
          if (!id_segs) {
            return;
          }
          id_segs = id_segs.split('.');
          tab_val = id_segs.pop();
          tab_group = id_segs.join('.');
          if (element.hasClass('active')) {
            scope.dp_tab_ids[tab_group] = tab_val;
          }
          element.on('click', function(ev) {
            ev.preventDefault();
            scope.dp_tab_ids[tab_group] = tab_val;
            return scope.$apply();
          });
          return scope.$watch(function() {
            return scope.dp_tab_ids[tab_group];
          }, function(newVal) {
            if (newVal === tab_val) {
              return element.addClass('active');
            } else {
              return element.removeClass('active');
            }
          });
        }
      };
    });
    Admin_App.directive('dpTabBody', function() {
      return {
        restrict: 'A',
        link: function(scope, element, attrs) {
          var id_segs, tab_group, tab_val;
          if (!scope.dp_tab_ids) {
            scope.dp_tab_ids = {};
          }
          id_segs = attrs['dpTabBody'];
          if (!id_segs) {
            return;
          }
          id_segs = id_segs.split('.');
          tab_val = id_segs.pop();
          tab_group = id_segs.join('.');
          if (scope.dp_tab_ids[tab_group] === tab_val) {
            element.show();
          } else {
            element.hide();
          }
          return scope.$watch(function() {
            return scope.dp_tab_ids[tab_group];
          }, function(newVal) {
            if (newVal === tab_val) {
              return element.show();
            } else {
              return element.hide();
            }
          });
        }
      };
    });
    Admin_App.config([
      '$stateProvider', '$urlRouterProvider', function($stateProvider, $urlRouterProvider) {
        var id, opts, route, segs, url, views, with_lists, _i, _len, _results;
        $urlRouterProvider.otherwise("/");
        with_lists = {};
        _results = [];
        for (_i = 0, _len = routing.length; _i < _len; _i++) {
          route = routing[_i];
          id = route.id;
          url = route.url;
          views = {};
          if (route.nav != null) {
            views['dp_section_nav'] = route.nav;
          }
          if (route.list != null) {
            views['dp_section_list@'] = route.list;
          }
          if (route.page != null) {
            views['dp_section_page@'] = route.page;
          }
          opts = {
            url: url,
            views: views
          };
          if (route.with_list_view) {
            opts.with_list_view = true;
          } else if (route.list != null) {
            opts.with_list_view = true;
          } else if (route.page != null) {
            segs = id.split('.');
            segs.pop();
            if (with_lists[segs.join('.')]) {
              opts.with_list_view = true;
            }
          }
          if (opts.with_list_view) {
            with_lists[id] = true;
          }
          _results.push($stateProvider.state(id, opts));
        }
        return _results;
      }
    ]);
    Admin_App.run([
      '$http', '$templateCache', function($http, $templateCache) {
        var qs, t, templates, _i, _len;
        templates = ['Index/app-nav-setup.html', 'Index/app-nav-agents.html', 'Index/app-nav-tickets.html', 'Index/app-nav-crm.html', 'Index/app-nav-portal.html', 'Index/app-nav-chat.html', 'Index/app-nav-twitter.html', 'Index/app-nav-apps.html', 'Index/app-nav-server.html', 'Index/blank.html'];
        qs = [];
        for (_i = 0, _len = templates.length; _i < _len; _i++) {
          t = templates[_i];
          qs.push('views[]=' + encodeURIComponent(t));
        }
        qs = qs.join('&');
        $http({
          method: 'GET',
          url: DP_BASE_ADMIN_URL + '/load-view/multi?' + qs
        }).success(function(data) {
          var id, tpl, _j, _len1, _results;
          _results = [];
          for (_j = 0, _len1 = data.length; _j < _len1; _j++) {
            tpl = data[_j];
            id = DP_BASE_ADMIN_URL + '/load-view/' + tpl.id;
            _results.push($templateCache.put(id, tpl.source));
          }
          return _results;
        });
        return window.TC = $templateCache;
      }
    ]);
    if ((_ref = window.parent) != null ? _ref.DP_FRAME_OVERLAY_admin : void 0) {
      if ((_ref1 = window.parent) != null) {
        _ref1.DP_FRAME_OVERLAY_admin.callLoaded();
      }
    }
    return Admin_App;
  });

}).call(this);

/*
//@ sourceMappingURL=App.map
*/
