// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty;

  define(['angular', 'DP_LANG', 'Admin/Resources/config/routing', 'Admin/Main/Service/AppState', 'Admin/Main/Service/DpApi', 'Admin/Main/Service/Growl', 'Admin/Main/DataService/EntityManager', 'Admin/Main/DataService/Departments'], function(angular, DP_LANG, routing, Admin_Main_Service_AppState, Admin_Main_Service_DpApi, Admin_Main_Service_Growl, Admin_Main_DataService_EntityManager, Admin_Main_DataService_Departments) {
    var Admin_App, _ref, _ref1;
    Admin_App = angular.module('Admin_App', ['ui.router', 'ui.bootstrap', 'ui.select2', 'ui.sortable', 'pascalprecht.translate']);
    Admin_App.service('AppState', [
      '$rootScope', '$state', function($rootScope, $state) {
        return new Admin_Main_Service_AppState($rootScope, $state);
      }
    ]);
    Admin_App.service('Api', [
      '$http', function($http) {
        return new Admin_Main_Service_DpApi($http, window.DP_BASE_API_URL, window.DP_API_TOKEN);
      }
    ]);
    Admin_App.factory('$exceptionHandler', [
      '$log', function($log) {
        return function(exception, cause) {
          throw exception;
        };
      }
    ]);
    Admin_App.service('em', [
      function() {
        return new Admin_Main_DataService_EntityManager();
      }
    ]);
    Admin_App.service('DepartmentData', [
      'em', 'Api', '$q', function(em, Api, $q) {
        return new Admin_Main_DataService_Departments(em, Api, $q);
      }
    ]);
    Admin_App.service('Growl', [
      function() {
        return new Admin_Main_Service_Growl();
      }
    ]);
    Admin_App.directive('dpStateMark', [
      '$rootScope', '$state', function($rootScope, $state) {
        return {
          restrict: 'A',
          link: function(scope, element, attrs) {
            var checkState, current_state_id, _ref;
            checkState = function(stateId, newStateId) {
              var stateIdRegex;
              if (!stateId || !newStateId) {
                return;
              }
              stateIdRegex = '^';
              stateIdRegex += stateId.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&");
              stateIdRegex += '\\b';
              if (newStateId.match(new RegExp(stateIdRegex))) {
                return true;
              } else {
                return false;
              }
            };
            if ((_ref = $state.current) != null ? _ref.name : void 0) {
              current_state_id = $state.current.name;
              if ($state.params.id) {
                current_state_id += '.' + $state.params.id;
              }
              if (checkState(attrs.dpStateMark, current_state_id)) {
                element.addClass('state-on active');
              }
            }
            return $rootScope.$on('dp_activeStateChange', function(ev, newStateId) {
              if (checkState(attrs.dpStateMark, newStateId)) {
                return element.addClass('state-on active');
              } else {
                return element.removeClass('state-on active');
              }
            }, true);
          }
        };
      }
    ]);
    Admin_App.directive('dpNavSubnav', [
      '$rootScope', '$state', function($rootScope, $state) {
        return {
          restrict: 'A',
          link: function(scope, element, attrs) {
            var $toggler;
            $toggler = element.parent().find('> a');
            $toggler.on('click', function(ev) {
              ev.preventDefault();
              ev.stopPropagation();
              return element.slideToggle();
            });
          }
        };
      }
    ]);
    Admin_App.directive('dpToggleSwitch', function() {
      return {
        restrict: 'A',
        require: 'ngModel',
        template: "<div class=\"dp-switch\">\n	<label><span></span></label>\n</div>",
        replace: true,
        scope: {
          model: '=ngModel',
          lockedModel: '=lockedModel',
          change: '=ngChange',
          lockedTip: '@'
        },
        link: function(scope, element, attrs, ngModel) {
          var tipTarget, updateVal;
          updateVal = function() {
            var val;
            val = scope.model;
            ngModel.$setViewValue(val);
            scope.model = val;
            if (val) {
              element.addClass('switch-on');
              element.removeClass('switch-off');
            } else {
              element.removeClass('switch-on');
              element.addClass('switch-off');
            }
            if (scope.change) {
              return scope.$eval(scope.change);
            }
          };
          element.on('click', function(ev) {
            ev.preventDefault();
            if (element.hasClass('locked')) {
              return;
            }
            scope.model = !scope.model;
            return scope.$apply(function() {
              return updateVal(updateVal);
            });
          });
          scope.$watch('model', function() {
            return updateVal();
          });
          scope.$watch('lockedModel', function(newVal) {
            if (newVal) {
              return element.addClass('locked');
            } else {
              return element.removeClass('locked');
            }
          });
          if (scope.lockedTip) {
            tipTarget = angular.element('<div class="mouse-target show-on-locked-on"></div>');
            tipTarget.attr('title', scope.lockedTip);
            tipTarget.appendTo(element);
            tipTarget.tooltip({
              placement: 'auto top',
              trigger: 'hover',
              container: 'body'
            });
          }
          if (scope.model) {
            ngModel.$setViewValue(true);
            element.addClass('switch-on');
            return element.removeClass('switch-off');
          }
        }
      };
    });
    Admin_App.directive('dpTabBtn', function() {
      return {
        restrict: 'A',
        link: function(scope, element, attrs) {
          var id_segs, tab_group, tab_val;
          if (!scope.dp_tab_ids) {
            scope.dp_tab_ids = {};
          }
          id_segs = attrs['dpTabBtn'];
          if (!id_segs) {
            return;
          }
          id_segs = id_segs.split('.');
          tab_val = id_segs.pop();
          tab_group = id_segs.join('.');
          if (element.hasClass('active')) {
            scope.dp_tab_ids[tab_group] = tab_val;
          }
          element.on('click', function(ev) {
            ev.preventDefault();
            scope.dp_tab_ids[tab_group] = tab_val;
            return scope.$apply();
          });
          return scope.$watch(function() {
            return scope.dp_tab_ids[tab_group];
          }, function(newVal) {
            if (newVal === tab_val) {
              return element.addClass('active');
            } else {
              return element.removeClass('active');
            }
          });
        }
      };
    });
    Admin_App.directive('dpTabBody', function() {
      return {
        restrict: 'A',
        link: function(scope, element, attrs) {
          var id_segs, tab_group, tab_val;
          if (!scope.dp_tab_ids) {
            scope.dp_tab_ids = {};
          }
          id_segs = attrs['dpTabBody'];
          if (!id_segs) {
            return;
          }
          id_segs = id_segs.split('.');
          tab_val = id_segs.pop();
          tab_group = id_segs.join('.');
          if (scope.dp_tab_ids[tab_group] === tab_val) {
            element.show();
          } else {
            element.hide();
          }
          return scope.$watch(function() {
            return scope.dp_tab_ids[tab_group];
          }, function(newVal) {
            if (newVal === tab_val) {
              return element.show();
            } else {
              return element.hide();
            }
          });
        }
      };
    });
    Admin_App.directive('bgImg', function() {
      return {
        restrict: 'A',
        scope: {
          'bgImg': '&'
        },
        link: function(scope, element, attrs) {
          return element.css({
            'background-image': 'url("' + scope.$eval(scope.bgImg) + '")'
          });
        }
      };
    });
    Admin_App.directive('dpServerValidation', function() {
      return {
        require: 'ngModel',
        restrict: 'A',
        link: function(scope, elm, attrs, ngModel) {
          ngModel.dpServerValidationKeys = attrs.dpServerValidation.split(',');
          if (!ngModel.dpServerValidationKeys.length) {
            return;
          }
          return ngModel.$parsers.unshift(function(viewValue) {
            var code, code_safe, code_segs, error_code, is_error, last_seg, _i, _len, _ref, _ref1;
            _ref = ngModel.$error;
            for (error_code in _ref) {
              if (!__hasProp.call(_ref, error_code)) continue;
              is_error = _ref[error_code];
              if (!is_error) {
                continue;
              }
              _ref1 = ngModel.dpServerValidationKeys;
              for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
                code = _ref1[_i];
                code_safe = code.replace(/\./g, '_');
                if (error_code === code_safe) {
                  code_segs = code.split('.');
                  last_seg = code_segs.pop();
                  switch (last_seg) {
                    case 'required':
                      ngModel.$setValidity('required', true);
                      break;
                    default:
                      ngModel.$setValidity(code_safe, true);
                  }
                }
              }
            }
            return viewValue;
          });
        }
      };
    });
    Admin_App.factory('translateDpInterpolation', function() {
      var choosePlural, regexQuote;
      choosePlural = function(text, number) {
        var parts;
        parts = text.split('|');
        if (number === 0 || number !== 1) {
          return parts[1];
        } else {
          return parts[0];
        }
      };
      regexQuote = function(strRegex) {
        return strRegex.replace(/([.?*+^$[\]\\(){}-])/g, "\\$1");
      };
      return {
        setLocale: function(locale) {},
        getInterpolationIdentifier: function() {
          return 'dp';
        },
        interpolate: function(text, vars) {
          var is_raw, key, re, value;
          if (!vars) {
            return text;
          }
          if (vars.count_length != null) {
            vars.count = vars.count_length.length;
          }
          if (vars.count != null) {
            text = choosePlural(text);
          }
          is_raw = vars.as_raw != null;
          for (key in vars) {
            if (!__hasProp.call(vars, key)) continue;
            value = vars[key];
            re = new RegExp('\{\{\s*' + regexQuote(key) + '\s*\}\}', 'g');
            if (is_raw) {
              text = text.replace(re, value);
            } else {
              text = text.replace(re, _.escape(value));
            }
          }
          return text;
        }
      };
    });
    Admin_App.factory('xxxtranslateDpStorage', function() {
      return {
        DP_LANG: DP_LANG,
        set: function(name, value) {
          return DP_LANG[name] = value;
        },
        get: function(name) {
          if (name === 'NG_TRANSLATE_LANG_KEY') {
            return 'en';
          }
          if (DP_LANG[name] != null) {
            return DP_LANG[name];
          } else {
            return '';
          }
        }
      };
    });
    Admin_App.config([
      '$translateProvider', function($translateProvider) {
        $translateProvider.translations('default', DP_LANG);
        $translateProvider.preferredLanguage('default');
        return $translateProvider.useInterpolation('translateDpInterpolation');
      }
    ]);
    Admin_App.config([
      '$stateProvider', '$urlRouterProvider', function($stateProvider, $urlRouterProvider) {
        var id, opts, route, segs, url, views, with_lists, _i, _len, _results;
        $urlRouterProvider.otherwise("/");
        with_lists = {};
        _results = [];
        for (_i = 0, _len = routing.length; _i < _len; _i++) {
          route = routing[_i];
          id = route.id;
          url = route.url;
          views = {};
          if (route.nav != null) {
            views['dp_section_nav'] = route.nav;
          }
          if (route.list != null) {
            views['dp_section_list@'] = route.list;
          }
          if (route.page != null) {
            views['dp_section_page@'] = route.page;
          }
          opts = {
            url: url,
            views: views,
            with_nav_view: true
          };
          if (route.with_list_view) {
            opts.with_list_view = true;
          } else if (route.list != null) {
            opts.with_list_view = true;
          } else if (route.page != null) {
            segs = id.split('.');
            segs.pop();
            if (with_lists[segs.join('.')]) {
              opts.with_list_view = true;
            }
          }
          if (route.with_nav_view != null) {
            opts.with_nav_view = route.with_nav_view;
          }
          if (opts.with_list_view) {
            with_lists[id] = true;
          }
          _results.push($stateProvider.state(id, opts));
        }
        return _results;
      }
    ]);
    Admin_App.run([
      '$http', '$templateCache', function($http, $templateCache) {
        var qs, t, templates, _i, _len;
        templates = ['Index/app-nav-setup.html', 'Index/app-nav-agents.html', 'Index/app-nav-tickets.html', 'Index/app-nav-crm.html', 'Index/app-nav-portal.html', 'Index/app-nav-chat.html', 'Index/app-nav-twitter.html', 'Index/app-nav-apps.html', 'Index/app-nav-server.html', 'Index/modal-alert.html', 'Index/modal-confirm-leavetab.html', 'TicketDeps/code-link.html', 'TicketDeps/code-win.html', 'TicketDeps/code-embed.html', 'Index/blank.html'];
        qs = [];
        for (_i = 0, _len = templates.length; _i < _len; _i++) {
          t = templates[_i];
          qs.push('views[]=' + encodeURIComponent(t));
        }
        qs = qs.join('&');
        $http({
          method: 'GET',
          url: DP_BASE_ADMIN_URL + '/load-view/multi?' + qs
        }).success(function(data) {
          var id, tpl, _j, _len1, _results;
          _results = [];
          for (_j = 0, _len1 = data.length; _j < _len1; _j++) {
            tpl = data[_j];
            id = DP_BASE_ADMIN_URL + '/load-view/' + tpl.id;
            _results.push($templateCache.put(id, tpl.source));
          }
          return _results;
        });
        return window.TC = $templateCache;
      }
    ]);
    if ((_ref = window.parent) != null ? _ref.DP_FRAME_OVERLAY_admin : void 0) {
      if ((_ref1 = window.parent) != null) {
        _ref1.DP_FRAME_OVERLAY_admin.callLoaded();
      }
    }
    return Admin_App;
  });

}).call(this);

/*
//@ sourceMappingURL=App.map
*/
