// Generated by CoffeeScript 1.6.3
(function() {
  define(['angular', 'Admin/Resources/config/routing', 'Admin/Main/Service/AppState', 'Admin/Main/Service/DpApi', 'Admin/Main/DataService/EntityManager', 'Admin/Main/DataService/Departments'], function(angular, routing, Admin_Main_Service_AppState, Admin_Main_Service_DpApi, Admin_Main_DataService_EntityManager, Admin_Main_DataService_Departments) {
    var Admin_App;
    Admin_App = angular.module('Admin_App', ['ui.router', 'ui.bootstrap', 'ui.select2']);
    Admin_App.service('AppState', [
      '$rootScope', '$state', function($rootScope, $state) {
        return new Admin_Main_Service_AppState($rootScope, $state);
      }
    ]);
    Admin_App.service('Api', [
      '$http', function($http) {
        return new Admin_Main_Service_DpApi($http, window.DP_BASE_API_URL, window.DP_API_TOKEN);
      }
    ]);
    Admin_App.factory('$exceptionHandler', [
      '$log', function($log) {
        return function(exception, cause) {
          throw exception;
        };
      }
    ]);
    Admin_App.service('em', [
      function() {
        return new Admin_Main_DataService_EntityManager();
      }
    ]);
    Admin_App.service('DepartmentData', [
      'em', 'Api', '$q', function(em, Api, $q) {
        return new Admin_Main_DataService_Departments(em, Api, $q);
      }
    ]);
    Admin_App.directive('dpStateMark', [
      '$rootScope', '$state', function($rootScope, $state) {
        return {
          restrict: 'A',
          link: function(scope, element, attrs) {
            var checkState, current_state_id, _ref;
            checkState = function(stateId, newStateId) {
              var stateIdRegex;
              if (!stateId || !newStateId) {
                return;
              }
              stateIdRegex = '^';
              stateIdRegex += stateId.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&");
              stateIdRegex += '\\b';
              if (newStateId.match(new RegExp(stateIdRegex))) {
                return true;
              } else {
                return false;
              }
            };
            if ((_ref = $state.current) != null ? _ref.name : void 0) {
              current_state_id = $state.current.name;
              if ($state.params.id) {
                current_state_id += '.' + $state.params.id;
              }
              if (checkState(attrs.dpStateMark, current_state_id)) {
                element.addClass('state-on active');
              }
            }
            return $rootScope.$on('dp_activeStateChange', function(ev, newStateId) {
              if (checkState(attrs.dpStateMark, newStateId)) {
                return element.addClass('state-on active');
              } else {
                return element.removeClass('state-on active');
              }
            }, true);
          }
        };
      }
    ]);
    Admin_App.directive('dpToggleSwitch', function() {
      return {
        restrict: 'A',
        require: 'ngModel',
        template: '<div ng-class="{\'switch-on\': model, \'switch-off\': !model}"><input type="checkbox" /></div>',
        replace: true,
        scope: {
          options: '@dpToggleSwitch',
          model: '=ngModel'
        },
        link: function(scope, element, attrs, ngModel) {
          var $wrap, options;
          if (scope.options) {
            options = scope.$eval(scope.options);
          } else {
            options = {};
          }
          $wrap = jQuery(element);
          $wrap.attr('data-off-label', options['off-label'] || "<i class='icon-remove'></i>");
          $wrap.attr('data-on-label', options['on-label'] || "<i class='icon-ok'></i>");
          $wrap.attr('data-off', options['off-class'] || "danger");
          $wrap.attr('data-on', options['on-class'] || "success");
          $wrap.addClass('dp-switch');
          if (scope["class"]) {
            $wrap.addClass(scope["class"]);
          }
          if (scope.model) {
            $wrap.find('input').get(0).checked = true;
            ngModel.$setViewValue(true);
          }
          $wrap.bootstrapSwitch();
          return $wrap.find('input').on('change', function() {
            var el;
            el = this;
            return scope.$apply(function() {
              var val;
              val = !!el.checked;
              ngModel.$setViewValue(val);
              return scope.model = val;
            });
          });
        }
      };
    });
    Admin_App.config([
      '$stateProvider', '$urlRouterProvider', function($stateProvider, $urlRouterProvider) {
        var id, route, url, views, _i, _len, _results;
        $urlRouterProvider.otherwise("/");
        _results = [];
        for (_i = 0, _len = routing.length; _i < _len; _i++) {
          route = routing[_i];
          id = route.id;
          url = route.url;
          views = {};
          if (route.nav != null) {
            views['dp_section_nav'] = route.nav;
          }
          if (route.list != null) {
            views['dp_section_list@'] = route.list;
          }
          if (route.page != null) {
            views['dp_section_page@'] = route.page;
          }
          _results.push($stateProvider.state(id, {
            url: url,
            views: views
          }));
        }
        return _results;
      }
    ]);
    return Admin_App;
  });

}).call(this);

/*
//@ sourceMappingURL=App.map
*/
