// Generated by CoffeeScript 1.6.3
(function() {
  define(['angular', 'Admin/Resources/config/routing', 'Admin/Main/Service/AppState', 'Admin/Main/Directive/ActiveStateMark'], function(angular, routing, Admin_Main_Service_AppState, Admin_Main_Directive_ActiveStateMark) {
    var Admin_App;
    Admin_App = angular.module('Admin_App', ['ui.router']);
    Admin_App.service('AppState', Admin_Main_Service_AppState);
    Admin_App.directive('dpStateMark', Admin_Main_Directive_ActiveStateMark);
    Admin_App.config([
      '$stateProvider', '$urlRouterProvider', function($stateProvider, $urlRouterProvider) {
        var id, route, url, views, _i, _len, _results;
        $urlRouterProvider.otherwise("/settings/ticket_deps");
        _results = [];
        for (_i = 0, _len = routing.length; _i < _len; _i++) {
          route = routing[_i];
          id = route.id;
          url = route.url;
          views = {};
          if (route.nav != null) {
            views['dp_section_nav'] = route.nav;
          }
          if (route.list != null) {
            views['dp_section_list@'] = route.list;
          }
          if (route.page != null) {
            views['dp_section_page@'] = route.page;
          }
          _results.push($stateProvider.state(id, {
            url: url,
            views: views
          }));
        }
        return _results;
      }
    ]);
    return Admin_App;
  });

}).call(this);
