sandbox_widgets:
    type: rest
    resource: DeskPRO\Bundle\ApiBundle\Controller\Sandbox\SandboxWidgetsController

me:
    type: rest
    resource: DeskPRO\Bundle\ApiBundle\Controller\Authentication\MeController

api_tokens:
    type: rest
    resource: DeskPRO\Bundle\ApiBundle\Controller\Authentication\ApiTokensController

api_batch_annotation:
    type: annotation
    resource: "@ApiBundle/Controller/BatchController.php"

ticket_filters:
    type: annotation
    resource: DeskPRO\Bundle\ApiBundle\Controller\Filters\FiltersController

ticket_filter_sets:
    type: rest
    resource: DeskPRO\Bundle\ApiBundle\Controller\Filters\TicketFilterSetsController
