sandbox_widgets:
    type: rest
    resource: DeskPRO\Bundle\ApiBundle\Controller\SandboxWidgetsController

#ticket_filters:
#    type: rest
#    resource: DeskPRO\Bundle\ApiBundle\Controller\Tickets\TicketFiltersController