sandbox:
    type: rest
    resource: DeskPRO\Bundle\ApiBundle\Controller\SandboxController
ticket_filters:
    type: rest
    resource: DeskPRO\Bundle\ApiBundle\Controller\Tickets\TicketFiltersController