app:
  notification:
    strategies:
      notification.agent_chat.new_message:
        strategy: immediate
        delivery:
          - pusher
      notification.yet.another.system.event:
        strategy: deferred
        delivery:
          - db
        persistance: db