
security:
    providers:
        dp_person_user_provider:
            id: dp_person_user_provider

    firewalls:
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js|web)/
#            security: false
        portal:
            pattern: ^/
            provider: dp_person_user_provider
            deskpro_form_login:
                failure_path: /login?retry=auth
            anonymous: ~
            logout:
                path: portal_logout
                target: /
                invalidate_session: false
                handlers:  [security.authentication.logout_handler]
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # the current domain from $_SERVER
                remember_me_parameter: remember_me


services:
    dp_authentication_manager.user:
        class: Application\DeskPRO\Auth\AuthenticationManager
        factory_class: Application\DeskPRO\DependencyInjection\SystemServices\AuthenticationManagerService
        factory_method: create
        arguments: [@service_container, 'user']

    dp_auth_settings:
        class: Application\DeskPRO\Auth\AuthSettings
        factory_class: Application\DeskPRO\DependencyInjection\SystemServices\AuthSettingsService
        factory_method: create
        arguments: [@service_container]

    dp_person_user_provider:
        class: Application\AuthBundle\Security\DpPersonUserProvider
        arguments: [@person_repository]

    dp_security.form_login.provider:
        class: Application\AuthBundle\Security\Authentication\Provider\DpFormLoginProvider
        arguments: [@dp_authentication_manager.user,@dp_person_user_provider]

    dp_security.form_login.listener:
        class: Application\AuthBundle\Security\Firewall\DpAuthListener
        parent: security.authentication.listener.abstract
        abstract: true
        calls:
            - [ setContainer, [@service_container] ]

    security.authentication.success_handler:
            class:  Application\AuthBundle\Handler\AuthenticationSuccessHandler
            arguments:  [@security.http_utils, {}]
            calls:
                - [ setContainer, [ @service_container ] ]
            tags:
                - { name: 'monolog.logger', channel: 'security' }

    security.authentication.logout_handler:
            class:  Application\AuthBundle\Handler\LogoutHandler

    security.authentication.failure_handler:
        class: Application\AuthBundle\Handler\AuthenticationFailureHandler
        arguments:  [@http_kernel, @security.http_utils, {}, @logger]
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    dp_security.twig_extension:
        class: Application\AuthBundle\Twig\AuthTwigExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }