services:

    # use a custom user/password validator
    security.validator.user_password:
        class: Application\AuthBundle\Validator\Constraints\UserPasswordValidator
        arguments: [@security.token_storage]
        tags:
            - { name: validator.constraint_validator, alias: security.validator.user_password }