#!/usr/bin/env php
<?php
require(__DIR__.'/lib/env.php');

use Symfony\Component\Console\Application;
use DeskPRO\Services\EmailCollection\Command\EmailCollectionCommand;

$application = new Application();
$application->add(new EmailCollectionCommand());
$application->run();