#!/usr/bin/env php
<?php
require(__DIR__.'/lib/env.php');

$opts = getopt("s:l:h", array('service:', 'lockfile:', 'php-bin:', 'help'));

if (isset($opts['h']) || isset($opts['help'])) {
    echo "Use this command to start a service only if it's not already running. This is useful when ";
    echo "you are using a system like cron to ensure services are running.\n\n";
    echo "\t--service    The service name.\n";
    echo "\t--lockfile   (Optional) Path to a lockfile. By default it will be placed in the DeskPRO tmp directory.\n";
    echo "\t--php-bin    (Optional) Path to the PHP CLI binary.\n";
    echo "\t-- [args]    Anything after a double-dash will be passed directly to the service.\n";
    echo "\n";
    echo "Example:\n";
    echo "\tservice-cron --service email:collection -- --load-config\n";
    echo "\tservice-cron --service email:process -- --load-config\n";
    echo "\n";
    exit;
}

$service  = @$opts['s'] ?: @$opts['service'];
$lockfile = @$opts['l'] ?: @$opts['lockfile:'];
$php_bin  = @$opts['php-bin'] ?: dp_get_php_path();

if (empty($service)) {
    echo "You must specify the --service option.\n";
    exit(1);
}

if (empty($php_bin)) {
    echo "The path to PHP could not be determined. Use --php-bin to specify the path.";
    exit(1);
}

if (empty($lockfile)) {
    $lockfile = dp_get_tmp_dir() . DIRECTORY_SEPARATOR . preg_replace('#[^a-z0-9]#', '_', $service) . '.lock';
}

if ($pos = array_search('--', $_SERVER['argv'])) {
    $args = array_slice($_SERVER['argv'], $pos + 1);
} else {
    $args = array();
}

$service_path = __DIR__.DIRECTORY_SEPARATOR.'service';
$cmd = trim($php_bin . ' ' . $service_path . ' ' . $service . ' ' . implode(' ', $args));
$fp = fopen($lockfile, 'w') or exit(1);

if (flock($fp, LOCK_EX | LOCK_NB)) {
    set_time_limit(0);
    fwrite($fp, "Service: $service\nCommand: $cmd\nTime: ".time());
    fflush($fp);
    passthru($cmd);
    @flock($fp, LOCK_UN);
}

@fclose($fp);