#!/usr/bin/env php
<?php

require_once __DIR__.'/DeskproKernel.php';

use Symfony\Framework\FoundationBundle\Console\Application;

$kernel = new DeskproKernel('dev', true);

$application = new Application($kernel);
$application->run();
