# This is the "main" file for the api kernel. No other kernel imports this.
# 1) It avoids recursion in the loader, and 2) Let's us add specific route config for this kernel only
api_routes:
    resource: "@ApiBundle/Resources/config/routing_api.yml"
    prefix: /api/v2

portal_routes:
    resource: "@PortalBundle/Resources/config/routing_portal.yml"

agent_routes:
    resource: "@AgentBundle/Resources/config/agent-routing.php"

dp_routes:
    resource: "@DeskPRO/Resources/config/dp-routing.php"

dpkernel_routes:
    resource: "@DeskPRO/Resources/config/dp-routing.php"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/v2/doc
