imports:
    - { resource: ../config.shared.php }

# Keeping all parameter changes here rather than in various bundles
parameters:
  router.options.matcher.cache_class: null
  portal.session.name: sess_data
  doctrine.orm.proxy_dir: %kernel.cache_dir%/../../doctrine-proxies
  fos_rest.routing.loader.reader.controller.class: DeskPRO\Bundle\ApiBundle\Routing\ApiRestControllerReader
  hateoas.serializer.json_hal.class: DeskPRO\Bundle\ApiBundle\Serializer\HateoasJsonApiSerializer
  monolog.logger.class: DeskPRO\Bundle\AppBundle\Logging\NoExceptionsLogger
  file_locator.class: DeskPRO\Bundle\AppBundle\HttpKernel\Config\FileLocator
  nelmio_api_doc.extractor.api_doc_extractor.class: DeskPRO\Bundle\ApiBundle\ApiDoc\Extractor\ApiDocExtractor

api:
    data_serializer:
    # This is where we define the map, but you only need to do this if your "type" does not map
    # directly to the underscore version of the object name. For example, if
    # "DeskPRO\\Bundle\\AppBundle\\Entity\\SandboxWidget" is for type "sandbox_widget" then
    # it does NOT need to be in this map because the naming convention is the default.
        types:
            avatar:
                classes:
                    - DeskPRO\Bundle\AppBundle\Content\Avatar

framework:
    esi:             { enabled: true }
    fragments:       { path: /_proxy }
    #translator:      { fallback: "%locale%" }
    secret:          "irrelevant - compiler pass will override this"
    router:
        resource: "%kernel.root_dir%/config/api/api_routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies:
        - 127.0.0.1
    session: ~
#        handler_id:  session.handler.dbal
    fragments:       ~
    http_method_override: true

monolog:
    channels: # you MUST also update portal_config.yml if you change these
        - "dp.tickets.filters.tengine.dbal.engine"
        - "dp.tickets.filters.tengine.dbal.compiler"
        - "dp.tickets.filters.tengine.php.engine"
        - "dp.tickets.filters.tengine.php.compiler"
    handlers:
        main:
            type:   service
            id:     monolog.handler.deskpro_fingers_crossed
        term_engine:
            type: service
            id: term_engine.log_handler
            channels:
                - "dp.tickets.filters.tengine.dbal.engine"
                - "dp.tickets.filters.tengine.dbal.compiler"
                - "dp.tickets.filters.tengine.php.engine"
                - "dp.tickets.filters.tengine.php.compiler"

jms_serializer:
    visitors:
        json:
            options: 128 # JSON_PRETTY_PRINT constant unavailable in php 5.3, use int instead

fos_rest:
    disable_csrf_role: ROLE_API
    routing_loader:
        default_format: json
        include_format: false
    allowed_methods_listener: true
    body_converter:
        enabled: false
    param_fetcher_listener: true
    serializer:
        serialize_null: true
    body_listener:
        default_format: json
        throw_exception_on_unsupported_content_type:  true
        decoders:
            json: fos_rest.decoder.jsontoform
        array_normalizer:
            forms: false
    service:
        inflector: api_url_inflector
    format_listener:
        rules:
            - { path: '^/api/v2', priorities: ['json', 'jsonp'], fallback_format: json, exception_fallback_format: json, prefer_extension: false }
    exception:
        enabled: true
        exception_controller: 'DeskPRO\Bundle\ApiBundle\Controller\ExceptionController::showAction'
    view:
        view_response_listener: force
        formats:
            json: true
            jsonp: true
            html: false
        jsonp_handler:
            callback_param: callback
        failed_validation: HTTP_BAD_REQUEST
    routing_loader:
        default_format: json

nelmio_api_doc:
    name: 'DeskPRO API Documentation'
    sandbox:
        enabled: false
    cache:
        enabled: true
        file: '%kernel.cache_dir%/api-doc.cache'

# Security Configuration
security:
    providers:
        dp_person_user_provider:
            id: dp_person_user_provider

    firewalls:
        api_doc:
            pattern: ^/api/v2/doc
            stateless: true
            anonymous: ~
        api_tokens_request:
            pattern: ^/api/v2/api_tokens$
            stateless: true
            anonymous: ~
        api:
            pattern: ^/api/v2(?!/api_tokens|/doc|/get_session$)
            stateless: true
            simple_preauth:
                authenticator: api_authenticator

    access_control:
        - { path: '^/api/v2(?!/api_tokens|/doc|/get_session)', roles: ['ROLE_API'] }

sensio_framework_extra:
    cache:    { annotations: true }
    security:    { annotations: true }

white_october_pagerfanta:
    default_view: deskpro
    exceptions_strategy:
        out_of_range_page:        to_http_not_found
        not_valid_current_page:   to_http_not_found

doctrine:
     orm:
         dql:
             datetime_functions:
                 date: DoctrineExtensions\Query\Mysql\Date

             string_functions:
                 field: DoctrineExtensions\Query\Mysql\Field
                 group_concat: DoctrineExtensions\Query\Mysql\GroupConcat
