imports:
  - { resource: api_config.yml }

framework:
    profiler: { only_exceptions: false }
    router:
        resource: "%kernel.root_dir%/config/api/api_routing_dev.yml"
        strict_requirements: true

debug:
    max_items: 400

