language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - app/tests/travis-ci/before-script

after_failure:
  - app/tests/travis-ci/after-failure

after_success:
  - app/tests/travis-ci/after-success

script: app/tests/bin/run-tests

#notifications:
#  hipchat:
#    rooms:
#      secure: bqrfROrUT4nmOdLkMRRS09BgIJ6CwGUcND76j5dRkwdGzKrsDYU/FyvLr3sjMZ611ehHOGz/cScBY1ZyuYNBAdqzBL8K1RtbvdukX0Ktt+BUJPepIXfV1T8wtvce0DhVvc2ILzoBynoCsmts1/qQNcKDI+4/5z0rA1GK8m9u7ao=

cache:
  apt: true

services:
  - elasticsearch
