base_path: /app/BUILD/locales
files:
  - source: /en-US/helpcenter.yml
    translation: /%locale%/helpcenter.yml
    languages_mapping:
      locale:
        ar-SA: ar
        bg-BG: bg
        cs-CZ: cs
        da-DK: da
        de-DE: de
        el-GR: el
        fa-IR: fa
        fi-FI: fi
        fr-FR: fr
        hu-HU: hu
        id-ID: id
        it-IT: it
        ja-JP: ja
        ko-KR: ko
        nl-NL: nl
        no-NO: 'no'
        pl-PL: pl
        ru-RU: ru
        sk-SK: sk
        sv-SE: sv
        tr-TR: tr
        vi-VN: vi
