<?php
// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile


use \Codeception\Maybe;
use Codeception\Module\DpControlHelper;
use Codeception\Module\CodeHelper;

/**
 * Inherited methods
 * @method void execute($callable)
 * @method void wantToTest($text)
 * @method void wantTo($text)
 * @method void expectTo($prediction)
 * @method void expect($prediction)
 * @method void amGoingTo($argumentation)
 * @method void am($role)
 * @method void lookForwardTo($achieveValue)
 * @method void offsetGet($offset)
 * @method void offsetSet($offset, $value)
 * @method void offsetExists($offset)
 * @method void offsetUnset($offset)
*/

class CodeGuy extends \Codeception\AbstractGuy
{
    
    /**
     * This method is generated.
     * Documentation taken from corresponding module.
     * ----------------------------------------------
     *
     * @return \Application\DeskPRO\DependencyInjection\DeskproContainer
     * @see Codeception\Module\DpControlHelper::getSymfonyContainer()
     * @return \Codeception\Maybe
     */
    public function getSymfonyContainer() {
        $this->scenario->addStep(new \Codeception\Step\Action('getSymfonyContainer', func_get_args()));
        if ($this->scenario->running()) {
            $result = $this->scenario->runStep();
            return new Maybe($result);
        }
        return new Maybe();
    }

 
    /**
     * This method is generated.
     * Documentation taken from corresponding module.
     * ----------------------------------------------
     *
     * Sets the database set to a version of the set. If it already exists,
	 * it will be re-used (not recreated).
	 *
	 * @param string $set_name
     * @see Codeception\Module\DpControlHelper::enableDatabaseSet()
     * @return \Codeception\Maybe
     */
    public function enableDatabaseSet($set_name) {
        $this->scenario->addStep(new \Codeception\Step\Action('enableDatabaseSet', func_get_args()));
        if ($this->scenario->running()) {
            $result = $this->scenario->runStep();
            return new Maybe($result);
        }
        return new Maybe();
    }

 
    /**
     * This method is generated.
     * Documentation taken from corresponding module.
     * ----------------------------------------------
     *
     * Like enableDatabaseSet but will always use a freshly built db.
	 *
	 * @param string $set_name
     * @see Codeception\Module\DpControlHelper::enableFreshDatabaseSet()
     * @return \Codeception\Maybe
     */
    public function enableFreshDatabaseSet($set_name) {
        $this->scenario->addStep(new \Codeception\Step\Action('enableFreshDatabaseSet', func_get_args()));
        if ($this->scenario->running()) {
            $result = $this->scenario->runStep();
            return new Maybe($result);
        }
        return new Maybe();
    }

 
    /**
     * This method is generated.
     * Documentation taken from corresponding module.
     * ----------------------------------------------
     *
     * Like enableDatabaseSet except this will reset the database set afterwards.
	 *
	 * @param string $set_name
	 * @param bool $reset True to mark the db for reset
     * @see Codeception\Module\DpControlHelper::enableDestructiveDatabaseSet()
     * @return \Codeception\Maybe
     */
    public function enableDestructiveDatabaseSet($set_name, $reset = null) {
        $this->scenario->addStep(new \Codeception\Step\Action('enableDestructiveDatabaseSet', func_get_args()));
        if ($this->scenario->running()) {
            $result = $this->scenario->runStep();
            return new Maybe($result);
        }
        return new Maybe();
    }

 
    /**
     * This method is generated.
     * Documentation taken from corresponding module.
     * ----------------------------------------------
     *
     * Returns the currently set database back to the default.
     * @see Codeception\Module\DpControlHelper::useDefaultDatabase()
     * @return \Codeception\Maybe
     */
    public function useDefaultDatabase() {
        $this->scenario->addStep(new \Codeception\Step\Action('useDefaultDatabase', func_get_args()));
        if ($this->scenario->running()) {
            $result = $this->scenario->runStep();
            return new Maybe($result);
        }
        return new Maybe();
    }

 
    /**
     * This method is generated.
     * Documentation taken from corresponding module.
     * ----------------------------------------------
     *
     * @return int
     * @see Codeception\Module\DpControlHelper::getContainerCounter()
     * @return \Codeception\Maybe
     */
    public function getContainerCounter() {
        $this->scenario->addStep(new \Codeception\Step\Action('getContainerCounter', func_get_args()));
        if ($this->scenario->running()) {
            $result = $this->scenario->runStep();
            return new Maybe($result);
        }
        return new Maybe();
    }

 
    /**
     * This method is generated.
     * Documentation taken from corresponding module.
     * ----------------------------------------------
     *
     * Loads fixtures into the current database.
	 * Note that this will mark the database to be reset.
	 *
	 * @param array $f...
	 * @throws \InvalidArgumentException
     * @see Codeception\Module\DpControlHelper::loadFixtures()
     * @return \Codeception\Maybe
     */
    public function loadFixtures($f) {
        $this->scenario->addStep(new \Codeception\Step\Action('loadFixtures', func_get_args()));
        if ($this->scenario->running()) {
            $result = $this->scenario->runStep();
            return new Maybe($result);
        }
        return new Maybe();
    }

 
    /**
     * This method is generated.
     * Documentation taken from corresponding module.
     * ----------------------------------------------
     *
     *
     * @see Codeception\Module::getName()
     * @return \Codeception\Maybe
     */
    public function getName() {
        $this->scenario->addStep(new \Codeception\Step\Action('getName', func_get_args()));
        if ($this->scenario->running()) {
            $result = $this->scenario->runStep();
            return new Maybe($result);
        }
        return new Maybe();
    }
}

