services:
  form.ticket:
    class: Application\FormBundle\Form\Type\TicketType
    tags:
      - { name: form.type, alias: deskpro_ticket }
  form.language:
    class: Application\FormBundle\Form\Type\LanguageType
    tags:
      - { name: form.type, alias: deskpro_language }
  form.department:
    class: Application\FormBundle\Form\Type\DepartmentType
    tags:
      - { name: form.type, alias: deskpro_department }
  form.product:
    class: Application\FormBundle\Form\Type\ProductType
    tags:
      - { name: form.type, alias: deskpro_product }
  form.workflow:
    class: Application\FormBundle\Form\Type\WorkflowType
    tags:
      - { name: form.type, alias: deskpro_workflow }
  form.priority:
    class: Application\FormBundle\Form\Type\PriorityType
    tags:
      - { name: form.type, alias: deskpro_priority }
  form.captcha:
    class: Application\FormBundle\Form\Type\CaptchaType
    arguments: [@brand_stack]
    tags:
      - { name: form.type, alias: deskpro_captcha }
  form.heirarchical_entity:
    class: Application\FormBundle\Form\Type\HeirarchicalEntity
    tags:
      - { name: form.type, alias: deskpro_heirarchical_entity }