services:
  form.extension.deskpro:
    class: Application\FormBundle\Form\Extension\DeskproExtension
    tags:
      - { name: form.type_extension, alias: form }
  form_field_manager:
    class: Application\FormBundle\Form\FormFieldManager
    arguments: [@doctrine.orm.default_entity_manager]
  form.custom_data_ticket:
    class: Application\FormBundle\Form\Type\CustomDataTicketType
    arguments: [@form_field_manager]
    tags:
      - { name: form.type, alias: deskpro_custom_data_ticket }
  form.ticket:
    class: Application\FormBundle\Form\Type\TicketType
    arguments: [@form_field_manager]
    tags:
      - { name: form.type, alias: deskpro_ticket }
  form.language:
    class: Application\FormBundle\Form\Type\LanguageType
    tags:
      - { name: form.type, alias: deskpro_language }
  form.department:
    class: Application\FormBundle\Form\Type\DepartmentType
    tags:
      - { name: form.type, alias: deskpro_department }
  form.product:
    class: Application\FormBundle\Form\Type\ProductType
    tags:
      - { name: form.type, alias: deskpro_product }
  form.category:
    class: Application\FormBundle\Form\Type\CategoryType
    tags:
      - { name: form.type, alias: deskpro_category }
  form.workflow:
    class: Application\FormBundle\Form\Type\WorkflowType
    tags:
      - { name: form.type, alias: deskpro_workflow }
  form.priority:
    class: Application\FormBundle\Form\Type\PriorityType
    tags:
      - { name: form.type, alias: deskpro_priority }
  form.captcha:
    class: Application\FormBundle\Form\Type\CaptchaType
    arguments: [@brand_stack]
    tags:
      - { name: form.type, alias: deskpro_captcha }
  form.heirarchical_entity:
    class: Application\FormBundle\Form\Type\HeirarchicalEntity
    tags:
      - { name: form.type, alias: deskpro_heirarchical_entity }