services:

  form.ticket:
    class: Application\FormBundle\Form\Type\TicketType
    arguments: [@form_field_manager, @ticket_layout_factory, @ticket_layout_differ, @form_hierarchy_generator, @doctrine.orm.default_entity_manager, @language_manager]
    tags:
      - { name: form.type, alias: ticket }


  form.ticket_reply:
    class: Application\FormBundle\Form\Type\TicketReplyType
    tags:
      - { name: form.type, alias: ticket_reply }


  form.person_registration:
    class: Application\FormBundle\Form\Type\PersonRegistrationType
    arguments: [@form_field_manager, @language_manager]
    tags:
      - { name: form.type, alias: person_registration }


  form.person_manage_emails:
    class: Application\FormBundle\Form\Type\PersonManageEmailsType
    arguments: [@doctrine.orm.default_entity_manager]
    tags:
      - { name: form.type, alias: person_manage_emails }


  form.person_profile:
    class: Application\FormBundle\Form\Type\PersonEditProfileType
    arguments: [@form_field_manager, @language_manager, @blob.storage, @doctrine.orm.default_entity_manager]
    tags:
      - { name: form.type, alias: person_profile }


  form.comment:
    class: Application\FormBundle\Form\Type\CommentType
    tags:
      - { name: form.type, alias: comment }


  form.new_feedback:
    class: Application\FormBundle\Form\Type\NewFeedbackType
    arguments: [@captcha_decider]
    tags:
      - { name: form.type, alias: new_feedback }


  form.feedback_attachment:
    class: Application\FormBundle\Form\Type\FeedbackAttachmentType
    arguments: [@blob.storage]
    tags:
      - { name: form.type, alias: feedback_attachment }


  form.feedback_attachment_collection:
    class: Application\FormBundle\Form\Type\FeedbackAttachmentCollectionType
    tags:
      - { name: form.type, alias: feedback_attachment_collection }


  form.feedback_category:
    class: Application\FormBundle\Form\Type\FeedbackCategoryType
    tags:
      - { name: form.type, alias: feedback_category }


  form.request_password_reset:
    class: Application\FormBundle\Form\Type\PasswordResetRequestType
    tags:
      - { name: form.type, alias: request_password_reset }


  form.person_change_password:
    class: Application\FormBundle\Form\Type\PersonChangePasswordType
    tags:
      - { name: form.type, alias: person_change_password }


  form.custom_data_ticket:
    class: Application\FormBundle\Form\Type\CustomDataTicketType
    arguments: [@form_field_manager, @doctrine.orm.default_entity_manager]
    tags:
      - { name: form.type, alias: deskpro_custom_data_ticket }


  form.custom_data_person:
    class: Application\FormBundle\Form\Type\CustomDataPersonType
    arguments: [@form_field_manager]
    tags:
      - { name: form.type, alias: deskpro_custom_data_person }


  form.ticket_message:
    class: Application\FormBundle\Form\Type\TicketMessageType
    tags:
      - { name: form.type, alias: ticket_message }


  form.ticket_message_attachment:
    class: Application\FormBundle\Form\Type\TicketMessageAttachmentType
    arguments: [@blob.storage, @doctrine.orm.default_entity_manager]
    tags:
      - { name: form.type, alias: ticket_message_attachment }


  form.ticket_message_attachment_collection:
    class: Application\FormBundle\Form\Type\TicketMessageAttachmentCollectionType
    tags:
      - { name: form.type, alias: ticket_message_attachment_collection }


  form.custom_field_choice:
    class: Application\FormBundle\Form\Type\CustomFieldChoiceType
    arguments: [@form_hierarchy_generator]
    tags:
      - { name: form.type, alias: deskpro_custom_field_choice }


  form.language:
    class: Application\FormBundle\Form\Type\LanguageType
    tags:
      - { name: form.type, alias: deskpro_language }


  form.person_email:
    class: Application\FormBundle\Form\Type\PersonEmailType
    tags:
      - { name: form.type, alias: deskpro_person_email }


  form.display_html:
    class: Application\FormBundle\Form\Type\DisplayHtmlType
    tags:
      - { name: form.type, alias: deskpro_display_html }


  form.hidden:
    class: Application\FormBundle\Form\Type\HiddenType
    arguments: [@request_stack]
    tags:
      - { name: form.type, alias: deskpro_hidden }


  form.department:
    class: Application\FormBundle\Form\Type\DepartmentType
    tags:
      - { name: form.type, alias: deskpro_department }


  form.product:
    class: Application\FormBundle\Form\Type\ProductType
    tags:
      - { name: form.type, alias: deskpro_product }


  form.category:
    class: Application\FormBundle\Form\Type\CategoryType
    tags:
      - { name: form.type, alias: deskpro_category }


  form.workflow:
    class: Application\FormBundle\Form\Type\WorkflowType
    tags:
      - { name: form.type, alias: deskpro_workflow }


  form.priority:
    class: Application\FormBundle\Form\Type\PriorityType
    tags:
      - { name: form.type, alias: deskpro_priority }


  form.captcha:
    class: Application\FormBundle\Form\Type\CaptchaType
    arguments: [@brand_stack]
    tags:
      - { name: form.type, alias: deskpro_captcha }


  form.blob:
    class: Application\FormBundle\Form\Type\BlobType
    arguments: [@doctrine.orm.default_entity_manager, @blob.storage]
    tags:
      - { name: form.type, alias: deskpro_blob }


  form.cc:
    class: Application\FormBundle\Form\Type\CcType
    arguments: [@person_factory]
    tags:
      - { name: form.type, alias: deskpro_cc }


  form.date:
    class: Application\FormBundle\Form\Type\DateType
    tags:
      - { name: form.type, alias: deskpro_date }


  form.datetime:
    class: Application\FormBundle\Form\Type\DateTimeType
    tags:
      - { name: form.type, alias: deskpro_datetime }


  form.heirarchical_entity:
    class: Application\FormBundle\Form\Type\HeirarchicalEntityType
    tags:
      - { name: form.type, alias: deskpro_heirarchical_entity }


  form.entity_hierarchy:
    class: Application\FormBundle\Form\Type\EntityHeirarchyType
    arguments: [@form_hierarchy_generator]
    tags:
      - { name: form.type, alias: entity_hierarchy }