user:
  pattern:  /
  defaults: { _controller: UserBundle:Main:index }

user_login:
  pattern: /login
  defaults: { _controller: UserBundle:Login:index }

user_logout:
  pattern: /logout
  defaults: { _controller: UserBundle:Login:logout }

user_login_authenticate_local:
  pattern: /login/authenticate-password
  defaults: { _controller: UserBundle:Login:authenticate, usersource_id: 0 }

user_login_authenticate:
  pattern: /login/authenticate/{usersource_id}
  defaults: { _controller: UserBundle:Login:authenticate, usersource_id: 0 }
  requirements: { usersource_id: "\d+" }

user_login_callback:
  pattern: /login/authenticate-callback/{usersource_id}
  defaults: { _controller: UserBundle:Login:authenticateCallback }
  requirements: { usersource_id: "\d+" }


################################################################################
# Register
################################################################################

user_register_finish:
  pattern: /register/finish
  defaults: { _controller: UserBundle:Register:finish }


################################################################################
# Tickets
################################################################################

user_tickets:
  pattern: /tickets
  defaults: { _controller: UserBundle:Tickets:list }

# This must be before _view, so /new isnt considered a ticket with ref 'new'
user_tickets_new:
  pattern: /tickets/new
  defaults: { _controller: UserBundle:NewTicket:new }

user_tickets_new_thanks:
  pattern: /tickets/new/thanks/{ticket_ref}
  defaults: { _controller: UserBundle:NewTicket:thanks }

user_tickets_view:
  pattern: /tickets/{ticket_ref}
  defaults: { _controller: UserBundle:Tickets:view }

user_tickets_view_auth:
  pattern: /tickets/{ticket_ref}/{ticket_auth}
  defaults: { _controller: UserBundle:Tickets:viewWithAuth }

################################################################################
# Articles
################################################################################

user_articles:
  pattern: /articles
  defaults: { _controller: UserBundle:Articles:index }

user_articles_cat:
  pattern: /articles/cat/{category_id}
  defaults: { _controller: UserBundle:Articles:category }

user_articles_article:
  pattern: /articles/view/{article_id}/{slug}
  defaults: { _controller: UserBundle:Articles:article }

user_articles_newcomment:
  pattern: /articles/new-comment/{article_id}
  defaults: { _controller: UserBundle:Articles:newComment }

################################################################################
# Downloads
################################################################################

user_downloads:
  pattern: /downloads
  defaults: { _controller: UserBundle:Downloads:index }

user_downloads_cat:
  pattern: /downloads/folder/{category_id}
  defaults: { _controller: UserBundle:Downloads:category }

user_downloads_file:
  pattern: /downloads/file/{download_id}/{slug}
  defaults: { _controller: UserBundle:Downloads:file }

################################################################################
# News
################################################################################

user_news:
  pattern: /news
  defaults: { _controller: UserBundle:News:index, category_id: 0 }

user_news_cat:
  pattern: /news/category/{category_id}
  defaults: { _controller: UserBundle:News:index }

user_news_view:
  pattern: /news/view/{post_id}
  defaults: { _controller: UserBundle:News:view }

user_news_newcomment:
  pattern: /news/new-comment/{post_id}
  defaults: { _controller: UserBundle:News:newComment }

################################################################################
# Ideas
################################################################################

user_ideas_view:
  pattern: /ideas/view/{idea_id}
  defaults: { _controller: UserBundle:Ideas:view }

user_ideas_newcomment:
  pattern: /ideas/new-comment/{idea_id}
  defaults: { _controller: UserBundle:Ideas:newComment }

user_ideas_vote:
  pattern: /ideas/view/{idea_id}/vote
  defaults: { _controller: UserBundle:Ideas:vote }

user_ideas:
  pattern: /ideas
  defaults: { _controller: UserBundle:Ideas:index, category_id: 0, status: new }

user_ideas_status:
  pattern: /ideas/all/{status}
  defaults: { _controller: UserBundle:Ideas:index, category_id: 0 }

user_ideas_cat:
  pattern: /ideas/{category_id}
  defaults: { _controller: UserBundle:Ideas:index, status: new }

user_ideas_cat_status:
  pattern: /ideas/{category_id}/{status}
  defaults: { _controller: UserBundle:Ideas:index }