user:
  pattern:  /
  defaults: { _controller: UserBundle:Main:index, _locale: en }

################################################################################
# Login/logout
################################################################################

user_login:
  pattern: /login
  defaults: { _controller: UserBundle:Login:index }

user_logout:
  pattern: /logout
  defaults: { _controller: UserBundle:Login:logout }

user_login_authenticate_local:
  pattern: /login/authenticate-password
  defaults: { _controller: UserBundle:Login:authenticate, usersource_id: 0 }

user_login_authenticate:
  pattern: /login/authenticate/{usersource_id}
  defaults: { _controller: UserBundle:Login:authenticate, usersource_id: 0 }
  requirements: { usersource_id: "\d+" }

user_login_callback:
  pattern: /login/authenticate-callback/{usersource_id}
  defaults: { _controller: UserBundle:Login:authenticateCallback }
  requirements: { usersource_id: "\d+" }

################################################################################
# Register
################################################################################

user_register_finish:
  pattern: /register/finish
  defaults: { _controller: UserBundle:Register:finish }

################################################################################
# Profile
################################################################################

user_profile:
  pattern: /profile
  defaults: { _controller: UserBundle:Profile:index }

user_profile_changepassword:
  pattern: /profile/change-password
  defaults: { _controller: UserBundle:Profile:changePassword }

user_profile_emails:
  pattern: /profile/emails
  defaults: { _controller: UserBundle:Profile:emails }

user_profile_emails_new:
  pattern: /profile/emails/new
  defaults: { _controller: UserBundle:Profile:newEmail }

user_profile_emails_remove:
  pattern: /profile/emails/{email_id}/remove
  defaults: { _controller: UserBundle:Profile:removeEmail }

user_profile_emails_validate:
  pattern: /profile/emails/{email_id}/validate
  defaults: { _controller: UserBundle:Profile:validateEmail }

user_profile_emails_validate_sendlink:
  pattern: /profile/emails/{email_id}/validate/send-link
  defaults: { _controller: UserBundle:Profile:sendValidateEmailLink }

user_profile_emails_validate_code:
  pattern: /profile/emails/{email_id}/validate/{code}
  defaults: { _controller: UserBundle:Profile:validateEmail }

user_profile_emails_setdefault:
  pattern: /profile/emails/{email_id}/set-default
  defaults: { _controller: UserBundle:Profile:setDefaultEmail }

################################################################################
# Search
################################################################################

user_search:
  pattern: /search
  defaults: { _controller: UserBundle:Search:search }

user_search_labels:
  pattern: /tagged/{labels}
  defaults: { _controller: UserBundle:Search:labelled }

################################################################################
# Tickets
################################################################################

user_tickets:
  pattern: /tickets
  defaults: { _controller: UserBundle:Tickets:list }

# This must be before _view, so /new isnt considered a ticket with ref 'new'
user_tickets_new:
  pattern: /tickets/new
  defaults: { _controller: UserBundle:NewTicket:new }

user_tickets_new_thanks:
  pattern: /tickets/new/thanks/{ticket_ref}
  defaults: { _controller: UserBundle:NewTicket:thanks }

user_tickets_view:
  pattern: /tickets/{ticket_ref}
  defaults: { _controller: UserBundle:Tickets:view }

user_tickets_view_auth:
  pattern: /tickets/{ticket_ref}/{ticket_auth}
  defaults: { _controller: UserBundle:Tickets:viewWithAuth }

################################################################################
# Articles
################################################################################

user_articles:
  pattern: /kb
  defaults: { _controller: UserBundle:Articles:index }

user_articles_cat:
  pattern: /kb/{slug}
  defaults: { _controller: UserBundle:Articles:category }

user_articles_article:
  pattern: /kb/articles/{slug}
  defaults: { _controller: UserBundle:Articles:article }

user_articles_rate:
  pattern: /kb/rate-article/{article_id}
  defaults: { _controller: UserBundle:Articles:rate }

user_articles_newcomment:
  pattern: /kb/new-comment/{article_id}
  defaults: { _controller: UserBundle:Articles:newComment }

################################################################################
# Downloads
################################################################################

user_downloads:
  pattern: /downloads
  defaults: { _controller: UserBundle:Downloads:index }

user_downloads_file:
  pattern: /downloads/files/{slug}
  defaults: { _controller: UserBundle:Downloads:file }

user_downloads_cat:
  pattern: /downloads/{slug}
  defaults: { _controller: UserBundle:Downloads:category }

################################################################################
# News
################################################################################

user_news:
  pattern: /news
  defaults: { _controller: UserBundle:News:index, slug: 0 }

user_news_view:
  pattern: /news/posts/{slug}
  defaults: { _controller: UserBundle:News:view }

user_news_cat:
  pattern: /news/{slug}
  defaults: { _controller: UserBundle:News:index }

user_news_newcomment:
  pattern: /news/new-comment/{post_id}
  defaults: { _controller: UserBundle:News:newComment }

################################################################################
# Ideas
################################################################################

user_ideas_view:
  pattern: /feedback/ideas/{slug}
  defaults: { _controller: UserBundle:Ideas:view }

user_ideas_newidea:
  pattern: /feedback/new-idea
  defaults: { _controller: UserBundle:Ideas:newIdea }

user_ideas_newcomment:
  pattern: /feedback/new-comment/{idea_id}
  defaults: { _controller: UserBundle:Ideas:newComment }

user_ideas_vote:
  pattern: /feedback/vote/{idea_id}
  defaults: { _controller: UserBundle:Ideas:vote }

user_ideas:
  pattern: /feedback
  defaults: { _controller: UserBundle:Ideas:index, slug: 0, status: new }

user_ideas_status:
  pattern: /feedback/all/{status}
  defaults: { _controller: UserBundle:Ideas:index, slug: 0 }

user_ideas_cat:
  pattern: /feedback/{slug}
  defaults: { _controller: UserBundle:Ideas:index, status: new }

user_ideas_cat_status:
  pattern: /feedback/{slug}/{status}
  defaults: { _controller: UserBundle:Ideas:index }