admin:
  pattern: /
  defaults: { _controller: AdminBundle:Main:index }

admin_test:
  pattern: /test
  defaults: { _controller: AdminBundle:Test:index }

################################################################################
# Labels
################################################################################

admin_labels:
  pattern: /settings/labels
  defaults: { _controller: AdminBundle:Settings:labels }

admin_labels_ajaxnew:
  pattern: /settings/labels/ajax-new
  defaults: { _controller: AdminBundle:Settings:labelsAjaxNew }

admin_labels_ajaxdel:
  pattern: /settings/labels/ajax-delete
  defaults: { _controller: AdminBundle:Settings:labelsAjaxDelete }

################################################################################
# Agents
################################################################################

admin_agents_teams:
  pattern: /agents/teams
  defaults: { _controller: AdminBundle:Agents:teams }

admin_agents_teams_edit:
  pattern: /agents/teams/{team_id}/edit
  defaults: { _controller: AdminBundle:Agents:editTeam }
  requirements: { team_id: "\d+" }

admin_agents_teams_new:
  pattern: /agents/teams/new
  defaults: { _controller: AdminBundle:Agents:editTeam, team_id: 0 }

################################################################################
# Styles
################################################################################

admin_styles:
  pattern: /styles
  defaults: { _controller: AdminBundle:Styles:index }

admin_styles_intro:
  pattern: /styles/intro
  defaults: { _controller: AdminBundle:Styles:intro }

admin_styles_showstyle:
  pattern: /styles/{style_id}
  defaults: { _controller: AdminBundle:Styles:showStyle }
  requirements: { style_id: "\d+" }

admin_styles_editstyle:
  pattern: /styles/{style_id}/edit
  defaults: { _controller: AdminBundle:Styles:editStyle }
  requirements: { style_id: "\d+" }

admin_styles_newstyle:
  pattern: /styles/new-style
  defaults: { _controller: AdminBundle:Styles:editStyle, style_id: 0 }

admin_styles_resources:
  pattern: /styles/{style_id}/resources
  defaults: { _controller: AdminBundle:Styles:styleResourceList }
  requirements: { style_id: "\d+" }

admin_styles_templates:
  pattern: /styles/{style_id}/templates
  defaults: { _controller: AdminBundle:Styles:styleTemplateList }
  requirements: { style_id: "\d+" }

admin_styles_edittemplate:
  pattern: /styles/{style_id}/templates/{template_name}
  defaults: { _controller: AdminBundle:Styles:editTemplate }
  requirements: { style_id: "\d+" }


################################################################################
# Languages
################################################################################

admin_langs:
  pattern: /languages
  defaults: { _controller: AdminBundle:Languages:index }

admin_langs_intro:
  pattern: /languages/intro
  defaults: { _controller: AdminBundle:Languages:intro }

admin_langs_editlang:
  pattern: /languages/{lang_id}/edit
  defaults: { _controller: AdminBundle:Languages:editLang }
  requirements: { lang_id: "\d+" }

admin_langs_newlang:
  pattern: /languages/new-language
  defaults: { _controller: AdminBundle:Languages:editLang, lang_id: 0 }

admin_langs_phrases:
  pattern: /languages/{lang_id}/phrases
  defaults: { _controller: AdminBundle:Languages:listPhrases}
  requirements: { lang_id: "\d+", phrase_group: null }

admin_langs_editphrase:
  pattern: /languages/{lang_id}/edit-phrase/{phrase_name}
  defaults: { _controller: AdminBundle:Languages:editPhrase }
  requirements: { lang_id: "\d+" }


################################################################################
# Usersources
################################################################################

admin_usersources:
  pattern: /usersources
  defaults: { _controller: AdminBundle:Usersources:index }

admin_usersources_intro:
  pattern: /usersources/intro
  defaults: { _controller: AdminBundle:Usersources:intro }

admin_usersources_info:
  pattern: /usersources/{usersource_id}
  defaults: { _controller: AdminBundle:Usersources:info }
  requirements: { usersource_id: "\d+" }

admin_usersources_edit:
  pattern: /usersources/{usersource_id}/edit
  defaults: { _controller: AdminBundle:Usersources:edit }
  requirements: { usersource_id: "\d+" }

admin_usersources_new:
  pattern: /usersources/new-usersource
  defaults: { _controller: AdminBundle:Usersources:edit, usersource_id: 0 }

################################################################################
# API Keys
################################################################################

admin_api_keylist:
  pattern: /api
  defaults: { _controller: AdminBundle:Api:index }

admin_api_delkey:
  pattern: /api/key/{id}/del
  defaults: { _controller: AdminBundle:Api:delKey }
  requirements: { id: "\d+" }

admin_api_editkey:
  pattern: /api/key/{id}/edit
  defaults: { _controller: AdminBundle:Api:editKey }
  requirements: { id: "\d+" }

admin_api_newkey:
  pattern: /api/key/new
  defaults: { _controller: AdminBundle:Api:editKey, id: 0 }


################################################################################
# People Fields
################################################################################

admin_customdefpeople:
  pattern: /people-fields
  defaults: { _controller: AdminBundle:CustomDefPeople:index }

admin_customdefpeople_new_choosetype:
  pattern: /people-fields/new-choose-type
  defaults: { _controller: AdminBundle:CustomDefPeople:newChooseType, field_id: 0 }

admin_customdefpeople_edit:
  pattern: /people-fields/{field_id}/edit
  defaults: { _controller: AdminBundle:CustomDefPeople:edit }
  requirements: { field_id: "\d+" }

admin_customdefpeople_test:
  pattern: /people-fields/{field_id}/test
  defaults: { _controller: AdminBundle:CustomDefPeople:test }
  requirements: { field_id: "\d+" }

################################################################################
# People Fields
################################################################################

admin_customdeftickets:
  pattern: /ticket-fields
  defaults: { _controller: AdminBundle:CustomDefTickets:index }

admin_customdeftickets_new_choosetype:
  pattern: /ticket-fields/new-choose-type
  defaults: { _controller: AdminBundle:CustomDefTickets:newChooseType, field_id: 0 }

admin_customdeftickets_edit:
  pattern: /ticket-fields/{field_id}/edit
  defaults: { _controller: AdminBundle:CustomDefTickets:edit }
  requirements: { field_id: "\d+" }

admin_customdeftickets_test:
  pattern: /ticket-fields/{field_id}/test
  defaults: { _controller: AdminBundle:CustomDefTickets:test }
  requirements: { field_id: "\d+" }

################################################################################
# Twitter
################################################################################

admin_twitter:
  pattern: /twitter
  defaults: { _controller: AdminBundle:Twitter:index }

admin_twitter_newaccount:
  pattern: /twitter/newaccount
  defaults: { _controller: AdminBundle:Twitter:authenticate}

admin_twitter_addaccount:
  pattern: /twitter/addaccount
  defaults: { _controller: AdminBundle:Twitter:addaccount}