// Generated by CoffeeScript 1.6.3
(function() {
  define(['Admin/Main/Util/EventsMixin'], function(EventsMixin) {
    /**
    	* Save an ordered k=>v
    */

    var Admin_Main_Collection_OrderedDictionary;
    return Admin_Main_Collection_OrderedDictionary = (function() {
      function Admin_Main_Collection_OrderedDictionary() {
        EventsMixin(this);
        this._touch = (new Date()).getTime();
        this.scope = null;
        this.data = {};
        this.order = [];
      }

      Admin_Main_Collection_OrderedDictionary.prototype.count = function() {
        return this.order.length;
      };

      Admin_Main_Collection_OrderedDictionary.prototype.set = function(k, v) {
        var exist_pos;
        this._touch = (new Date()).getTime();
        this.data[k] = v;
        exist_pos = this.order.indexOf(k);
        if (exist_pos !== -1) {
          this.order.splice(exist_pos, 1);
        }
        this.order.push(k);
        this.notifyListeners('changed');
        return v;
      };

      Admin_Main_Collection_OrderedDictionary.prototype.get = function(k, default_val) {
        if (default_val == null) {
          default_val = null;
        }
        if (this.data[k] == null) {
          return default_val;
        }
        return this.data[k];
      };

      Admin_Main_Collection_OrderedDictionary.prototype.remove = function(k) {
        var exist_pos;
        this._touch = (new Date()).getTime();
        if (this.data[k] != null) {
          delete this.data[k];
          exist_pos = this.order.indexOf(k);
          this.order.splice(exist_pos, 1);
        }
        this.notifyListeners('changed');
        return null;
      };

      Admin_Main_Collection_OrderedDictionary.prototype.has = function(k) {
        return !(this.data[k] == null);
      };

      Admin_Main_Collection_OrderedDictionary.prototype.forEach = function(fn) {
        var key, ret, val, _i, _len, _ref, _results;
        _ref = this.order;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          key = _ref[_i];
          val = this.data[key];
          ret = fn(key, val);
          if (ret === false) {
            break;
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      };

      Admin_Main_Collection_OrderedDictionary.prototype.getOrderedPair = function() {
        var key, ret, val, _i, _len, _ref;
        ret = [];
        _ref = this.order;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          key = _ref[_i];
          val = this.data[key];
          ret.push([key, val]);
        }
        return ret;
      };

      Admin_Main_Collection_OrderedDictionary.prototype.keys = function() {
        return this.order;
      };

      Admin_Main_Collection_OrderedDictionary.prototype.values = function() {
        var key, ret, val, _i, _len, _ref;
        ret = [];
        _ref = this.order;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          key = _ref[_i];
          val = this.data[key];
          ret.push(val);
        }
        return ret;
      };

      return Admin_Main_Collection_OrderedDictionary;

    })();
  });

}).call(this);

/*
//@ sourceMappingURL=OrderedDictionary.map
*/
