// Generated by CoffeeScript 1.6.3
(function() {
  define(function() {
    var AppState;
    return AppState = (function() {
      function AppState($rootScope) {
        var _this = this;
        this.$rootScope = $rootScope;
        this.vars = {};
        this.activeState = null;
        this.activeStateApp = null;
        this.activeStateNav = null;
        this.activeStateList = null;
        this.sectionState = null;
        this.$rootScope.$on('$stateChangeSuccess', function(event, toState, toParams, fromState, fromParams) {
          return _this.setActiveState(toState.name);
        });
      }

      AppState.prototype.setActiveState = function(activeState) {
        var bits;
        this.activeState = activeState;
        bits = this.activeState.split('.');
        this.activeStateApp = bits.shift();
        this.activeStateNav = bits.shift();
        this.activeStateList = bits.shift();
        return this.$rootScope.$broadcast('dp_activeStateChange', this.activeState, this.activeStateApp, this.activeStateNav, this.activeStateList);
      };

      return AppState;

    })();
  });

}).call(this);

/*
//@ sourceMappingURL=AppState.map
*/
