// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty;

  define(['angular'], function(angular) {
    var DpApi;
    return DpApi = (function() {
      function DpApi($http, api_url, api_token) {
        this.$http = $http;
        this.api_token = api_token;
        this.api_url = api_url.replace(/\/$/, '');
      }

      /**
      		* Format an endpoint with GET params to a full URL string.
        	*
        	* @param {String} endpoint
        	* @param {Object/Array} Params to send in the query string
        	* @return {String}
      */


      DpApi.prototype.formatUrl = function(endpoint, params) {
        var itm, k, url, v, _i, _len;
        if (params == null) {
          params = null;
        }
        endpoint = endpoint.replace(/^\//, '');
        url = "" + this.api_url + "/" + endpoint;
        if (params) {
          if (url.indexOf('?') === -1) {
            url += '?';
          } else {
            url += '&';
          }
          if (angular.isArray(params)) {
            for (_i = 0, _len = params.length; _i < _len; _i++) {
              itm = params[_i];
              k = encodeURIComponent(itm.name);
              v = encodeURIComponent(itm.value);
              url += "" + k + "=" + v + "&";
            }
          } else {
            for (k in params) {
              v = params[k];
              k = encodeURIComponent(k);
              v = encodeURIComponent(v);
              url += "" + k + "=" + v + "&";
            }
          }
          url = url.replace(/&$/, '');
        }
        return url;
      };

      /**
      		* Uses the api-caller endpoint to fetch multiple data points at once.
        	*
        	* @return {Promise}
      */


      DpApi.prototype.sendDataGet = function(paths, http_params) {
        var params, path, _i, _len;
        if (http_params == null) {
          http_params = {};
        }
        params = [];
        for (_i = 0, _len = paths.length; _i < _len; _i++) {
          path = paths[_i];
          params.push({
            name: 'load_data[]',
            value: this.formatUrl(path)
          });
        }
        return this.sendGet('api_caller', params, http_params);
      };

      /**
      		* Format an endpoint with GET params to a full URL string.
        	*
        	* @param {String} endpoint
        	* @param {Object/Array} Params to send in the query string
        	* @return {String}
      */


      DpApi.prototype.prepareHttpParams = function(http_params) {
        var headers;
        if (http_params == null) {
          http_params = {};
        }
        headers = http_params.headers || {};
        headers["X-DeskPRO-API-Token"] = this.api_token;
        if (http_params.cache == null) {
          http_params.cache = false;
        }
        http_params.headers = headers;
        return http_params;
      };

      /*
        	* Sends a GET request
        	*
        	* @param {String} endpoint
        	* @param {Object/Array} params to send in th query string
        	* @return {Promise}
      */


      DpApi.prototype.sendGet = function(endpoint, params, http_params) {
        var url;
        if (params == null) {
          params = null;
        }
        if (http_params == null) {
          http_params = {};
        }
        url = this.formatUrl(endpoint, params);
        http_params.method = 'GET';
        http_params.url = url;
        this.prepareHttpParams(http_params);
        return this.$http(http_params);
      };

      /*
        	* Sends a POST request
        	*
        	* @param {String} endpoint
        	* @param {Object/Array} post_data Params to send as the POST data
        	* @param {Object/Array} params to send in th query string
        	* @param {Object} http_params Params that will be written to
        	* @return {Promise}
      */


      DpApi.prototype.sendPost = function(endpoint, post_data, params, http_params) {
        var data_str, itm, k, url, v, _i, _len;
        if (post_data == null) {
          post_data = null;
        }
        if (params == null) {
          params = null;
        }
        if (http_params == null) {
          http_params = {};
        }
        url = this.formatUrl(endpoint, params);
        data_str = '';
        if (post_data) {
          if (angular.isArray(post_data)) {
            for (_i = 0, _len = post_data.length; _i < _len; _i++) {
              itm = post_data[_i];
              k = encodeURIComponent(itm.name);
              v = encodeURIComponent(itm.value);
              data_str += "" + k + "=" + v + "&";
            }
          } else {
            for (k in post_data) {
              if (!__hasProp.call(post_data, k)) continue;
              v = post_data[k];
              k = encodeURIComponent(k);
              v = encodeURIComponent(v);
              data_str += "" + k + "=" + v + "&";
            }
          }
          data_str = data_str.replace(/&$/, '');
        }
        http_params.method = 'POST';
        http_params.url = url;
        http_params.data = data_str;
        this.prepareHttpParams(http_params);
        return this.$http(http_params);
      };

      /*
        	* Sends a POST request with a JSON payload
        	*
        	* @param {String} endpoint
        	* @param {Object/Array} post_data Params to send as the POST data
        	* @param {Object/Array} params to send in th query string
        	* @param {Object} http_params Params that will be written to
        	* @return {Promise}
      */


      DpApi.prototype.sendPostJson = function(endpoint, post_data, params, http_params) {
        var url;
        if (post_data == null) {
          post_data = null;
        }
        if (params == null) {
          params = null;
        }
        if (http_params == null) {
          http_params = {};
        }
        url = this.formatUrl(endpoint, params);
        http_params.method = 'POST';
        http_params.url = url;
        http_params.data = post_data;
        this.prepareHttpParams(http_params);
        return this.$http(http_params);
      };

      /*
        	* Sends a PUT request
        	*
        	* @param {String} endpoint
        	* @param {Object/Array} post_data Params to send as the POST data
        	* @param {Object/Array} params to send in th query string
        	* @param {Object} http_params Params that will be written to
        	* @return {Promise}
      */


      DpApi.prototype.sendPut = function(endpoint, post_data, params, http_params) {
        var data_str, itm, k, url, v, _i, _len;
        if (post_data == null) {
          post_data = null;
        }
        if (params == null) {
          params = null;
        }
        if (http_params == null) {
          http_params = {};
        }
        url = this.formatUrl(endpoint, params);
        data_str = '';
        if (post_data) {
          if (angular.isArray(params)) {
            for (_i = 0, _len = params.length; _i < _len; _i++) {
              itm = params[_i];
              k = encodeURIComponent(itm.name);
              v = encodeURIComponent(itm.value);
              data_str += "" + k + "=" + v + "&";
            }
          } else {
            for (k in params) {
              v = params[k];
              k = encodeURIComponent(k);
              v = encodeURIComponent(v);
              data_str += "" + k + "=" + v + "&";
            }
          }
          data_str = data_str.replace(/&$/, '');
        }
        http_params.method = 'PUT';
        http_params.url = url;
        if (post_data) {
          http_params.data = data_str;
        }
        this.prepareHttpParams(http_params);
        return this.$http(http_params);
      };

      /*
        	* Sends a DELETE request
        	*
        	* @param {String} endpoint
        	* @param {Object/Array} params to send in th query string
        	* @return {Promise}
      */


      DpApi.prototype.sendDelete = function(endpoint, params, http_params) {
        var url;
        if (params == null) {
          params = null;
        }
        if (http_params == null) {
          http_params = {};
        }
        url = this.formatUrl(endpoint, params);
        http_params.method = 'DELETE';
        http_params.url = url;
        this.prepareHttpParams(http_params);
        return this.$http(http_params);
      };

      return DpApi;

    })();
  });

}).call(this);

/*
//@ sourceMappingURL=DpApi.map
*/
