// Generated by CoffeeScript 1.6.3
(function() {
  var __slice = [].slice;

  define(['angular', 'Admin/App'], function(angular) {
    /**
    	* The base controller class is mainly to make it easier to define controllers with angular.
       *
       * At the bottom of controller files, the controllers register themselves by calling
       * the class method EXPORT_CTRL().
       *
       * EXPORT_CTRL() is pre-configured to install the controller into the Admin_App module
       * with the defined dependencies (as well as AppState and $scope which are always defined).
       *
       * Note that controllers typically *register themselves* with EXPORT_CTRL(). This is converse to
       * all other types of objects (services and directives etc) which are registered through the App
       * loader.
    */

    var Admin_Ctrl_Base;
    return Admin_Ctrl_Base = (function() {
      Admin_Ctrl_Base.CTRL_AS = null;

      Admin_Ctrl_Base.CTRL_ID = 'Admin_Main_Ctrl_Base';

      Admin_Ctrl_Base.CTRL_TYPE = null;

      Admin_Ctrl_Base.DEPS = [];

      /**
      		* Exports this controller to the Admin_App angular module
        	* so it can be used.
      */


      Admin_Ctrl_Base.EXPORT_CTRL = function() {
        var ctrl_def;
        if (this.DEPS.indexOf('AppState') === -1) {
          this.DEPS.push('AppState');
        }
        if (this.DEPS.indexOf('Api') === -1) {
          this.DEPS.push('Api');
        }
        if (this.DEPS.indexOf('$scope') === -1) {
          this.DEPS.push('$scope');
        }
        if (this.DEPS.indexOf('$modal') === -1) {
          this.DEPS.push('$modal');
        }
        if (this.DEPS.indexOf('$q') === -1) {
          this.DEPS.push('$q');
        }
        ctrl_def = this.DEPS.slice(0);
        ctrl_def.push(this);
        angular.module('Admin_App').controller(this.CTRL_ID, ctrl_def);
        return this;
      };

      /**
      		* The constructor will assign all passed-in dependencies to class vars
      */


      function Admin_Ctrl_Base() {
        var arg, arg_name, args, i, me, ret, _i, _j, _len, _len1,
          _this = this;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        if (this.constructor.DEPS.length !== args.length) {
          console.error("Dependencies are not the same as passed args: %o != %o", this.constructor.DEPS, args);
          return;
        }
        for (i = _i = 0, _len = args.length; _i < _len; i = ++_i) {
          arg = args[i];
          arg_name = this.constructor.DEPS[i];
          this[arg_name] = arg;
        }
        me = this;
        for (i = _j = 0, _len1 = args.length; _j < _len1; i = ++_j) {
          arg = args[i];
          if (arg._is_ds_class != null) {
            arg.registerCtrl(this);
            this.$scope.$on('$destroy', function() {});
          }
        }
        if (this.constructor.CTRL_AS) {
          this.$scope[this.constructor.CTRL_AS] = this;
        }
        this._managed_listeners = [];
        this.$scope.$on('$destroy', function(ev) {
          var info, _k, _len2, _ref;
          return;
          if (ev.targetScope.$id !== _this.$scope.$id) {
            return;
          }
          if (!_this._managed_listeners.length) {
            return;
          }
          _ref = _this._managed_listeners;
          for (_k = 0, _len2 = _ref.length; _k < _len2; _k++) {
            info = _ref[_k];
            info.object.removeListener(info.event_name, info.fn);
          }
          return _this._managed_listeners = null;
        });
        this.$scope.$on('$stateChangeStart', function(ev, toState, toParams, fromState, fromParams) {
          if (ev.defaultPrevented) {
            return;
          }
          if (!_this._state_cont_go && _this.checkDirtyState()) {
            _this.AppState.setLoadingState('dp_section_page', false);
            ev.preventDefault();
            _this._state_cont_state = toState.name;
            _this._state_cont_state_params = toParams;
            return _this._showStateConfirmLeave();
          }
        });
        this.has_init = false;
        this.init();
        this.has_init = true;
        ret = this.initialLoad();
        if (ret) {
          ret.then(function() {
            return _this.disableViewLoadingState();
          });
        } else {
          this.disableViewLoadingState();
        }
      }

      /**
      		* A controller may override this method.
      		*
      		* Return true if the current state is dirty (unsaved). The user
      		* will be asked to confirm leaving.
      		*
      		* @return {Boolean}
      */


      Admin_Ctrl_Base.prototype.checkDirtyState = function() {
        return false;
      };

      /**
        	* Set dirty state checking feature on this tab. Disabled
         	* means no dirty state checking is performed when the user
        	* tries to leave.
        	*
        	* @param {Boolean} turn_off True (default) to turn off. Pass false to turn it back on
      */


      Admin_Ctrl_Base.prototype.skipDirtyState = function(turn_off) {
        if (turn_off == null) {
          turn_off = true;
        }
        return this._state_cont_go = turn_off;
      };

      /**
      		* Show this page as "loading"
      */


      Admin_Ctrl_Base.prototype.enableViewLoadingState = function() {
        if (!this.constructor.CTRL_TYPE === 'any') {
          this.AppState.setLoadingState('dp_section_list', true);
          return this.AppState.setLoadingState('dp_section_page', true);
        } else if (this.constructor.CTRL_TYPE === 'list') {
          return this.AppState.setLoadingState('dp_section_list', true);
        } else if (this.constructor.CTRL_TYPE === 'page') {
          return this.AppState.setLoadingState('dp_section_page', true);
        }
      };

      /**
      		* Stop the loading indicator in this pane
      */


      Admin_Ctrl_Base.prototype.disableViewLoadingState = function() {
        if (!this.constructor.CTRL_TYPE === 'any') {
          this.AppState.setLoadingState('dp_section_list', false);
          return this.AppState.setLoadingState('dp_section_page', false);
        } else if (this.constructor.CTRL_TYPE === 'list') {
          return this.AppState.setLoadingState('dp_section_list', false);
        } else if (this.constructor.CTRL_TYPE === 'page') {
          return this.AppState.setLoadingState('dp_section_page', false);
        }
      };

      /**
      		* Controllers can implement this init() method to add custom init functionality.
      */


      Admin_Ctrl_Base.prototype.init = function() {};

      /**
      		* Controllers can implement this initialLoad() method to load the data needed for a view
      */


      Admin_Ctrl_Base.prototype.initialLoad = function() {};

      /**
      		* Calls $apply on scope only if digest isn't already being processed
      */


      Admin_Ctrl_Base.prototype.ngApply = function(fn) {
        var e,
          _this = this;
        if (!this.$scope.$$phase && !this.$scope.$root.$$phase) {
          try {
            return this.$scope.$apply(fn);
          } catch (_error) {
            e = _error;
            return window.setTimeout(function() {
              try {
                return _this.ngApply();
              } catch (_error) {
                e = _error;
              }
            }, 100);
          }
        }
      };

      /**
      		* Configures an object for auto-release when this controller is destroyed
      		*
      		* @param {Admin_Main_Model_Base} obj
      */


      Admin_Ctrl_Base.prototype._configureAutoReleaseObject = function(obj) {
        var _this = this;
        if (this._autoReleaseObjects == null) {
          this._autoReleaseObjects = [];
          this.$scope.$on('$destroy', function() {
            var i, _i, _len, _ref, _results;
            _ref = _this._autoReleaseObjects;
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              i = _ref[_i];
              _results.push(i.release());
            }
            return _results;
          });
        }
        return this._autoReleaseObjects.push(obj);
      };

      /**
      		* Attaches a listener to an object that will be automatically removed
        	* when this controller is destroyed.
      		*
      		* @param {Admin_Main_Model_Base} obj
      */


      Admin_Ctrl_Base.prototype.addManagedListener = function(object, event_name, fn) {
        this._managed_listeners.push({
          object: object,
          event_name: event_name,
          fn: fn
        });
        return object.addListener(event_name, fn);
      };

      /**
      		* Get the URL to the template
      		*
      		* @return {String}
      */


      Admin_Ctrl_Base.prototype.getTemplatePath = function(path) {
        return DP_BASE_ADMIN_URL + '/load-view/' + path;
      };

      /**
      		* Show an alert
      */


      Admin_Ctrl_Base.prototype._showStateConfirmLeave = function() {
        var inst, parentCtrl;
        parentCtrl = this;
        inst = this.$modal.open({
          templateUrl: this.getTemplatePath('Index/modal-confirm-leavetab.html'),
          controller: [
            '$scope', '$modalInstance', '$state', function($scope, $modalInstance, $state) {
              $scope.dismiss = function() {
                return $modalInstance.dismiss();
              };
              return $scope["continue"] = function() {
                parentCtrl._state_cont_go = true;
                $modalInstance.dismiss();
                return $state.go(parentCtrl._state_cont_state, parentCtrl._state_cont_state_params);
              };
            }
          ]
        });
        return inst;
      };

      /**
      		* Show an alert
      		*
        	* @param {String} message The message to show
        	* @param {String} title   The title to show
      		* @return {Object}
      */


      Admin_Ctrl_Base.prototype.showAlert = function(message, title) {
        var inst;
        if (title == null) {
          title = 'Alert';
        }
        inst = this.$modal.open({
          templateUrl: this.getTemplatePath('Index/modal-alert.html'),
          controller: [
            '$scope', '$modalInstance', function($scope, $modalInstance) {
              $scope.title = title;
              $scope.message = message;
              return $scope.dismiss = function() {
                return $modalInstance.dismiss();
              };
            }
          ]
        });
        return inst;
      };

      return Admin_Ctrl_Base;

    })();
  });

}).call(this);

/*
//@ sourceMappingURL=Base.map
*/
