// Generated by CoffeeScript 1.6.3
(function() {
  var __slice = [].slice;

  define(['angular', 'Admin/App'], function(angular) {
    var Admin_Ctrl_Base;
    return Admin_Ctrl_Base = (function() {
      Admin_Ctrl_Base.CTRL_ID = 'Admin_Main_Ctrl_Base';

      Admin_Ctrl_Base.MODULE_ID = 'Admin_App';

      Admin_Ctrl_Base.DEPS = [];

      Admin_Ctrl_Base.EXPORT_CTRL = function() {
        var ctrl_def;
        if (this.DEPS.indexOf('AppState') === -1) {
          this.DEPS.push('AppState');
        }
        if (this.DEPS.indexOf('$scope') === -1) {
          this.DEPS.push('$scope');
        }
        ctrl_def = this.DEPS.slice(0);
        ctrl_def.push(this);
        return angular.module(this.MODULE_ID).controller(this.CTRL_ID, ctrl_def);
      };

      function Admin_Ctrl_Base() {
        var arg, arg_name, args, i, _i, _len;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        if (this.constructor.DEPS.length !== args.length) {
          console.error("Dependencies are not the same as passed args: %o != %o", this.constructor.DEPS, args);
          return;
        }
        for (i = _i = 0, _len = args.length; _i < _len; i = ++_i) {
          arg = args[i];
          arg_name = this.constructor.DEPS[i];
          this[arg_name] = arg;
        }
        this.has_init = false;
        this.baseTypeInit();
        this.init();
        this.has_init = true;
      }

      Admin_Ctrl_Base.prototype.baseTypeInit = function() {};

      Admin_Ctrl_Base.prototype.init = function() {};

      return Admin_Ctrl_Base;

    })();
  });

}).call(this);
