services:
  deskpro.import.config:
    class: Application\ImportBundle\Generator\GeneratorConfig

  deskpro.import.generator:
    class: Application\ImportBundle\Generator\Generator
    arguments:
      - @=service('deskpro.import.config').getExporterFactory(service('service_container')).createExporter(service('deskpro.import.config').getReaderConfig())
      - @=service('deskpro.import.config').getWriterFactory(service('service_container')).createWriter()
      - @validator
      - @deskpro.import.config

  deskpro.import.batch_exporter:
    class: Application\ImportBundle\Generator\Exporter\Batch
    factory_class: Application\ImportBundle\Generator\Exporter\BatchFactory
    factory_method: createExporter
