<?php

namespace Application\DeskPRO\EntityRepository;

use Application\DeskPRO\Entity\Article as ArticleEntity;
use Application\DeskPRO\Entity\News as NewsEntity;
use Application\DeskPRO\Entity\Download as DownloadEntity;

/**
 * RelatedContent
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelatedContent extends AbstractEntityRepository
{
    public function findRelatedArticles(ArticleEntity $article)
    {
       return $this->findBy(array(
            'object_type' => 'articles',
            'rel_object_type' => 'articles',
            'object_id' => $article->getId()
        ));
    }

    public function findRelatedNewsPosts(NewsEntity $post)
    {
       return $this->findBy(array(
            'object_type' => 'news',
            'rel_object_type' => 'news',
            'object_id' => $post->getId()
        ));
    }

    public function findRelatedFiles(DownloadEntity $download)
    {
       return $this->findBy(array(
            'object_type' => 'downloads',
            'rel_object_type' => 'downloads',
            'object_id' => $download->getId()
        ));
    }
}
