<?php

/*
 * DeskPRO (r) has been developed by DeskPRO Ltd. https://www.deskpro.com/
 * a British company located in London, England.
 *
 * All source code and content Copyright (c) 2015, DeskPRO Ltd.
 *
 * The license agreement under which this software is released
 * can be found at https://www.deskpro.com/eula/
 *
 * By using this software, you acknowledge having read the license
 * and agree to be bound thereby.
 *
 * Please note that DeskPRO is not free software. We release the full
 * source code for our software because we trust our users to pay us for
 * the huge investment in time and energy that has gone into both creating
 * this software and supporting our customers. By providing the source code
 * we preserve our customers' ability to modify, audit and learn from our
 * work. We have been developing DeskPRO since 2001, please help us make it
 * another decade.
 *
 * Like the work you see? Think you could make it better? We are always
 * looking for great developers to join us: http://www.deskpro.com/jobs/
 *
 * ~ Thanks, Everyone at Team DeskPRO
 */

namespace Application\DeskPRO\EntityRepository;

use Application\DeskPRO\Entity\Article as ArticleEntity;
use Application\DeskPRO\Entity\Download as DownloadEntity;
use Application\DeskPRO\Entity\News as NewsEntity;

/**
 * RelatedContent.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelatedContent extends AbstractEntityRepository
{
    public function findRelatedArticles(ArticleEntity $article)
    {
        return $this->findBy(array(
            'object_type'     => 'articles',
            'rel_object_type' => 'articles',
            'object_id'       => $article->getId(),
        ));
    }

    public function findRelatedNewsPosts(NewsEntity $post)
    {
        return $this->findBy(array(
            'object_type'     => 'news',
            'rel_object_type' => 'news',
            'object_id'       => $post->getId(),
        ));
    }

    public function findRelatedFiles(DownloadEntity $download)
    {
        return $this->findBy(array(
            'object_type'     => 'downloads',
            'rel_object_type' => 'downloads',
            'object_id'       => $download->getId(),
        ));
    }
}
