<?php

namespace Application\DeskPRO\EntityRepository;

use Application\DeskPRO\Entity\Article as ArticleEntity;

/**
 * RelatedContent
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelatedContent extends AbstractEntityRepository
{
    public function findRelatedArticles(ArticleEntity $article)
    {
       return $this->findBy(array(
            'object_type' => 'articles',
            'rel_object_type' => 'articles',
            'object_id' => $article->getId()
        ));
    }
}
