// Generated by CoffeeScript 1.6.3
(function() {
  define(function() {
    var Admin_Main_Directive_ActiveStateMark;
    return Admin_Main_Directive_ActiveStateMark = (function() {
      function Admin_Main_Directive_ActiveStateMark() {}

      Admin_Main_Directive_ActiveStateMark.prototype.construct = function() {
        return this.restrict = 'A';
      };

      Admin_Main_Directive_ActiveStateMark.prototype.link = function(scope, element, attrs) {
        return scope.$on('dp_activeStateChange', function(ev, newStateId) {
          var stateId, stateIdRegex;
          stateId = attrs.dpStateMark;
          if (!stateId) {
            return;
          }
          stateIdRegex = '^';
          stateIdRegex += stateId.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&");
          stateIdRegex += '\\b';
          if (newStateId.match(new RegExp(stateIdRegex))) {
            return element.addClass('state-on');
          } else {
            return element.removeClass('state-on');
          }
        }, true);
      };

      return Admin_Main_Directive_ActiveStateMark;

    })();
  });

}).call(this);

/*
//@ sourceMappingURL=ActiveStateMark.map
*/
