// Generated by CoffeeScript 1.6.3
(function() {
  define(function() {
    return [
      function() {
        return {
          restrict: 'A',
          link: function(scope, element, attrs) {
            return scope.$on('dp_activeStateChange', function(ev, newStateId) {
              var stateId;
              stateId = attrs.dpStateMark;
              if (!stateId) {
                return;
              }
              if (newStateId.indexOf(stateId) === 0) {
                return element.addClass('state-on');
              } else {
                return element.removeClass('state-on');
              }
            }, true);
          }
        };
      }
    ];
  });

}).call(this);
