// Generated by CoffeeScript 1.6.3
(function() {
  define(['angular', 'Admin/App'], function(angular, Admin_App) {
    Admin_App.directive('dpSection', function() {
      var def;
      def = {};
      def.restrict = 'E';
      def.transclude = true;
      def.replace = true;
      def.template = '<div class="dp-section"></div>';
      def.compile = function(element, attr, linker) {
        return function(scope, iElement, iAttrs, controller) {
          var div;
          div = iElement;
          linker(scope, function(clone) {
            var hasList;
            hasList = !!clone.filter('.dp-section-list')[0];
            if (hasList) {
              clone.filter('.dp-section-page').addClass('with-list');
            }
            return div.append(clone);
          });
          return div;
        };
      };
      return def;
    });
    Admin_App.directive('dpSectionNav', function() {
      var def;
      def = {};
      def.restrict = 'E';
      def.replace = true;
      def.transclude = true;
      def.template = '<nav class="dp-section-nav sections-nav" ng-transclude></nav>';
      return def;
    });
    Admin_App.directive('dpSectionList', function() {
      var def;
      def = {};
      def.restrict = 'E';
      def.replace = true;
      def.transclude = true;
      def.template = '<div class="dp-section-list" ng-transclude></div>';
      return def;
    });
    Admin_App.directive('dpSectionContent', function() {
      var def;
      def = {};
      def.restrict = 'E';
      def.replace = true;
      def.transclude = true;
      def.template = '<div class="dp-section-page" ng-transclude></div>';
      return def;
    });
    return Admin_App;
  });

}).call(this);
