// Generated by CoffeeScript 1.6.3
(function() {
  define(['jquery'], function(jQuery) {
    var Admin_Main_Directive_ToggleSwitch;
    return Admin_Main_Directive_ToggleSwitch = (function() {
      function Admin_Main_Directive_ToggleSwitch() {}

      Admin_Main_Directive_ToggleSwitch.prototype.construct = function() {
        this.restrict = 'A';
        this.template = '<div ng-transclude></div>';
        this.replace = true;
        this.transclude = true;
        this['require'] = 'ng-model';
      };

      Admin_Main_Directive_ToggleSwitch.prototype.link = function(scope, element, attrs, ngModel) {
        var $check, $wrap;
        $check = jQuery(element);
        $wrap = $check.parent();
        $wrap.addClass('make-switch').bootstrapSwitch();
        ngModel.$render = function() {
          var val;
          val = ngModel.$viewValue;
          if (val) {
            return $check.bootstrapSwitch('active', true);
          } else {
            return $check.bootstrapSwitch('active', false);
          }
        };
        return ngModel.$render();
      };

      return Admin_Main_Directive_ToggleSwitch;

    })();
  });

}).call(this);

/*
//@ sourceMappingURL=ToggleSwitch.map
*/
