agent_dashboard:
  pattern: /
  defaults: { _controller: AgentBundle:Main:index }

agent_test:
  pattern: /test
  defaults: { _controller: AgentBundle:Test:index }

agent_interface_poller:
  pattern: /poller
  defaults: { _controller: AgentBundle:Poller:handler }

agent_accept_upload:
  pattern: /misc/accept-upload
  defaults: { _controller: AgentBundle:Misc:acceptTempUpload }

agent_show_blob:
  pattern: /misc/show-blob/:blob_id
  defaults: { _controller: AgentBundle:Misc:showBlob }

agent_ajax_save_prefs:
  pattern: /misc/ajax-save-prefs
  defaults: { _controller: AgentBundle:Misc:ajaxSavePrefs }

################################################################################
# People
################################################################################

agent_people:
  pattern: /people
  defaults: { _controller: AgentBundle:PeopleSearch:index }

agent_people_view:
  pattern: /people/:person_id
  defaults: { _controller: AgentBundle:Person:view }
  requirements: { person_id: "\d+" }

agent_people_new:
  pattern: /people/new-person
  defaults: { _controller: AgentBundle:Person:view, person_id: 0 }

agent_people_ajaxsave:
  pattern: /people/:person_id/ajax-save
  defaults: { _controller: AgentBundle:Person:ajaxSave }
  requirements: { person_id: "\d+" }

agent_people_ajaxsave_emails:
  pattern: /people/:person_id/ajax-save-emails
  defaults: { _controller: AgentBundle:Person:ajaxSaveEmails }
  requirements: { person_id: "\d+" }

agent_people_ajaxsave_contact:
  pattern: /people/:person_id/ajax-save-contact
  defaults: { _controller: AgentBundle:Person:ajaxSaveContact }
  requirements: { person_id: "\d+" }

agent_people_ajaxsave_note:
  pattern: /people/:person_id/ajax-save-note
  defaults: { _controller: AgentBundle:Person:ajaxSaveNote }
  requirements: { person_id: "\d+" }

agent_people_ajaxsave_organization:
  pattern: /people/:person_id/ajax-save-organization
  defaults: { _controller: AgentBundle:Person:ajaxSaveOrganization }
  requirements: { person_id: "\d+" }

agent_people_ajaxget_notes:
  pattern: /people/:person_id/ajax-get-notes
  defaults: { _controller: AgentBundle:Person:ajaxGetNotes }
  requirements: { person_id: "\d+" }

agent_peoplesearch_perform:
  pattern: /people-search/search
  defaults: { _controller: AgentBundle:PeopleSearch:performSearch }

agent_peoplesearch_performquick:
  pattern: /people-search/search-quick
  defaults: { _controller: AgentBundle:PeopleSearch:performQuickSearch }

agent_peoplesearch:
  pattern: /people-search
  defaults: { _controller: AgentBundle:PeopleSearch:search }

agent_peoplesearch_labelspane:
  pattern: /people-search/filters-pane
  defaults: { _controller: AgentBundle:PeopleSearch:labelsPane }

agent_peoplesearch_directorypane:
  pattern: /people-search/directory-pane
  defaults: { _controller: AgentBundle:PeopleSearch:directoryPane }


################################################################################
# Ticket Search
################################################################################

agent_ticketsearch:
  pattern: /ticket-search
  defaults: { _controller: AgentBundle:TicketSearch:index }

agent_ticketsearch_filterspane:
  pattern: /ticket-search/filters-pane
  defaults: { _controller: AgentBundle:TicketSearch:filtersPane }

agent_ticketsearch_flaggedpane:
  pattern: /ticket-search/flagged-pane
  defaults: { _controller: AgentBundle:TicketSearch:flaggedPane }

agent_ticketsearch_runfilter:
  pattern: /ticket-search/filter/:filter_id
  defaults: { _controller: AgentBundle:TicketSearch:runFilter }
  requirements: { filter_id: "\d+" }

agent_ticketsearch_runflag:
  pattern: /ticket-search/flag/:flag
  defaults: { _controller: AgentBundle:TicketSearch:runFlagged }

agent_ticketqueues_list:
  pattern: /ticket-search/queues/list
  defaults: { _controller: AgentBundle:TicketSearch:listQueues }

agent_ticketqueues_edit:
  pattern: /ticket-search/queues/:queue_id/edit
  defaults: { _controller: AgentBundle:TicketSearch:editQueue }
  requirements: { queue_id: "\d+" }

agent_ticketqueues_new:
  pattern: /ticket-search/queues/new-queue
  defaults: { _controller: AgentBundle:TicketSearch:editQueue, queue_id: 0 }


################################################################################
# Ticket
################################################################################

agent_ticket_view:
  pattern: /tickets/:ticket_id
  defaults: { _controller: AgentBundle:Ticket:view }
  requirements: { ticket_id: "\d+" }

agent_ticket_ajaxsavecustomfields:
  pattern: /tickets/:ticket_id/ajax-save-custom-fields
  defaults: { _controller: AgentBundle:Ticket:ajaxSaveCustomFields }
  requirements: { ticket_id: "\d+" }

agent_ticket_ajaxsavereply:
  pattern: /tickets/:ticket_id/ajax-save-reply
  defaults: { _controller: AgentBundle:Ticket:ajaxSaveReply }
  requirements: { ticket_id: "\d+" }

agent_ticket_ajaxsaveoptions:
  pattern: /tickets/:ticket_id/ajax-save-options
  defaults: { _controller: AgentBundle:Ticket:ajaxSaveOptions }
  requirements: { ticket_id: "\d+" }

agent_ticket_ajaxsaveflagged:
  pattern: /tickets/:ticket_id/ajax-save-flagged
  defaults: { _controller: AgentBundle:Ticket:ajaxSaveFlagged }
  requirements: { ticket_id: "\d+" }