agent:
  pattern: /
  defaults: { _controller: AgentBundle:Main:index }

agent_dashboard:
  pattern: /
  defaults: { _controller: AgentBundle:Main:index }

agent_test:
  pattern: /test
  defaults: { _controller: AgentBundle:Test:index }

agent_interface_poller:
  pattern: /poller
  defaults: { _controller: AgentBundle:Poller:handler }

agent_accept_upload:
  pattern: /misc/accept-upload
  defaults: { _controller: AgentBundle:Misc:acceptTempUpload }

agent_show_blob:
  pattern: /misc/show-blob/{blob_id}
  defaults: { _controller: AgentBundle:Misc:showBlob }

agent_ajax_save_prefs:
  pattern: /misc/ajax-save-prefs
  defaults: { _controller: AgentBundle:Misc:ajaxSavePrefs }

agent_ajax_labels_autocomplete:
  pattern: /misc/ajax-labels/{label_type}
  defaults: { _controller: AgentBundle:Misc:ajaxLabelsAutocomplete }
  requirements: { label_type: "[a-z]+" }

agent_interface_data_js:
  pattern: /misc/interface-data.js
  defaults: { _controller: AgentBundle:Misc:getInterfaceData }



agent_messages_getnew:
  pattern: /client-messages/get-new-messages
  defaults: { _controller: AgentBundle:ClientMessages:getNewMessages, since: "0" }
  requirements: { since: "\d+" }

agent_messages_subscribe_channels:
  pattern: /client-messages/subscribe-channels
  defaults: { _controller: AgentBundle:ClientMessages:subscribeChannels }

agent_messages_unsubscribe_channels:
  pattern: /client-messages/unsubscribe-channels
  defaults: { _controller: AgentBundle:ClientMessages:unsubscribeChannels }

################################################################################
# Settings
################################################################################

agent_settings:
  pattern: /settings
  defaults: { _controller: AgentBundle:Settings:index }

agent_settings_picture:
  pattern: /settings/picture
  defaults: { _controller: AgentBundle:Settings:picture }

agent_settings_ticketmacros:
  pattern: /settings/ticket-macros
  defaults: { _controller: AgentBundle:Settings:ticketMacros }

agent_settings_ticketmacros_edit:
  pattern: /settings/ticket-macros/{macro_id}
  defaults: { _controller: AgentBundle:Settings:ticketMacroEdit }
  requirements: { macro_id: "\d+" }

agent_settings_ticketmacros_new:
  pattern: /settings/ticket-macros/new
  defaults: { _controller: AgentBundle:Settings:ticketMacroEdit, macro_id: 0 }

agent_settings_ticketmacros_del:
  pattern: /settings/ticket-macros/{macro_id}/delete
  defaults: { _controller: AgentBundle:Settings:ticketMacroDelete }
  requirements: { macro_id: "\d+" }

agent_settings_ticketfilters:
  pattern: /settings/ticket-filters
  defaults: { _controller: AgentBundle:Settings:ticketFilters }

agent_settings_ticketfilters_edit:
  pattern: /settings/ticket-filters/{filter_id}/edit
  defaults: { _controller: AgentBundle:Settings:ticketFilterEdit }
  requirements: { filter_id: "\d+" }

agent_settings_ticketfilters_del:
  pattern: /settings/ticket-filters/{filter_id}/delete
  defaults: { _controller: AgentBundle:Settings:ticketFilterDelete }
  requirements: { filter_id: "\d+" }

agent_settings_ticketfilters_new:
  pattern: /settings/ticket-filters/new-filter
  defaults: { _controller: AgentBundle:Settings:ticketFilterEdit, filter_id: 0 }

################################################################################
# People
################################################################################

agent_people:
  pattern: /people
  defaults: { _controller: AgentBundle:PeopleSearch:index }

agent_people_view:
  pattern: /people/{person_id}
  defaults: { _controller: AgentBundle:Person:view }
  requirements: { person_id: "\d+" }

agent_people_new:
  pattern: /people/new-person
  defaults: { _controller: AgentBundle:Person:new }

agent_people_ajaxsave:
  pattern: /people/{person_id}/ajax-save
  defaults: { _controller: AgentBundle:Person:ajaxSave }
  requirements: { person_id: "\d+" }

agent_people_ajaxsave_emails:
  pattern: /people/{person_id}/ajax-save-emails
  defaults: { _controller: AgentBundle:Person:ajaxSaveEmails }
  requirements: { person_id: "\d+" }

agent_people_ajaxsave_contact:
  pattern: /people/{person_id}/ajax-save-contact
  defaults: { _controller: AgentBundle:Person:ajaxSaveContact }
  requirements: { person_id: "\d+" }

agent_people_ajaxsave_note:
  pattern: /people/{person_id}/ajax-save-note
  defaults: { _controller: AgentBundle:Person:ajaxSaveNote }
  requirements: { person_id: "\d+" }

agent_people_ajaxsave_organization:
  pattern: /people/{person_id}/ajax-save-organization
  defaults: { _controller: AgentBundle:Person:ajaxSaveOrganization }
  requirements: { person_id: "\d+" }

agent_people_ajaxget_notes:
  pattern: /people/{person_id}/ajax-get-notes
  defaults: { _controller: AgentBundle:Person:ajaxGetNotes }
  requirements: { person_id: "\d+" }

agent_person_ajax_labels_save:
  pattern: /person/{person_id}/ajax-save-labels
  defaults: { _controller: AgentBundle:Person:ajaxSaveLabels }
  requirements: { person_id: "\d+" }

agent_person_ajaxsavecustomfields:
  pattern: /person/{person_id}/ajax-save-custom-fields
  defaults: { _controller: AgentBundle:Person:ajaxSaveCustomFields }
  requirements: { person_id: "\d+" }

agent_peoplesearch_perform:
  pattern: /people-search/search
  defaults: { _controller: AgentBundle:PeopleSearch:performSearch }

agent_peoplesearch_performquick:
  pattern: /people-search/search-quick
  defaults: { _controller: AgentBundle:PeopleSearch:performQuickSearch }

agent_peoplesearch:
  pattern: /people-search
  defaults: { _controller: AgentBundle:PeopleSearch:search }

agent_peoplesearch_labelspane:
  pattern: /people-search/labels-pane
  defaults: { _controller: AgentBundle:PeopleSearch:labelsPane }

agent_peoplesearch_labelsindexpane:
  pattern: /people-search/labels-index-pane
  defaults: { _controller: AgentBundle:PeopleSearch:labelsIndexPane }

agent_peoplesearch_org_labelspane:
  pattern: /people-search/org-labels-pane
  defaults: { _controller: AgentBundle:PeopleSearch:orgLabelsPane }

agent_peoplesearch_org_labelsindexpane:
  pattern: /people-search/org-labels-index-pane
  defaults: { _controller: AgentBundle:PeopleSearch:orgLabelsIndexPane }

agent_peoplesearch_findpane:
  pattern: /people-search/find-pane
  defaults: { _controller: AgentBundle:PeopleSearch:findPane }

agent_peoplesearch_directorypane:
  pattern: /people-search/directory-pane
  defaults: { _controller: AgentBundle:PeopleSearch:directoryPane }

agent_peoplesearch_usergroupspane:
  pattern: /people-search/usergroups-pane
  defaults: { _controller: AgentBundle:PeopleSearch:usergroupsPane }

################################################################################
# Ticket Search
################################################################################

agent_ticketsearch:
  pattern: /ticket-search
  defaults: { _controller: AgentBundle:TicketSearch:index }

agent_ticketsearch_overviewpane:
  pattern: /ticket-search/overview-pane
  defaults: { _controller: AgentBundle:TicketSearch:overviewPane }

agent_ticketsearch_labelspane:
  pattern: /ticket-search/labels-pane
  defaults: { _controller: AgentBundle:TicketSearch:labelsPane }

agent_ticketsearch_labelsindexpane:
  pattern: /ticket-search/labels-index-pane
  defaults: { _controller: AgentBundle:TicketSearch:labelsIndexPane }

agent_ticketsearch_overviewnav:
  pattern: /ticket-search/overview-nav
  defaults: { _controller: AgentBundle:TicketSearch:overviewNav }

agent_ticketsearch_runoverview:
  pattern: /ticket-search/overview-run
  defaults: { _controller: AgentBundle:TicketSearch:overviewRun }

agent_ticketsearch_ajaxmassactions:
  pattern: /ticket-search/ajax-mass-actions
  defaults: { _controller: AgentBundle:TicketSearch:ajaxMassActions }

agent_ticketsearch_filterspane:
  pattern: /ticket-search/filters-pane
  defaults: { _controller: AgentBundle:TicketSearch:filtersPane }

agent_ticketsearch_flaggedpane:
  pattern: /ticket-search/flagged-pane
  defaults: { _controller: AgentBundle:TicketSearch:flaggedPane }

agent_ticketsearch_findpane:
  pattern: /ticket-search/find-pane
  defaults: { _controller: AgentBundle:TicketSearch:findPane }

agent_ticketsearch_customfilter:
  pattern: /ticket-search/custom-filter
  defaults: { _controller: AgentBundle:TicketSearch:customFilter }

agent_ticketsearch_runcustomfilter:
  pattern: /ticket-search/custom-filter/run
  defaults: { _controller: AgentBundle:TicketSearch:runCustomFilter }

agent_ticketsearch_search:
  pattern: /ticket-search/search
  defaults: { _controller: AgentBundle:TicketSearch:search }

agent_ticketsearch_runsearch:
  pattern: /ticket-search/search/run
  defaults: { _controller: AgentBundle:TicketSearch:runSearch }

agent_ticketsearch_runfilter:
  pattern: /ticket-search/filter/{filter_id}
  defaults: { _controller: AgentBundle:TicketSearch:runfilter }
  requirements: { filter_id: "\d+" }

agent_ticketsearch_runnamedfilter:
  pattern: /ticket-search/filter/{filter_name}
  defaults: { _controller: AgentBundle:TicketSearch:runNamedFilter }

agent_ticketsearch_runflag:
  pattern: /ticket-search/flag/{flag}
  defaults: { _controller: AgentBundle:TicketSearch:runFlagged }

agent_ticketsearch_save_resultprefs:
  pattern: /ticket-search/save-result-prefs/{cache_id}
  defaults: { _controller: AgentBundle:TicketSearch:ajaxSaveResultPrefs }
  requirements: { cache_id: "\d+" }

agent_ticketsearch_ajax_get_macro:
  pattern: /ticket-search/ajax-get-macro
  defaults: { _controller: AgentBundle:TicketSearch:ajaxGetMacro }

agent_ticketsearch_ajax_save_macro:
  pattern: /ticket-search/ajax-save-macro
  defaults: { _controller: AgentBundle:TicketSearch:ajaxSaveMacro }

agent_ticketsearch_ajax_delete_tickets:
  pattern: /ticket-search/ajax-delete-tickets
  defaults: { _controller: AgentBundle:TicketSearch:ajaxDeleteTickets }

agent_ticketsearch_ajax_mass_reply:
  pattern: /ticket-search/ajax-mass-reply
  defaults: { _controller: AgentBundle:TicketSearch:ajaxMassReply }

agent_ticketsearch_ajax_release_locks:
  pattern: /ticket-search/ajax-release-locks
  defaults: { _controller: AgentBundle:TicketSearch:ajaxReleaseLocks }

################################################################################
# Ticket
################################################################################

agent_ticket_new:
  pattern: /tickets/new
  defaults: { _controller: AgentBundle:Ticket:new }

agent_people_new_ajaxsave:
  pattern: /tickets/new-ajax-save
  defaults: { _controller: AgentBundle:Ticket:newAjaxSave }

agent_ticket_view:
  pattern: /tickets/{ticket_id}
  defaults: { _controller: AgentBundle:Ticket:view }
  requirements: { ticket_id: "\d+" }

agent_ticket_ajaxsavecustomfields:
  pattern: /tickets/{ticket_id}/ajax-save-custom-fields
  defaults: { _controller: AgentBundle:Ticket:ajaxSaveCustomFields }
  requirements: { ticket_id: "\d+" }

agent_ticket_ajaxsavereply:
  pattern: /tickets/{ticket_id}/ajax-save-reply
  defaults: { _controller: AgentBundle:Ticket:ajaxSaveReply }
  requirements: { ticket_id: "\d+" }

agent_ticket_ajaxsavenote:
  pattern: /tickets/{ticket_id}/ajax-save-note
  defaults: { _controller: AgentBundle:Ticket:ajaxSaveNote }
  requirements: { ticket_id: "\d+" }

agent_ticket_ajaxsaveoptions:
  pattern: /tickets/{ticket_id}/ajax-save-options
  defaults: { _controller: AgentBundle:Ticket:ajaxSaveOptions }
  requirements: { ticket_id: "\d+" }

agent_ticket_ajaxsaveflagged:
  pattern: /tickets/{ticket_id}/ajax-save-flagged
  defaults: { _controller: AgentBundle:Ticket:ajaxSaveFlagged }
  requirements: { ticket_id: "\d+" }

agent_ticket_ajaxtab_ticketlog:
  pattern: /tickets/{ticket_id}/ajax-tab-ticket-Log
  defaults: { _controller: AgentBundle:Ticket:ajaxTabTicketLog }
  requirements: { ticket_id: "\d+" }

agent_ticket_ajaxtab_attachments:
  pattern: /tickets/{ticket_id}/ajax-tab-attachments
  defaults: { _controller: AgentBundle:Ticket:ajaxTabAttachments }
  requirements: { ticket_id: "\d+" }

agent_ticket_ajax_labels_save:
  pattern: /tickets/{ticket_id}/ajax-save-labels
  defaults: { _controller: AgentBundle:Ticket:ajaxSaveLabels }
  requirements: { ticket_id: "\d+" }

agent_ticket_ajax_get_macro:
  pattern: /tickets/{ticket_id}/ajax-get-macro
  defaults: { _controller: AgentBundle:Ticket:ajaxGetMacro }
  requirements: { ticket_id: "\d+" }

agent_ticket_ajax_save_actions:
  pattern: /tickets/{ticket_id}/ajax-save-actions
  defaults: { _controller: AgentBundle:Ticket:ajaxSaveActions }
  requirements: { ticket_id: "\d+" }

agent_ticket_message_unformatted:
  pattern: /tickets/{ticket_id}/message-details/{message_id}/unformatted
  defaults: { _controller: AgentBundle:Ticket:viewUnformattedMessage }
  requirements: { ticket_id: "\d+", message_id: "\d+" }

agent_ticket_message_ajax_getquote:
  pattern: /tickets/{ticket_id}/message-details/{message_id}/ajax-get-quote
  defaults: { _controller: AgentBundle:Ticket:ajaxGetMessageQuote }
  requirements: { ticket_id: "\d+", message_id: "\d+" }

agent_ticket_ajax_getmessages:
  pattern: /tickets/{ticket_id}/ajax-get-messages
  defaults: { _controller: AgentBundle:Ticket:ajaxGetMessages }
  requirements: { ticket_id: "\d+" }

################################################################################
# Twitter
################################################################################

agent_twitter_statuses:
  pattern: /twitter/statuses/{account_id}
  defaults: { _controller: AgentBundle:Twitter:statuses }

agent_twitter_accountspane:
  pattern: /twitter/pane/accounts
  defaults: { _controller: AgentBundle:Twitter:accountsPane }

agent_twitter_statusespane:
  pattern: /twitter/pane/statuses
  defaults: { _controller: AgentBundle:Twitter:statusesPane }
