agent:
  pattern: /
  defaults: { _controller: AgentBundle:Main:index }

agent_dashboard:
  pattern: /
  defaults: { _controller: AgentBundle:Main:index }

agent_test:
  pattern: /test
  defaults: { _controller: AgentBundle:Test:index }

agent_interface_poller:
  pattern: /poller
  defaults: { _controller: AgentBundle:Poller:handler }

agent_accept_upload:
  pattern: /misc/accept-upload
  defaults: { _controller: AgentBundle:Misc:acceptTempUpload }

agent_show_blob:
  pattern: /misc/show-blob/{blob_id}
  defaults: { _controller: AgentBundle:Misc:showBlob }

agent_ajax_save_prefs:
  pattern: /misc/ajax-save-prefs
  defaults: { _controller: AgentBundle:Misc:ajaxSavePrefs }

agent_ajax_labels_autocomplete:
  pattern: /misc/ajax-labels
  defaults: { _controller: AgentBundle:Misc:ajaxLabelsAutocomplete }

################################################################################
# Settings
################################################################################

agent_settings:
  pattern: /settings
  defaults: { _controller: AgentBundle:Settings:index }

agent_settings_ticketmacros:
  pattern: /settings/ticket-macros
  defaults: { _controller: AgentBundle:Settings:ticketMacros }

agent_settings_ticketmacros_edit:
  pattern: /settings/ticket-macros/{macro_id}
  defaults: { _controller: AgentBundle:Settings:ticketMacroEdit }
  requirements: { macro_id: "\d+" }

agent_settings_ticketmacros_new:
  pattern: /settings/ticket-macros/new
  defaults: { _controller: AgentBundle:Settings:ticketMacroEdit, macro_id: 0 }

agent_settings_ticketmacros_del:
  pattern: /settings/ticket-macros/{macro_id}/delete
  defaults: { _controller: AgentBundle:Settings:ticketMacroDelete }
  requirements: { macro_id: "\d+" }

agent_settings_ticketqueues:
  pattern: /settings/ticket-queues
  defaults: { _controller: AgentBundle:Settings:ticketQueues }

agent_settings_ticketqueues_edit:
  pattern: /settings/ticket-queues/{queue_id}/edit
  defaults: { _controller: AgentBundle:Settings:ticketQueueEdit }
  requirements: { queue_id: "\d+" }

agent_settings_ticketqueues_del:
  pattern: /settings/ticket-queues/{queue_id}/delete
  defaults: { _controller: AgentBundle:Settings:ticketQueueDelete }
  requirements: { queue_id: "\d+" }

agent_settings_ticketqueues_new:
  pattern: /settings/ticket-queues/new-queue
  defaults: { _controller: AgentBundle:Settings:ticketQueueEdit, queue_id: 0 }

################################################################################
# People
################################################################################

agent_people:
  pattern: /people
  defaults: { _controller: AgentBundle:PeopleSearch:index }

agent_people_view:
  pattern: /people/{person_id}
  defaults: { _controller: AgentBundle:Person:view }
  requirements: { person_id: "\d+" }

agent_people_new:
  pattern: /people/new-person
  defaults: { _controller: AgentBundle:Person:new }

agent_people_ajaxsave:
  pattern: /people/{person_id}/ajax-save
  defaults: { _controller: AgentBundle:Person:ajaxSave }
  requirements: { person_id: "\d+" }

agent_people_ajaxsave_emails:
  pattern: /people/{person_id}/ajax-save-emails
  defaults: { _controller: AgentBundle:Person:ajaxSaveEmails }
  requirements: { person_id: "\d+" }

agent_people_ajaxsave_contact:
  pattern: /people/{person_id}/ajax-save-contact
  defaults: { _controller: AgentBundle:Person:ajaxSaveContact }
  requirements: { person_id: "\d+" }

agent_people_ajaxsave_note:
  pattern: /people/{person_id}/ajax-save-note
  defaults: { _controller: AgentBundle:Person:ajaxSaveNote }
  requirements: { person_id: "\d+" }

agent_people_ajaxsave_organization:
  pattern: /people/{person_id}/ajax-save-organization
  defaults: { _controller: AgentBundle:Person:ajaxSaveOrganization }
  requirements: { person_id: "\d+" }

agent_people_ajaxget_notes:
  pattern: /people/{person_id}/ajax-get-notes
  defaults: { _controller: AgentBundle:Person:ajaxGetNotes }
  requirements: { person_id: "\d+" }

agent_person_ajax_labels_save:
  pattern: /person/{person_id}/ajax-save-labels
  defaults: { _controller: AgentBundle:Person:ajaxSaveLabels }
  requirements: { person_id: "\d+" }

agent_peoplesearch_perform:
  pattern: /people-search/search
  defaults: { _controller: AgentBundle:PeopleSearch:performSearch }

agent_peoplesearch_performquick:
  pattern: /people-search/search-quick
  defaults: { _controller: AgentBundle:PeopleSearch:performQuickSearch }

agent_peoplesearch:
  pattern: /people-search
  defaults: { _controller: AgentBundle:PeopleSearch:search }

agent_peoplesearch_labelspane:
  pattern: /people-search/labels-pane
  defaults: { _controller: AgentBundle:PeopleSearch:labelsPane }

agent_peoplesearch_findpane:
  pattern: /people-search/find-pane
  defaults: { _controller: AgentBundle:PeopleSearch:findPane }

agent_peoplesearch_directorypane:
  pattern: /people-search/directory-pane
  defaults: { _controller: AgentBundle:PeopleSearch:directoryPane }


################################################################################
# Ticket Search
################################################################################

agent_ticketsearch:
  pattern: /ticket-search
  defaults: { _controller: AgentBundle:TicketSearch:index }

agent_ticketsearch_overviewpane:
  pattern: /ticket-search/overview-pane
  defaults: { _controller: AgentBundle:TicketSearch:overviewPane }
  
agent_ticketsearch_labelspane:
    pattern: /ticket-search/labels-pane
    defaults: { _controller: AgentBundle:TicketSearch:labelsPane }

agent_ticketsearch_run_label:
  pattern: /ticket-search/label/{label}
  defaults: { _controller: AgentBundle:TicketSearch:runLabel }

agent_ticketsearch_overviewnav:
  pattern: /ticket-search/overview-nav
  defaults: { _controller: AgentBundle:TicketSearch:overviewNav }

agent_ticketsearch_runoverview:
  pattern: /ticket-search/overview-run
  defaults: { _controller: AgentBundle:TicketSearch:overviewRun }

agent_ticketsearch_ajaxmassactions:
  pattern: /ticket-search/ajax-mass-actions
  defaults: { _controller: AgentBundle:TicketSearch:ajaxMassActions }

agent_ticketsearch_queuespane:
  pattern: /ticket-search/queues-pane
  defaults: { _controller: AgentBundle:TicketSearch:queuesPane }

agent_ticketsearch_flaggedpane:
  pattern: /ticket-search/flagged-pane
  defaults: { _controller: AgentBundle:TicketSearch:flaggedPane }

agent_ticketsearch_findpane:
  pattern: /ticket-search/find-pane
  defaults: { _controller: AgentBundle:TicketSearch:findPane }

agent_ticketsearch_filter:
  pattern: /ticket-search/filter
  defaults: { _controller: AgentBundle:TicketSearch:filter }

agent_ticketsearch_runfilter:
  pattern: /ticket-search/filter/run
  defaults: { _controller: AgentBundle:TicketSearch:runFilter }

agent_ticketsearch_search:
  pattern: /ticket-search/search
  defaults: { _controller: AgentBundle:TicketSearch:search }

agent_ticketsearch_runsearch:
  pattern: /ticket-search/search/run
  defaults: { _controller: AgentBundle:TicketSearch:runSearch }

agent_ticketsearch_runqueue:
  pattern: /ticket-search/queue/{queue_id}
  defaults: { _controller: AgentBundle:TicketSearch:runqueue }
  requirements: { queue_id: "\d+" }

agent_ticketsearch_runflag:
  pattern: /ticket-search/flag/{flag}
  defaults: { _controller: AgentBundle:TicketSearch:runFlagged }


################################################################################
# Ticket
################################################################################

agent_ticket_new:
  pattern: /tickets/new
  defaults: { _controller: AgentBundle:Ticket:new }

agent_people_new_ajaxsave:
  pattern: /tickets/new-ajax-save
  defaults: { _controller: AgentBundle:Ticket:newAjaxSave }

agent_ticket_view:
  pattern: /tickets/{ticket_id}
  defaults: { _controller: AgentBundle:Ticket:view }
  requirements: { ticket_id: "\d+" }

agent_ticket_ajaxsavecustomfields:
  pattern: /tickets/{ticket_id}/ajax-save-custom-fields
  defaults: { _controller: AgentBundle:Ticket:ajaxSaveCustomFields }
  requirements: { ticket_id: "\d+" }

agent_ticket_ajaxsavereply:
  pattern: /tickets/{ticket_id}/ajax-save-reply
  defaults: { _controller: AgentBundle:Ticket:ajaxSaveReply }
  requirements: { ticket_id: "\d+" }

agent_ticket_ajaxsaveoptions:
  pattern: /tickets/{ticket_id}/ajax-save-options
  defaults: { _controller: AgentBundle:Ticket:ajaxSaveOptions }
  requirements: { ticket_id: "\d+" }

agent_ticket_ajaxsaveflagged:
  pattern: /tickets/{ticket_id}/ajax-save-flagged
  defaults: { _controller: AgentBundle:Ticket:ajaxSaveFlagged }
  requirements: { ticket_id: "\d+" }

agent_ticket_ajaxticketlog:
  pattern: /tickets/{ticket_id}/ajax-ticket-log
  defaults: { _controller: AgentBundle:Ticket:ajaxTicketLog }
  requirements: { ticket_id: "\d+" }

agent_ticket_ajax_labels_save:
  pattern: /tickets/{ticket_id}/ajax-save-labels
  defaults: { _controller: AgentBundle:Ticket:ajaxSaveLabels }
  requirements: { ticket_id: "\d+" }


################################################################################
# Twitter
################################################################################

agent_twitter:
  pattern: /twitter
  defaults: { _controller: AgentBundle:Twitter:index }

agent_twitter_queuespane:
  pattern: /twitter/queues-pane
  defaults: { _controller: AgentBundle:Twitter:queuesPane }

agent_twitter_callback:
  pattern: /twitter/callback
  defaults: { _controller: AgentBundle:Twitter:callBack }

