<?php

$finder = Symfony\CS\Finder\DefaultFinder::create()
    ->exclude('docs')
    ->exclude('vendor')
    ->exclude('vendor-src')
    ->notName('StaticReflectionProperty_Real.php')
    ->in(__DIR__)
;

return Symfony\CS\Config\Config::create()
    ->fixers(array(
        'align_double_arrow',
        'align_equals',
        'braces',
        'concat_without_spaces',
        'duplicate_semicolon',
        'elseif',
        'encoding',
        'eof_ending',
        'extra_empty_lines',
        'function_call_space',
        'function_declaration',
        'include',
        'indentation',
        'line_after_namespace',
        'linefeed',
        'lowercase_constants',
        'lowercase_keywords',
        'method_argument_space',
        'multiline_array_trailing_comma',
        'multiple_use',
        'namespace_no_leading_whitespace',
        'new_with_braces',
        'no_blank_lines_after_class_opening',
        'no_empty_lines_after_phpdocs',
        'object_operator',
        'operators_spaces',
        'ordered_use',
        'phpdoc_order',
        'parenthesis',
        'php_closing_tag',
        'single_line_after_imports',
        'phpdoc_params',
        'phpdoc_indent',
        'phpdoc_no_empty_return',
        'phpdoc_no_package',
        'phpdoc_separation',
        'phpdoc_short_description',
        'phpdoc_to_comment',
        'phpdoc_trim',
        'phpdoc_var_without_name',
        'remove_leading_slash_use',
        'remove_lines_between_uses',
        'return',
        'short_tag',
        'single_array_no_trailing_comma',
        'spaces_before_semicolon',
        'spaces_cast',
        'standardize_not_equal',
        'ternary_spaces',
        'trailing_spaces',
        'unused_use',
        'visibility',
        'whitespacy_lines',
    ))
    ->finder($finder)
;
