requirejs.config({
	"baseUrl": DP_ASSET_URL,
	"waitSeconds": 60,
	"urlArgs": ((DP_IS_DEBUG && !DP_USE_RJS_BUILD) ? "bust=" + (new Date()).getTime() : "v=" + (DP_BUILD_TIME || "0")),
	"paths": {
		"angular":                         "app/bower_components/angular/angular.min",
		"angularRoute":                    "app/bower_components/angular-route/angular-route.min",
		"angularAnimate":                  "app/bower_components/angular-animate/angular-animate.min",
		"angularBootstrap":                "app/bower_components/angular-bootstrap/ui-bootstrap-tpls.min",
		"angularSanitize":                 "app/bower_components/angular-sanitize/angular-sanitize.min",
		"angularSelect2":                  "app/bower_components/angular-ui-select2/src/select2",
		"angularUiAce":                    "app/bower_components/angular-ui-ace/ui-ace",
		"angularUiRouter":                 "app/bower_components/angular-ui-router/release/angular-ui-router.min",
		"angularUiSortable":               "app/bower_components/angular-ui-sortable/src/sortable",
		"angularMoment":                   "app/bower_components/angular-moment/angular-moment",
		"angularFileUpload":               "app/bower_components/blueimp-file-upload/js/jquery.fileupload-angular",
		"angularSlider":                   "app/bower_components/angular-slider/angular-slider.min",
		"angularGrid":                     "app/bower_components/angular-grid/build/ng-grid.min",
		"ngFileUpload":                    "app/bower_components/ng-file-upload/angular-file-upload.min",
		"jquery":                          "app/bower_components/jquery/jquery.min",
		"jqueryUi":                        "app/bower_components/jquery-ui/ui/minified/jquery-ui.min",
		"jquery.ui.widget":                "app/bower_components/blueimp-file-upload/js/vendor/jquery.ui.widget",
		"jquery.fileupload":               "app/bower_components/blueimp-file-upload/js/jquery.fileupload",
		"jquery.fileupload-process":       "app/bower_components/blueimp-file-upload/js/jquery.fileupload-process",
		"jquery.fileupload-image":         "app/bower_components/blueimp-file-upload/js/jquery.fileupload-image",
		"jquery.fileupload-audio":         "app/bower_components/blueimp-file-upload/js/jquery.fileupload-audio",
		"jquery.fileupload-video":         "app/bower_components/blueimp-file-upload/js/jquery.fileupload-video",
		"jquery.fileupload-validate":      "app/bower_components/blueimp-file-upload/js/jquery.fileupload-validate",
		"load-image":                      "app/bower_components/blueimp-load-image/js/load-image",
		"load-image-meta":                 "app/bower_components/blueimp-load-image/js/load-image-meta",
		"load-image-ios":                  "app/bower_components/blueimp-load-image/js/load-image-ios",
		"load-image-exif":                 "app/bower_components/blueimp-load-image/js/load-image-exif",
		"canvas-to-blob":                  "app/bower_components/blueimp-canvas-to-blob/js/canvas-to-blob.min",
		"underscore":                      "app/bower_components/underscore/underscore-min",
		"momentTimezone":                  "app/vendor-src/moment-timezone",
		"moment":                          "app/bower_components/moment/min/moment-with-langs.min",
		"aceEditor":                       "app/bower_components/ace-builds/src-min-noconflict/ace",
		"stacktrace":                      "app/bower_components/stacktrace/stacktrace",
		"bootstrapModal":                  "app/bower_components/bootstrap/js/modal",
		"bootstrapTooltip":                "app/bower_components/bootstrap/js/tooltip",
		"select2":                         "app/bower_components/select2/select2.min",
		"toastr":                          "app/bower_components/toastr/toastr",
		"ColorPicker":                     "vendor/colorpicker/js/colorpicker.min",
		"jstz":                            "vendor/detect_timezone",
		"intl-tel-input":                  "app/bower_components/intl-tel-input/build/js/intlTelInput.min",

		"AdminLoad":                       (DP_USE_RJS_BUILD ? "app/build/Admin/js/build" : "app/Admin/AdminLoad"),
		"CloudAdminLoad":                  (DP_USE_RJS_BUILD ? "app/build/Admin/js/build" : "app/Admin/Cloud/CloudAdminLoad"),
		"AdminUpgradeLoad":                (DP_USE_RJS_BUILD ? "app/build/AdminUpgrade/js/build" : "app/AdminUpgrade/AdminUpgradeLoad"),
		"AdminStartLoad":                  (DP_USE_RJS_BUILD ? "app/build/AdminStart/js/build" : "app/AdminStart/AdminStartLoad"),
		"ReportsLoad":                     (DP_USE_RJS_BUILD ? "app/build/Reports/js/build" : "app/Reports/ReportsLoad"),

		"DeskPRO":                         "app/build/DeskPRO/js",
		"Admin":                           "app/build/Admin/js",
		"AdminRouting":                    "app/Admin/Resources/config/routing",
		"AdminUpgrade":                    "app/build/AdminUpgrade/js",
		"AdminStart":                      "app/build/AdminStart/js",
		"Reports":                         "app/build/Reports/js",
		"ReportsRouting":                  "app/Reports/Resources/config/routing"
	},
	"shim": {
		"angular":                         {"exports" : "angular", "deps": ["jquery"]},
		"angularRoute":                    ["angular"],
		"angularAnimate":                  ["angular"],
		"angularBootstrap":                ["angular"],
		"angularSanitize":                 ["angular"],
		"angularSelect2":                  ["angular", "select2"],
		"angularUiAce":                    ["angular"],
		"angularUiRouter":                 ["angular"],
		"angularUiSortable":               ["angular"],
		"angularMoment":                   ["angular", "moment"],
		"angularFileUpload":               ["jquery"],
		"angularSlider":                   ["angular"],
		"angularGrid":                     ["angular"],
		"ngFileUpload":                    ["angular"],
		"jquery":                          { "exports": "jquery" },
		"jqueryUi":                        ["jquery"],
		"bootstrapModal":                  ["jquery"],
		"bootstrapTooltip":                ["jquery", "jqueryUi"],
		"select2":                         ["jquery"],
		"toastr":                          ["jquery"],
		"ColorPicker":                     ["jquery"],
		"jstz":                            { "exports": "jstz" },
		"underscore":                      { "exports": "_" },
		"stacktrace":                      { "exports": "printStackTrace"},
		"trackjs":                         { "exports": "trackJs"},
		"intl-tel-input":                  ["jquery"]
	},
	"priority": [
		"jquery",
		"angular"
	]
});

window.name = "NG_DEFER_BOOTSTRAP!";
requirejs([DP_INTERFACE_LOADER], function(Loader) {
	Loader.start()
});
