services:

    data_serializer:
        class: DeskPRO\Bundle\ApiBundle\DataSerializer\DataSerializer
        arguments:
            - @data_serializer.type_map
            - @data_serializer.transformer_factory
            - @data_serializer.property_transformer
            - @logger

    data_serializer.property_transformer:
        class: DeskPRO\Bundle\ApiBundle\DataSerializer\DataPropertyTransformer
        arguments:
            "property_transformers":
                - @data_serializer.property_transformer.doctrine
                - @data_serializer.property_transformer.date

    data_serializer.property_transformer.date:
        class: DeskPRO\Bundle\ApiBundle\DataSerializer\PropertyTransformer\DatePropertyTransformer

    data_serializer.property_transformer.doctrine:
        class: DeskPRO\Bundle\ApiBundle\DataSerializer\PropertyTransformer\Doctrine\DoctrinePropertyTransformer
        arguments: [@doctrine_association_manager]

    data_serializer.type_map:
        class: DeskPRO\Bundle\ApiBundle\DataSerializer\DataTypeMap

    data_serializer.transformer_factory:
        class: DeskPRO\Bundle\ApiBundle\DataSerializer\DataTransformerFactory
        arguments:
            - @service_container

    # the transformers
    # note: you don't need a tag for these to work. just make the prefix the same.
    #       to reference this transformer, just use "sandbox_widget" (ignore the prefix when using).
    data_serializer.transformer.sandbox_widget:
        class: DeskPRO\Bundle\ApiBundle\DataSerializer\Transformer\SandboxWidgetTransformer