services:

    # DATA TRANSFORMERS
    #
    # NOTE: If you are making a transformer and no dependency injection is needed, you don't need
    # to make it a service. Instead, you can make a class name by convention.
    # For example the transformer for the type "sandbox_widget" just make the class:
    # DeskPRO\Bundle\ApiBundle\DataSerializer\DataTransformer\SandboxWidgetTransformer
    #
    # note: you don't need a tag for these to work. just make the prefix the same.
    #       to reference this transformer, just use "sandbox_widget" (ignore the prefix when using).

    # Example transformer service declaration for "sandbox_widget"
    #    data_serializer.transformer.sandbox_widget:
    #        class: DeskPRO\Bundle\ApiBundle\DataSerializer\DataTransformer\SandboxWidgetTransformer
