services:

    # the manager
    api_fractal_manager:
        class: DeskPRO\Bundle\ApiBundle\Fractal\FractalManager
        arguments:
            - @service_container
        calls:
            - [setSerializer, [@api_fractal_serializer]]
    api_fractal_serializer:
        class: DeskPRO\Bundle\ApiBundle\Fractal\FractalJsonSerializer

    # the transformers
    # note: you don't need a tag for these to work. just make the prefix the same.
    #       to reference this transformer, just use "sandbox_widget" (ignore the prefix when using).
    api_transformer.sandbox_widget:
        class: DeskPRO\Bundle\ApiBundle\Fractal\Transformer\SandboxWidgetTransformer
    api_transformer.task:
        class: DeskPRO\Bundle\ApiBundle\Fractal\Transformer\TaskTransformer
    api_transformer.task_label:
        class: DeskPRO\Bundle\ApiBundle\Fractal\Transformer\TaskLabelTransformer
    api_transformer.task_comment:
        class: DeskPRO\Bundle\ApiBundle\Fractal\Transformer\TaskCommentTransformer
    api_transformer.task_attachment:
        class: DeskPRO\Bundle\ApiBundle\Fractal\Transformer\TaskAttachmentTransformer
    api_transformer.task_linked_item:
        class: DeskPRO\Bundle\ApiBundle\Fractal\Transformer\TaskLinkedItemTransformer