services:

  api_authenticator:
    class: DeskPRO\Bundle\ApiBundle\Security\Authentication\ApiAuthenticator
    arguments:
      - @doctrine.orm.default_entity_manager
  api_anon_authenticator:
    class: DeskPRO\Bundle\ApiBundle\Security\Authentication\ApiAuthenticator
    arguments:
      - @doctrine.orm.default_entity_manager

  api_user_provider:
    class: DeskPRO\Bundle\ApiBundle\Security\Authentication\ApiUserProvider
    arguments:
      - @doctrine.orm.default_entity_manager

  api_authorization.action_permissions.event_listener:
    class: DeskPRO\Bundle\ApiBundle\EventListener\ApiEndpointListener
    arguments:
      - @security.authorization_checker
    tags:
      - {name: kernel.event_subscriber }

  api_authorization.action_permissions_helper:
    class: DeskPRO\Bundle\ApiBundle\Security\Authorization\ActionPermissionsHelper

  api_authorization.action_permissions_voter:
    class: DeskPRO\Bundle\ApiBundle\Security\Authorization\ActionPermissionsVoter
    arguments:
      - @api_authorization.action_permissions.metadata_factory
      - @api_authorization.action_permissions_helper
      - @doctrine.orm.default_entity_manager
    tags:
      - { name: security.voter }

parameters:
  security.authentication.manager.erase_credentials: false