services:

  api_authenticator:
    class: DeskPRO\Bundle\ApiBundle\Security\Authentication\ApiAuthenticator
    arguments:
      - @doctrine.orm.default_entity_manager

  api_user_provider:
    class: DeskPRO\Bundle\ApiBundle\Security\Authentication\ApiUserProvider
    arguments:
      - @doctrine.orm.default_entity_manager

  api_authorization.action_permissions.event_listener:
    class: DeskPRO\Bundle\ApiBundle\EventListener\ApiEndpointListener
    arguments:
      - @security.authorization_checker
#    tags:
#      - {name: kernel.event_listener, event: kernel.controller, method: onKernelController}

  api_authorization.action_permissions_voter:
    class: DeskPRO\Bundle\ApiBundle\Security\Authorization\ActionPermissionsVoter
    arguments:
      - @api_authorization.action_permissions.driver
      - %kernel.cache_dir%
    tags:
      - { name: security.voter }