imports:
  - { resource: "config.yml" }

parameters:
  kernel.debug: true

framework:
  router:   { resource: "%kernel.root_dir%/config/admin/routing_dev.yml" }
  profiler: { only_exceptions: false }

twig:
  debug: %kernel.debug%
