tech_login:
    pattern:  /login
    defaults: { _controller: TechBundle:Login:index }

tech_logout:
  pattern: /login/logout
  defaults: { _controller: TechBundle:Login:logout }

tech_dashboard:
  pattern: /
  defaults: { _controller: TechBundle:Main:index }

tech_admin_styles:
  pattern: /styles
  defaults: { _controller: TechBundle:Styles:index }

tech_admin_styles_intro:
  pattern: /styles/intro
  defaults: { _controller: TechBundle:Styles:intro }

tech_admin_styles_newstyle:
  pattern: /styles/new-style
  defaults: { _controller: TechBundle:Styles:newstyle }