tech_dashboard:
  pattern: /
  defaults: { _controller: TechBundle:Main:index }

################################################################################
# Styles
################################################################################

tech_admin_styles:
  pattern: /styles
  defaults: { _controller: TechBundle:Styles:index }

tech_admin_styles_intro:
  pattern: /styles/intro
  defaults: { _controller: TechBundle:Styles:intro }

tech_admin_styles_showstyle:
  pattern: /styles/:style_id
  defaults: { _controller: TechBundle:Styles:showStyle }
  requirements: { style_id: "\d+" }

tech_admin_styles_editstyle:
  pattern: /styles/:style_id/edit
  defaults: { _controller: TechBundle:Styles:editStyle }
  requirements: { style_id: "\d+" }

tech_admin_styles_newstyle:
  pattern: /styles/new-style
  defaults: { _controller: TechBundle:Styles:editStyle, style_id: 0 }

tech_admin_styles_resources:
  pattern: /styles/:style_id/resources
  defaults: { _controller: TechBundle:Styles:styleResourceList }
  requirements: { style_id: "\d+" }

tech_admin_styles_templates:
  pattern: /styles/:style_id/templates
  defaults: { _controller: TechBundle:Styles:styleTemplateList }
  requirements: { style_id: "\d+" }

tech_admin_styles_edittemplate:
  pattern: /styles/:style_id/templates/:template_name
  defaults: { _controller: TechBundle:Styles:editTemplate }
  requirements: { style_id: "\d+" }


################################################################################
# Languages
################################################################################

tech_admin_langs:
  pattern: /languages
  defaults: { _controller: TechBundle:Languages:index }

tech_admin_langs_intro:
  pattern: /languages/intro
  defaults: { _controller: TechBundle:Languages:intro }

tech_admin_langs_editlang:
  pattern: /languages/:lang_id/edit
  defaults: { _controller: TechBundle:Languages:editLang }
  requirements: { lang_id: "\d+" }

tech_admin_langs_newlang:
  pattern: /languages/new-language
  defaults: { _controller: TechBundle:Languages:editLang, lang_id: 0 }

tech_admin_langs_phrases:
  pattern: /languages/:lang_id/phrases
  defaults: { _controller: TechBundle:Languages:listPhrases}
  requirements: { lang_id: "\d+", phrase_group: null }

tech_admin_langs_editphrase:
  pattern: /languages/:lang_id/edit-phrase/:phrase_name
  defaults: { _controller: TechBundle:Languages:editPhrase }
  requirements: { lang_id: "\d+" }


################################################################################
# Usersources
################################################################################

tech_admin_usersources:
  pattern: /usersources
  defaults: { _controller: TechBundle:Usersources:index }

tech_admin_usersources_intro:
  pattern: /usersources/intro
  defaults: { _controller: TechBundle:Usersources:intro }

tech_admin_usersources_info:
  pattern: /usersources/:usersource_id
  defaults: { _controller: TechBundle:Usersources:info }
  requirements: { usersource_id: "\d+" }

tech_admin_usersources_edit:
  pattern: /usersources/:usersource_id/edit
  defaults: { _controller: TechBundle:Usersources:edit }
  requirements: { usersource_id: "\d+" }

tech_admin_usersources_new:
  pattern: /usersources/new-usersource
  defaults: { _controller: TechBundle:Usersources:edit, usersource_id: 0 }


################################################################################
# Fields
################################################################################

tech_admin_fields:
  pattern: /fields
  defaults: { _controller: TechBundle:Fields:index }

tech_admin_fields_newfield:
  pattern: /fields/new-field
  defaults: { _controller: TechBundle:Fields:editField, field_id: 0 }

tech_admin_fields_editfield:
  pattern: /fields/:field_id/edit
  defaults: { _controller: TechBundle:Fields:editField }
  requirements: { field_id: "\d+" }

tech_admin_fields_testfield:
  pattern: /fields/:field_id/test
  defaults: { _controller: TechBundle:Fields:testField }
  requirements: { field_id: "\d+" }


################################################################################
# API Keys
################################################################################

tech_admin_api:
  pattern: /api
  defaults: { _controller: TechBundle:Api:index }

tech_admin_api_intro:
  pattern: /api/intro
  defaults: { _controller: TechBundle:Api:intro }

tech_admin_api_keyinfo:
  pattern: /api/key/:apikey
  defaults: { _controller: TechBundle:Api:infoKey }
  requirements: { usersource_id: "\d+" }

tech_admin_api_editkey:
  pattern: /api/key/:apikey/edit
  defaults: { _controller: TechBundle:Api:editKey }

tech_admin_api_newkey:
  pattern: /api/new-key
  defaults: { _controller: TechBundle:Api:editKey, apikey: 0 }


################################################################################
# People
################################################################################

tech_people:
  pattern: /people
  defaults: { _controller: TechBundle:PeopleSearch:index }

tech_people_view:
  pattern: /people/:person_id
  defaults: { _controller: TechBundle:People:view }
  requirements: { person_id: "\d+" }
