services:
  data.departments:
      class: Application\AppBundle\DataService\DepartmentDataService
      arguments: [@doctrine.orm.default_entity_manager, @portal_permissions_manager]
  data.articles:
      class: Application\AppBundle\DataService\ArticlesDataService
      arguments: [@doctrine.orm.default_entity_manager]
  data.news:
      class: Application\AppBundle\DataService\NewsDataService
      arguments: [@doctrine.orm.default_entity_manager]
  data.downloads:
      class: Application\AppBundle\DataService\DownloadsDataService
      arguments: [@doctrine.orm.default_entity_manager]
  data.feedback:
      class: Application\AppBundle\DataService\FeedbackDataService
      arguments: [@doctrine.orm.default_entity_manager]
  data.ticket_view:
      class: Application\AppBundle\DataService\TicketViewService
      arguments: [@form_field_manager, @ticket_layout_factory, @deskpro.core.translate]