services:

  new_mailer:
      class: Application\AppBundle\Mailer\NewMailer
      arguments: [@service_container]

  blob.storage:
      class: Application\DeskPRO\BlobStorage\DeskproBlobStorage
      factory_class: Application\DeskPRO\DependencyInjection\SystemServices\BlobStorageService
      factory_method: create
      arguments: [@service_container]