services:

  brand_stack:
    class: DeskPRO\Bundle\PortalBundle\Brand\BrandStack
    arguments: [@brand_container_factory, @default_brand]


  brand_container_factory:
    class: DeskPRO\Bundle\PortalBundle\Brand\BrandContainerFactory
    arguments:
      - @settings_resolver
      - @theme_resolver
      - @doctrine.orm.default_entity_manager
      - @deskpro.blob_storage
      - @portal_mode_storage


  default_brand_finder:
    class: DeskPRO\Bundle\PortalBundle\Brand\DefaultBrandFinder
    arguments: [@settings_resolver, @brand_repository]


  default_brand:
    class: Application\DeskPRO\Entity\Brand
    factory_service: default_brand_finder
    factory_method: getDefaultBrand


  person_factory:
    class: DeskPRO\Bundle\PortalBundle\Person\PersonFactory
    arguments: [@doctrine.orm.default_entity_manager, @event_dispatcher, @brand_stack, @language_stack, @user_rule_processor]
