services:

  form_saver:
    class: DeskPRO\Bundle\PortalBundle\SavedForm\FormSaver
    arguments:
      - @router
      - @doctrine.orm.default_entity_manager
      - @session

  listener.response.double_submit:
    class: DeskPRO\Bundle\PortalBundle\Form\EventListener\DoubleSubmitJavascriptListener
    tags:
      - { name: kernel.event_subscriber }

  listener.response.visitor_identifier_js:
    class: DeskPRO\Bundle\PortalBundle\Visitor\EventListener\VisitorIdentifierJavascriptListener
    tags:
      - { name: kernel.event_subscriber }

  listener.response.hit_track_js:
    class: DeskPRO\Bundle\AppBundle\HitTrack\EventListener\HitTrackJavascriptListener
    tags:
      - { name: kernel.event_subscriber }

  form.form_extension:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Extension\DeskproFormExtension
    tags:
      - { name: form.type_extension, alias: form }

  form.checkbox_extension:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Extension\DeskproCheckboxExtension
    tags:
      - { name: form.type_extension, alias: checkbox }

  form_extension.twig:
    class: DeskPRO\Bundle\PortalBundle\Form\Twig\FormTwigExtension
    tags:
      - { name: twig.extension }

  captcha_decider:
    class: DeskPRO\Bundle\PortalBundle\Form\Captcha\CaptchaDecider
    arguments: [@brand_stack, @security.authorization_checker, @security.token_storage, @request_stack, @anti_abuse]

  deskpro.validator.valid_recaptcha:
    class: DeskPRO\Bundle\PortalBundle\Form\Validator\Constraints\ValidRecaptcha2Validator
    arguments: [@brand_stack, @request_stack]
    tags:
      - { name: validator.constraint_validator, alias: valid_recaptcha2 }

  form.api.chat.set_person_listener:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\Api\Chat\EventListener\SetPersonListener
    arguments: [@email.email_account_manager, @doctrine.orm.default_entity_manager]

  #
  # Types
  #

  form.csrf_double_submit_extension:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\CsrfDoubleSubmitExtension
    arguments: [@request_stack, @language_manager, %kernel.environment%]
    tags:
      - { name: form.type_extension, alias: form }


  form.ticket_reply:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\TicketReplyType
    arguments: [@language_manager]
    tags:
      - { name: form.type, alias: ticket_reply }


  form.person_registration:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\PersonRegistrationType
    arguments: [@form_field_manager, @language_manager, @captcha_decider]
    tags:
      - { name: form.type, alias: person_registration }


  form.person_profile:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\PersonEditProfileType
    arguments: [@form_field_manager, @language_manager, @blob.storage, @doctrine.orm.default_entity_manager]
    tags:
      - { name: form.type, alias: person_profile }


  form.comment:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\CommentType
    tags:
      - { name: form.type, alias: comment }
    arguments:
      - @captcha_decider
      - @language_manager


  form.new_feedback:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\NewFeedbackType
    arguments: [@captcha_decider, @language_manager]
    tags:
      - { name: form.type, alias: new_feedback }

  form.custom_feedback_fields:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\CustomFeedbackType
    arguments: [@form_field_manager]
    tags:
      - { name: form.type, alias: custom_feedback_fields }


  form.feedback_attachment:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\FeedbackAttachmentType
    arguments: [@blob.storage, @blob_repository, @attachment_accepter]
    tags:
      - { name: form.type, alias: feedback_attachment }


  form.feedback_attachment_collection:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\FeedbackAttachmentCollectionType
    tags:
      - { name: form.type, alias: feedback_attachment_collection }


  form.feedback_category:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\FeedbackCategoryType
    tags:
      - { name: form.type, alias: feedback_category }


  form.request_password_reset:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\PasswordResetRequestType
    tags:
      - { name: form.type, alias: request_password_reset }
    arguments:
      - @captcha_decider


  form.person_change_password:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\PersonChangePasswordType
    tags:
      - { name: form.type, alias: person_change_password }
    arguments:
      - @captcha_decider
      - @deskpro.core.translate


  form.deskpro_custom_per_field_data:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\CustomPerFieldType
    arguments: [@tickets.custom_per_field_manager, @form_field_manager]
    tags:
      - { name: form.type, alias: deskpro_custom_per_field_data }


  form.custom_data_ticket:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\CustomDataTicketType
    arguments: [@form_field_manager, @doctrine.orm.default_entity_manager]
    tags:
      - { name: form.type, alias: deskpro_custom_data_ticket }


  form.custom_data_organization:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\CustomDataOrganizationType
    arguments: [@form_field_manager]
    tags:
      - { name: form.type, alias: deskpro_custom_data_organization }


  form.custom_data_feedback:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\CustomDataFeedbackType
    arguments: [@form_field_manager]
    tags:
      - { name: form.type, alias: deskpro_custom_data_feedback }


  form.ticket_message:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\TicketMessageType
    arguments: [@language_manager]
    tags:
      - { name: form.type, alias: ticket_message }


  form.custom_field_choice:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\CustomFieldChoiceType
    arguments: [@form_hierarchy_generator]
    tags:
      - { name: form.type, alias: deskpro_custom_field_choice }


  form.deskpro_contextual_per_field_choice:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\ContextualPerFieldChoiceType
    arguments: [@form_hierarchy_generator]
    tags:
      - { name: form.type, alias: deskpro_contextual_per_field_choice }


  form.language:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\LanguageType
    tags:
      - { name: form.type, alias: deskpro_language }


  form.display_html:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\DisplayHtmlType
    tags:
      - { name: form.type, alias: deskpro_display_html }


  form.hidden:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\HiddenType
    arguments: [@request_stack]
    tags:
      - { name: form.type, alias: deskpro_hidden }


  form.captcha:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\CaptchaType
    arguments: [@brand_stack, @language_manager]
    tags:
      - { name: form.type, alias: deskpro_captcha }


  form.recaptcha:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\ReCaptchaType
    arguments: [@brand_stack, @language_manager]
    tags:
      - { name: form.type, alias: deskpro_recaptcha }


  form.blob:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\BlobType
    arguments: [@doctrine.orm.default_entity_manager, @blob.storage, @blob_repository]
    tags:
      - { name: form.type, alias: deskpro_blob }


  form.date:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\DateType
    tags:
      - { name: form.type, alias: deskpro_date }


  form.datetime:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\DateTimeType
    tags:
      - { name: form.type, alias: deskpro_datetime }


  form.heirarchical_entity:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\HeirarchicalEntityType
    tags:
      - { name: form.type, alias: deskpro_heirarchical_entity }


  form.api.chat_create:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\Api\Chat\CreateChatType
    arguments: [@form.api.chat.set_person_listener, @user_chat.settings]
    tags:
      - { name: form.type, alias: api_chat_create }


  form.api.api_chat_validate_email:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\Api\Chat\ChatValidateEmailType
    tags:
      - { name: form.type, alias: api_chat_validate_email }


  form.api.chat_user_typing:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\Api\Chat\ChatUserTypingType
    tags:
      - { name: form.type, alias: api_chat_user_typing }


  form.api.chat_message:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\Api\Chat\ChatMessageType
    tags:
      - { name: form.type, alias: api_chat_message }


  form.api.chat_transcription_info:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\Api\Chat\ChatTranscriptInfoType
    arguments: [@form.api.chat.set_person_listener, @user_chat.settings]
    tags:
      - { name: form.type, alias: api_chat_transcription_info }


  form.api.chat_transcription_toggle:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\Api\Chat\ChatTranscriptToggleType
    tags:
      - { name: form.type, alias: api_chat_transcription_toggle }


  form.api.chat_feedback:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\Api\Chat\ChatFeedbackType
    tags:
      - { name: form.type, alias: api_chat_feedback }
