services:

  person_manipulator:
      class: DeskPRO\Bundle\PortalBundle\Person\PersonManipulator
      arguments: [@router, @security.token_storage]

  session.handler.dbal:
    class: DeskPRO\Bundle\PortalBundle\Session\DbalSessionHandler
    arguments: [@doctrine.dbal.default_connection, %portal.session.name%, @visitor_identification_provider, @security.token_storage]

  visitor_identification_provider:
    class: DeskPRO\Bundle\PortalBundle\Visitor\VisitorIdentificationProvider
    arguments: [@request_stack, @logger]

  pagerfanta.view.deskpro:
    class: DeskPRO\Bundle\PortalBundle\View\Pagerfanta\DeskproView
    public: false
    tags:
      - { name: pagerfanta.view, alias: deskpro }

  portal_mode_factory:
      class: DeskPRO\Bundle\PortalBundle\Mode\PortalModeFactory

  portal_mode_storage:
      class: DeskPRO\Bundle\PortalBundle\Mode\PortalModeStorage

  portal_search_serializer:
      class: DeskPRO\Bundle\PortalBundle\Search\SimplePortalEntitySerializer
      arguments: [@object_router, @icon_factory]

  attachment_accepter:
    class: Application\DeskPRO\Attachments\AcceptAttachment
    factory_class: Application\DeskPRO\DependencyInjection\SystemServices\AttachmentAccepterService
    factory_method: create
    arguments: [@service_container]
