imports:
    - { resource: ../config.shared.php }

# Keeping all parameter changes here rather than in various bundles
parameters:
  router.options.matcher.cache_class: null
  portal.session.name: sess_data
  doctrine.orm.proxy_dir: %kernel.cache_dir%/../../doctrine-proxies
  templating.globals.class: DeskPRO\Bundle\AppBundle\Twig\GlobalVariables
  monolog.logger.class: DeskPRO\Bundle\AppBundle\Logging\NoExceptionsLogger
  file_locator.class: DeskPRO\Bundle\AppBundle\HttpKernel\Config\FileLocator
  twig.class: DeskPRO\Bundle\PortalBundle\Twig\Environment

app:
  data_serializer:
    types:
        person:
          classes:
            - Application\DeskPRO\Entity\Person

framework:
    esi:             { enabled: true }
    fragments:       { path: /_proxy }
    #translator:      { fallback: "%locale%" }
    secret:          "irrelevant - compiler pass will override this"
    router:
        resource: "%kernel.root_dir%/config/portal/portal_routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: false }
    templating:
        engines: ['twig']
        assets_base_urls: "SET_IN_ASSET_PACKAGE_PASS"
        packages:
          app_assets: { base_url: "SET_IN_ASSET_PACKAGE_PASS" }
          vendor_assets: { base_url: "SET_IN_ASSET_PACKAGE_PASS" }
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies:
        - 127.0.0.1
    session:
        handler_id:      session.handler.dbal
        name:            dpsid
        cookie_httponly: true
    fragments:       ~
    http_method_override: true

monolog:
    channels: # you MUST also update api_config.yml if you change these
        - "dp.tickets.filters.tengine.dbal.engine"
        - "dp.tickets.filters.tengine.dbal.compiler"
        - "dp.tickets.filters.tengine.php.engine"
        - "dp.tickets.filters.tengine.php.compiler"
    handlers:
        main:
            type:   service
            id:     monolog.handler.deskpro_fingers_crossed

# FOSHttpCacheBundle
fos_http_cache:
    user_context:
        enabled: true
        user_identifier_headers: ['Cookie']
        hash_cache_ttl: 600 # only make the user-context-hash request once per 10 minute per GUEST w/ session


# Security Configuration
security:
    providers:
        dp_person_user_provider:
            id: dp_person_user_provider

    firewalls:
        portal:
            pattern: ^/
            provider: dp_person_user_provider
            agent_impersonate:
                failure_path: /login?retry=auth
                login_path: /impersonate/agent-login
                require_previous_session: false
                remember_me: false
                always_use_default_target_path: true
                default_target_path: /
                target_path_parameter: _destination
                use_referer: false
            transfer_session_auth:
                failure_path: /
                login_path: /
                require_previous_session: false
                remember_me: false
                always_use_default_target_path: true
                default_target_path: /
                target_path_parameter: _destination
                use_referer: false
            deskpro_form_login:
                failure_path: /login?retry=auth
                login_path: /login
                use_forward: false
                require_previous_session: false
                remember_me: true
                default_target_path: /
                target_path_parameter: _destination
                use_referer: true
            anonymous:
                key:    "irrelevant - compiler pass will override this"
            logout:
                path: portal_logout
                target: /
                invalidate_session: true
                handlers:  [security.authentication.logout_handler]
            remember_me:
                key:      "irrelevant - compiler pass will override this"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # the current domain from $_SERVER
                remember_me_parameter: remember_me


# Twig Configuration
twig:
    exception_controller:  PortalBundle:Error:showException
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - Theme::form_theme.html.twig

sensio_framework_extra:
    cache:    { annotations: true }
    security:    { annotations: true }

white_october_pagerfanta:
    default_view: deskpro
    exceptions_strategy:
        out_of_range_page:        to_http_not_found
        not_valid_current_page:   to_http_not_found

jms_serializer:
    metadata:
        cache: none

gregwar_captcha: ~

nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
    paths:
        '^/portal/api/':
            allow_origin: ['*']
            allow_headers: ['X-Agent-Request', 'Content-Type']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
