imports:
  - { resource: portal_config_dev.yml }

framework:
    profiler: { only_exceptions: false }
    router:
        resource: "%kernel.root_dir%/config/portal_routing_dev.yml"
        strict_requirements: true

web_profiler:
    toolbar: true
    intercept_redirects: false
