portal_routes:
    resource: "@PortalBundle/Resources/config/routing_portal.yml"
auth_routes:
    resource: "@AuthBundle/Resources/config/routing_auth.yml"
dp_routes:
    resource: "@DeskPRO/Resources/config/dp-routing.php"
agent_routes:
    resource: "@AgentBundle/Resources/config/agent-routing.php"