imports:
    - { resource: config.shared.php }
    - { resource: @PortalBundle/Resources/config/portal_services.yml }

parameters:
    doctrine.orm.proxy_dir: %kernel.cache_dir%/../../doctrine-proxies

framework:
    esi:             ~
    fragments:       { path: /_proxy }
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/portal_routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: false }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  session.handler.dbal
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

sensio_framework_extra:
    cache:    { annotations: true }

white_october_pagerfanta:
    exceptions_strategy:
        out_of_range_page:        to_http_not_found
        not_valid_current_page:   to_http_not_found