<?php
// Empty implementations of term objects as we build up crud

namespace Application\DeskPRO\Tickets\Actions;
use Application\DeskPRO\Entity\Ticket;
use Application\DeskPRO\Entity\Person;
use Application\DeskPRO\Tickets\ExecutorContext;

class SetAgent                                 extends AbstractAction { public function applyAction(Ticket $ticket, ExecutorContext $context) { } public function getMacroPermissionErrors(Person $person, Ticket $ticket, ExecutorContext $context) { return array(); } public function applyMacro(Person $person, Ticket $ticket, ExecutorContext $context) {} }
class SetAgentTeam                             extends AbstractAction { public function applyAction(Ticket $ticket, ExecutorContext $context) { } public function getMacroPermissionErrors(Person $person, Ticket $ticket, ExecutorContext $context) { return array(); } public function applyMacro(Person $person, Ticket $ticket, ExecutorContext $context) {} }
class SetAgentFollowers                        extends AbstractAction { public function applyAction(Ticket $ticket, ExecutorContext $context) { } public function getMacroPermissionErrors(Person $person, Ticket $ticket, ExecutorContext $context) { return array(); } public function applyMacro(Person $person, Ticket $ticket, ExecutorContext $context) {} }
class SetDepartment                            extends AbstractAction { public function applyAction(Ticket $ticket, ExecutorContext $context) { } public function getMacroPermissionErrors(Person $person, Ticket $ticket, ExecutorContext $context) { return array(); } public function applyMacro(Person $person, Ticket $ticket, ExecutorContext $context) {} }
class SetProduct                               extends AbstractAction { public function applyAction(Ticket $ticket, ExecutorContext $context) { } public function getMacroPermissionErrors(Person $person, Ticket $ticket, ExecutorContext $context) { return array(); } public function applyMacro(Person $person, Ticket $ticket, ExecutorContext $context) {} }
class SetCategory                              extends AbstractAction { public function applyAction(Ticket $ticket, ExecutorContext $context) { } public function getMacroPermissionErrors(Person $person, Ticket $ticket, ExecutorContext $context) { return array(); } public function applyMacro(Person $person, Ticket $ticket, ExecutorContext $context) {} }
class SetPriority                              extends AbstractAction { public function applyAction(Ticket $ticket, ExecutorContext $context) { } public function getMacroPermissionErrors(Person $person, Ticket $ticket, ExecutorContext $context) { return array(); } public function applyMacro(Person $person, Ticket $ticket, ExecutorContext $context) {} }
class SetWorkflow                              extends AbstractAction { public function applyAction(Ticket $ticket, ExecutorContext $context) { } public function getMacroPermissionErrors(Person $person, Ticket $ticket, ExecutorContext $context) { return array(); } public function applyMacro(Person $person, Ticket $ticket, ExecutorContext $context) {} }
class SetUrgency                               extends AbstractAction { public function applyAction(Ticket $ticket, ExecutorContext $context) { } public function getMacroPermissionErrors(Person $person, Ticket $ticket, ExecutorContext $context) { return array(); } public function applyMacro(Person $person, Ticket $ticket, ExecutorContext $context) {} }
class SetSubject                               extends AbstractAction { public function applyAction(Ticket $ticket, ExecutorContext $context) { } public function getMacroPermissionErrors(Person $person, Ticket $ticket, ExecutorContext $context) { return array(); } public function applyMacro(Person $person, Ticket $ticket, ExecutorContext $context) {} }
class SetLabels                                extends AbstractAction { public function applyAction(Ticket $ticket, ExecutorContext $context) { } public function getMacroPermissionErrors(Person $person, Ticket $ticket, ExecutorContext $context) { return array(); } public function applyMacro(Person $person, Ticket $ticket, ExecutorContext $context) {} }
class SetFlag                                  extends AbstractAction { public function applyAction(Ticket $ticket, ExecutorContext $context) { } public function getMacroPermissionErrors(Person $person, Ticket $ticket, ExecutorContext $context) { return array(); } public function applyMacro(Person $person, Ticket $ticket, ExecutorContext $context) {} }
class SetEmailAccount                          extends AbstractAction { public function applyAction(Ticket $ticket, ExecutorContext $context) { } public function getMacroPermissionErrors(Person $person, Ticket $ticket, ExecutorContext $context) { return array(); } public function applyMacro(Person $person, Ticket $ticket, ExecutorContext $context) {} }
class SetCcUsers                               extends AbstractAction { public function applyAction(Ticket $ticket, ExecutorContext $context) { } public function getMacroPermissionErrors(Person $person, Ticket $ticket, ExecutorContext $context) { return array(); } public function applyMacro(Person $person, Ticket $ticket, ExecutorContext $context) {} }
class SetSlas                                  extends AbstractAction { public function applyAction(Ticket $ticket, ExecutorContext $context) { } public function getMacroPermissionErrors(Person $person, Ticket $ticket, ExecutorContext $context) { return array(); } public function applyMacro(Person $person, Ticket $ticket, ExecutorContext $context) {} }
class SetSlaStatus                             extends AbstractAction { public function applyAction(Ticket $ticket, ExecutorContext $context) { } public function getMacroPermissionErrors(Person $person, Ticket $ticket, ExecutorContext $context) { return array(); } public function applyMacro(Person $person, Ticket $ticket, ExecutorContext $context) {} }
class SetSlaRequirements                       extends AbstractAction { public function applyAction(Ticket $ticket, ExecutorContext $context) { } public function getMacroPermissionErrors(Person $person, Ticket $ticket, ExecutorContext $context) { return array(); } public function applyMacro(Person $person, Ticket $ticket, ExecutorContext $context) {} }
class ChangeUser                               extends AbstractAction { public function applyAction(Ticket $ticket, ExecutorContext $context) { } public function getMacroPermissionErrors(Person $person, Ticket $ticket, ExecutorContext $context) { return array(); } public function applyMacro(Person $person, Ticket $ticket, ExecutorContext $context) {} }
class DeleteTicket                             extends AbstractAction { public function applyAction(Ticket $ticket, ExecutorContext $context) { } public function getMacroPermissionErrors(Person $person, Ticket $ticket, ExecutorContext $context) { return array(); } public function applyMacro(Person $person, Ticket $ticket, ExecutorContext $context) {} }
class AddAgentReply                            extends AbstractAction { public function applyAction(Ticket $ticket, ExecutorContext $context) { } public function getMacroPermissionErrors(Person $person, Ticket $ticket, ExecutorContext $context) { return array(); } public function applyMacro(Person $person, Ticket $ticket, ExecutorContext $context) {} }
class ModForceEmailValidation                  extends AbstractAction { public function applyAction(Ticket $ticket, ExecutorContext $context) { } public function getMacroPermissionErrors(Person $person, Ticket $ticket, ExecutorContext $context) { return array(); } public function applyMacro(Person $person, Ticket $ticket, ExecutorContext $context) {} }
class SendUserEmail                            extends AbstractAction { public function applyAction(Ticket $ticket, ExecutorContext $context) { } public function getMacroPermissionErrors(Person $person, Ticket $ticket, ExecutorContext $context) { return array(); } public function applyMacro(Person $person, Ticket $ticket, ExecutorContext $context) {} }
class SendAgentEmail                           extends AbstractAction { public function applyAction(Ticket $ticket, ExecutorContext $context) { } public function getMacroPermissionErrors(Person $person, Ticket $ticket, ExecutorContext $context) { return array(); } public function applyMacro(Person $person, Ticket $ticket, ExecutorContext $context) {} }
class ModStopTriggers                          extends AbstractAction { public function applyAction(Ticket $ticket, ExecutorContext $context) { } public function getMacroPermissionErrors(Person $person, Ticket $ticket, ExecutorContext $context) { return array(); } public function applyMacro(Person $person, Ticket $ticket, ExecutorContext $context) {} }
class ModQuietUserEmails                       extends AbstractAction { public function applyAction(Ticket $ticket, ExecutorContext $context) { } public function getMacroPermissionErrors(Person $person, Ticket $ticket, ExecutorContext $context) { return array(); } public function applyMacro(Person $person, Ticket $ticket, ExecutorContext $context) {} }
class ModQuietAgentEmails                      extends AbstractAction { public function applyAction(Ticket $ticket, ExecutorContext $context) { } public function getMacroPermissionErrors(Person $person, Ticket $ticket, ExecutorContext $context) { return array(); } public function applyMacro(Person $person, Ticket $ticket, ExecutorContext $context) {} }
