// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['Admin/Main/Ctrl/Base', 'Admin/App'], function(Admin_Ctrl_Base) {
    var Admin_TicketDeps_Ctrl_Edit, _ref;
    Admin_TicketDeps_Ctrl_Edit = (function(_super) {
      __extends(Admin_TicketDeps_Ctrl_Edit, _super);

      function Admin_TicketDeps_Ctrl_Edit() {
        _ref = Admin_TicketDeps_Ctrl_Edit.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Admin_TicketDeps_Ctrl_Edit.CTRL_ID = 'Admin_TicketDeps_Ctrl_Edit';

      Admin_TicketDeps_Ctrl_Edit.CTRL_AS = 'TicketDepsEdit';

      Admin_TicketDeps_Ctrl_Edit.CTRL_TYPE = 'page';

      Admin_TicketDeps_Ctrl_Edit.DEPS = ['em', '$scope', 'DepartmentData', 'Api', '$stateParams', '$q', '$state'];

      Admin_TicketDeps_Ctrl_Edit.prototype.init = function() {
        var _this = this;
        return this.addManagedListener(this.DepartmentData.deps, 'changed', function() {
          _this.initDeplistData(_this.DepartmentData.deps);
          return _this.ngApply();
        });
      };

      Admin_TicketDeps_Ctrl_Edit.prototype.initialLoad = function() {
        return this.loadDepartment();
      };

      /**
      		# Load (or reload) the page values
      */


      Admin_TicketDeps_Ctrl_Edit.prototype.loadDepartment = function() {
        var promise, waiting,
          _this = this;
        waiting = [this.DepartmentData.loadDepList(), this.$stateParams.id ? this.Api.sendDataGet(['/ticket_deps/' + this.$stateParams.id, '/agents', '/agentgroups', '/usergroups', '/ticket_accounts']) : this.Api.sendDataGet(['/agents', '/agentgroups', '/usergroups', '/ticket_accounts'])];
        promise = this.$q.all(waiting).then(function(d) {
          var data_results, dep, dep_data, departments;
          departments = d[0], data_results = d[1];
          if (_this.$stateParams.id) {
            dep_data = data_results.data.api_ticket_deps_get;
          } else {
            dep_data = {
              department: {},
              perms_usergroup_ids: [],
              perms_agentgroup_ids: [],
              perms_agent_ids: []
            };
          }
          dep = dep_data.department;
          if (!dep.parent_id) {
            dep.parent_id = 0;
          }
          _this.dep = _this.em.createUnmanagedEntity('department', 'id', dep);
          _this.initDeplistData(departments);
          return _this.initData({
            usergroups: dep_data.perms_usergroup_ids,
            agentgroups: dep_data.perms_agentgroup_ids,
            agents: dep_data.perms_agent_ids
          }, data_results.data.api_agents_list.agents, data_results.data.api_agentgroups_list.agentgroups, data_results.data.api_usergroups_list.usergroups);
        });
        return promise;
      };

      /**
      		# Init data from loadDepartment, getting it ready for use
      */


      Admin_TicketDeps_Ctrl_Edit.prototype.initData = function(department_perms, agents, agentgroups, usergroups) {
        var ag, perm, ug, _i, _j, _k, _l, _len, _len1, _len2, _len3, _len4, _m, _ref1, _ref2, _ref3, _ref4, _ref5, _results;
        this.agentgroups = agentgroups;
        _ref1 = this.agentgroups;
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          ug = _ref1[_i];
          _ref2 = department_perms.agentgroups;
          for (_j = 0, _len1 = _ref2.length; _j < _len1; _j++) {
            perm = _ref2[_j];
            if (perm.usergroup_id === ug.id) {
              ug[perm.perm_name] = true;
            }
          }
        }
        this.usergroups = usergroups;
        _ref3 = this.usergroups;
        for (_k = 0, _len2 = _ref3.length; _k < _len2; _k++) {
          ug = _ref3[_k];
          _ref4 = department_perms.usergroups;
          for (_l = 0, _len3 = _ref4.length; _l < _len3; _l++) {
            perm = _ref4[_l];
            if (perm.usergroup_id === ug.id) {
              ug[perm.perm_name] = true;
            }
          }
        }
        this.agents = agents;
        _ref5 = this.agents;
        _results = [];
        for (_m = 0, _len4 = _ref5.length; _m < _len4; _m++) {
          ag = _ref5[_m];
          _results.push((function() {
            var _len5, _n, _ref6, _results1;
            _ref6 = department_perms.agents;
            _results1 = [];
            for (_n = 0, _len5 = _ref6.length; _n < _len5; _n++) {
              perm = _ref6[_n];
              if (perm.agent_id === ag.id) {
                _results1.push(ag[perm.perm_name] = true);
              } else {
                _results1.push(void 0);
              }
            }
            return _results1;
          })());
        }
        return _results;
      };

      Admin_TicketDeps_Ctrl_Edit.prototype.initDeplistData = function(departments) {
        var dep, _i, _len, _ref1, _results;
        this.departments = departments.values();
        if (!this.dep) {
          return;
        }
        this.dep_parent_list = departments.values();
        this.dep_parent_list = [
          {
            id: 0,
            title: 'No Parent'
          }
        ];
        _ref1 = this.departments;
        _results = [];
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          dep = _ref1[_i];
          if (this.dep.id !== dep.id && !dep.parent_id) {
            _results.push(this.dep_parent_list.push(dep));
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      };

      /**
      		# Save everything
      */


      Admin_TicketDeps_Ctrl_Edit.prototype.saveAll = function() {
        var full_title, is_new, model, parent, postData, promise,
          _this = this;
        postData = {
          properties: this.getPropsData(),
          permissions: this.getPermsData()
        };
        if (this.dep.id) {
          is_new = false;
          promise = this.Api.sendPostJson('/ticket_deps/' + this.dep.id, postData);
        } else {
          is_new = true;
          promise = this.Api.sendPostJson('/ticket_deps/create', postData);
        }
        if (this.dep.parent_id && this.dep.parent_id !== "0") {
          parent = this.DepartmentData.deps.get(this.dep.parent_id);
          full_title = parent.title + ' > ' + this.dep.title;
        } else {
          full_title = this.dep.title;
        }
        if (this.em.hasById('department', this.dep.id)) {
          model = this.em.getById('department', this.dep.id);
          model.title = this.dep.title;
          model._full_title = full_title;
          model.user_title = this.dep.user_title;
        } else {
          promise.success(function(result) {
            _this.dep.id = result.id;
            model = _this.em.createEntity('department', 'id', _this.dep.getData());
            model._full_title = full_title;
            if (!model.parent_id || model.parent_id === "0") {
              model.parent_id = null;
            }
            _this.DepartmentData.addToList(model);
            _this.initDeplistData(_this.DepartmentData.deps);
            if (is_new) {
              return _this.$state.go('tickets.ticket_deps.gocreate');
            } else {
              return _this.$state.go('tickets.ticket_deps');
            }
          });
        }
        return promise;
      };

      /**
      		# Gets property data
      */


      Admin_TicketDeps_Ctrl_Edit.prototype.getPropsData = function() {
        return this.dep.getData();
      };

      /**
      		# Gets permission data that can be posted for saving
      */


      Admin_TicketDeps_Ctrl_Edit.prototype.getPermsData = function(type) {
        var agent, agentgroup, perms, usergroup, _i, _j, _k, _len, _len1, _len2, _ref1, _ref2, _ref3;
        if (type == null) {
          type = 'all';
        }
        perms = {};
        if (type === 'all' || type === 'agents') {
          perms.agents = [];
          _ref1 = this.agents;
          for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
            agent = _ref1[_i];
            if (agent.full) {
              perms.agents.push({
                agent_id: agent.id,
                perm_name: 'full'
              });
            } else if (agent.assign) {
              perms.agents.push({
                agent_id: agent.id,
                perm_name: 'assign'
              });
            }
          }
        }
        if (type === 'all' || type === 'agentgroups') {
          perms.agentgroups = [];
          _ref2 = this.agentgroups;
          for (_j = 0, _len1 = _ref2.length; _j < _len1; _j++) {
            agentgroup = _ref2[_j];
            if (agentgroup.full) {
              perms.agentgroups.push({
                usergroup_id: agentgroup.id,
                perm_name: 'full'
              });
            } else if (agentgroup.assign) {
              perms.agentgroups.push({
                usergroup_id: agentgroup.id,
                perm_name: 'assign'
              });
            }
          }
        }
        if (type === 'all' || type === 'usergroups') {
          perms.usergroups = [];
          _ref3 = this.usergroups;
          for (_k = 0, _len2 = _ref3.length; _k < _len2; _k++) {
            usergroup = _ref3[_k];
            if (usergroup.use) {
              perms.usergroups.push({
                usergroup_id: usergroup.id,
                perm_name: 'use'
              });
            }
          }
        }
        return perms;
      };

      return Admin_TicketDeps_Ctrl_Edit;

    })(Admin_Ctrl_Base);
    return Admin_TicketDeps_Ctrl_Edit.EXPORT_CTRL();
  });

}).call(this);

/*
//@ sourceMappingURL=Edit.map
*/
