// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['Admin/Main/Ctrl/Base', 'Admin/App'], function(Admin_Ctrl_Base) {
    var Admin_TicketDeps_Ctrl_Edit, _ref;
    Admin_TicketDeps_Ctrl_Edit = (function(_super) {
      __extends(Admin_TicketDeps_Ctrl_Edit, _super);

      function Admin_TicketDeps_Ctrl_Edit() {
        _ref = Admin_TicketDeps_Ctrl_Edit.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Admin_TicketDeps_Ctrl_Edit.CTRL_ID = 'Admin_TicketDeps_Ctrl_Edit';

      Admin_TicketDeps_Ctrl_Edit.CTRL_AS = 'TicketDepsEdit';

      Admin_TicketDeps_Ctrl_Edit.DEPS = ['$scope', 'DepartmentData', 'Api', '$stateParams'];

      Admin_TicketDeps_Ctrl_Edit.prototype.init = function() {
        var _this = this;
        this.deps_list = this.DepartmentData.deps.values();
        return this.Api.sendDataGet(['/ticket_deps/' + this.$stateParams.id, '/agents', '/agentgroups', '/usergroups', '/ticket_accounts']).success(function(data) {
          _this.dep = data.api_ticket_deps_get.department;
          return _this.agents = data.api_agents_list;
        });
      };

      Admin_TicketDeps_Ctrl_Edit.prototype.saveDep = function() {
        var model;
        this.Api.sendPost('/ticket_deps/' + this.dep.id, {
          title: this.dep.title,
          user_title: this.dep.user_title
        });
        model = this.DepartmentData.deps.get(this.dep.id);
        model.title = this.dep.title;
        model.user_title = this.dep.user_title;
        return this.ngApply();
      };

      return Admin_TicketDeps_Ctrl_Edit;

    })(Admin_Ctrl_Base);
    return Admin_TicketDeps_Ctrl_Edit.EXPORT_CTRL();
  });

}).call(this);

/*
//@ sourceMappingURL=Edit.map
*/
