requirejs.config({
	"baseUrl":     DP_ASSET_URL,
	"waitSeconds": 60,
	"urlArgs":    (DP_IS_DEBUG ? "bust=" + (new Date()).getTime() : "v=" + (DP_BUILD_TIME || "0")),
	"paths": {
		"angular":                         "bower_components/angular/angular.min",
"angularRoute":                    "bower_components/angular-route/angular-route.min",
"angularAnimate":                  "bower_components/angular-animate/angular-animate.min",
"angularBootstrap":                "bower_components/angular-bootstrap/ui-bootstrap-tpls.min",
"angularSanitize":                 "bower_components/angular-sanitize/angular-sanitize.min",
"angularSelect2":                  "bower_components/angular-ui-select2/src/select2",
"angularUiAce":                    "bower_components/angular-ui-ace/ui-ace",
"angularUiRouter":                 "bower_components/angular-ui-router/release/angular-ui-router.min",
"angularUiSortable":               "bower_components/angular-ui-sortable/src/sortable",
"angular-moment":                  "bower_components/angular-moment/angular-moment",
"angularFileUpload":               "bower_components/blueimp-file-upload/js/jquery.fileupload-angular",
"angularSlider":                   "bower_components/angular-slider/slider",
"angularSelectize":                "bower_components/angular-selectize.js/angular-selectize",
"angularGrid":                     "bower_components/angular-grid/build/ng-grid.min",
"angularUiDatetime":               "vendor/ui-datetime",

"ngFileUpload":                    "bower_components/ng-file-upload/angular-file-upload.min",
"ngContextMenu":                   "vendor/ng-context-menu/src/ng-context-menu",
"jquery":                          "bower_components/jquery/dist/jquery.min",
"jqueryUi":                        "bower_components/jquery-ui/ui/minified/jquery-ui.min",
"jquery.ui.widget":                "bower_components/blueimp-file-upload/js/vendor/jquery.ui.widget",
"jquery.fileupload":               "bower_components/blueimp-file-upload/js/jquery.fileupload",
"jquery.fileupload-process":       "bower_components/blueimp-file-upload/js/jquery.fileupload-process",
"jquery.fileupload-image":         "bower_components/blueimp-file-upload/js/jquery.fileupload-image",
"jquery.fileupload-audio":         "bower_components/blueimp-file-upload/js/jquery.fileupload-audio",
"jquery.fileupload-video":         "bower_components/blueimp-file-upload/js/jquery.fileupload-video",
"jquery.fileupload-validate":      "bower_components/blueimp-file-upload/js/jquery.fileupload-validate",
"load-image":                      "bower_components/blueimp-load-image/js/load-image",
"load-image-meta":                 "bower_components/blueimp-load-image/js/load-image-meta",
"load-image-ios":                  "bower_components/blueimp-load-image/js/load-image-ios",
"load-image-exif":                 "bower_components/blueimp-load-image/js/load-image-exif",
"canvas-to-blob":                  "bower_components/blueimp-canvas-to-blob/js/canvas-to-blob.min",
"underscore":                      "bower_components/underscore/underscore-min",
"momentTimezone":                  "vendor/moment-timezone",
"moment":                          "bower_components/moment/min/moment-with-langs.min",
"aceEditor":                       "bower_components/ace-builds/src-min-noconflict/ace",
"stacktrace":                      "bower_components/stacktrace/stacktrace",
"bootstrapModal":                  "bower_components/bootstrap/js/modal",
"bootstrapTooltip":                "bower_components/bootstrap/js/tooltip",
"select2":                         "bower_components/select2/select2.min",
"toastr":                          "bower_components/toastr/toastr",
"ColorPicker":                     "vendor/colorpicker/js/colorpicker.min",
"jstz":                            "vendor/detect_timezone",
"intl-tel-input":                  "bower_components/intl-tel-input/build/js/intlTelInput.min",
"redactor":                        "vendor/redactor/redactor.min",

"selectize":                       "bower_components/selectize/dist/js/selectize",
"sifter":                          "bower_components/sifter/sifter",
"microplugin":                     "bower_components/microplugin/src/microplugin",

"ZeroClipboard":                   "bower_components/zeroclipboard/dist/ZeroClipboard",
"ngClip":                          "bower_components/ng-clip/src/ngClip",

"AdminLoad":                       "app/Admin/AdminLoad",
"CloudAdminLoad":                  "app/Admin/Cloud/CloudAdminLoad",
"AdminUpgradeLoad":                "app/AdminUpgrade/AdminUpgradeLoad",
"AdminStartLoad":                  "app/AdminStart/AdminStartLoad",
"ReportsLoad":                     "app/Reports/ReportsLoad",

"DeskPRO":                         "app-build/DeskPRO",
"Admin":                           "app-build/Admin",
"AdminRouting":                    "app/Admin/Resources/config/routing",
"AdminUpgrade":                    "app-build/AdminUpgrade",
"AdminStart":                      "app-build/AdminStart",
"Reports":                         "app-build/Reports",
"ReportsRouting":                  "app/Reports/Resources/config/routing"
	},
	"shims": {
		"angular":                         {"exports" : "angular", "deps": ["jquery"]},
"angularAnimate":                  ["angular"],
"angularBootstrap":                ["angular"],
"angularSanitize":                 ["angular"],
"angularSelect2":                  ["angular", "select2"],
"angularUiAce":                    ["angular"],
"angularUiRouter":                 ["angular"],
"angularUiSortable":               ["angular"],
"angular-moment":                   ["angular", "moment"],
"angularFileUpload":               ["jquery"],
"angularSlider":                   ["angular"],
"angularGrid":                     ["angular"],
"ngFileUpload":                    ["angular"],
"ngContextMenu":                   ["angular"],
"jquery":                          { "exports": "jquery" },
"jqueryUi":                        ["jquery"],
"bootstrapModal":                  ["jquery"],
"bootstrapTooltip":                ["jquery", "jqueryUi"],
"select2":                         ["jquery"],
"toastr":                          ["jquery"],
"ColorPicker":                     ["jquery"],
"underscore":                      { "exports": "_" },
"stacktrace":                      { "exports": "printStackTrace"},
"trackjs":                         { "exports": "trackJs"},
"intl-tel-input":                  ["jquery"]
	},
	"priority": [
		"jquery",
		"angular"
	]
});
