imports:
    - { resource: config.yml }

parameters:
    kernel.debug: true

web.config:
    toolbar: true

twig.config:
  auto_reload: true

zend.logger:
    priority: debug
    path:     %kernel.root_dir%/logs/%kernel.environment%.log
