parameters:
    kernel.include_core_classes: false

kernel.config:
  error_handler_level: null

web.config:
  router: { resource: "%kernel.root_dir%/config/routing.yml" }

web.templating:
  escaping: htmlspecialchars

doctrine.orm: ~
doctrine.dbal:
  driver: PDOMySql
  dbname: dp_400
  user: root
  password: mysquirrel