parameters:
    kernel.include_core_classes: false
    templating.engine.class: "DeskPRO\Templating\Engine"

kernel.config:
  error_handler_level: null

web.config:
  router: { resource: "%kernel.root_dir%/config/routing.yml" }

web.templating:
  escaping: htmlspecialchars

doctrine.orm:
  auto_generate_proxy_classes: true

doctrine.dbal:
  driver: PDOMySql
  dbname: dp_400
  user: root
  password: mysquirrel

deskpro_core.config: ~
deskpro_tech_core.config: ~
deskpro_requestuser.config: ~