deskpro:
  resource: "%DP_ROOT%/src/Application/DeskPRO/Resources/config/routing.php"

user:
  resource: "%DP_ROOT%/src/Application/UserBundle/Resources/config/routing.php"

agent:
  prefix: /agent
  resource: "%DP_ROOT%/src/Application/AgentBundle/Resources/config/routing.php"
