// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['Admin/Main/DataService/Base', 'Admin/Main/Model/Base', 'Admin/Main/Collection/OrderedDictionary'], function(Admin_Main_DataService_Base, Admin_Main_Model_Base, Admin_Main_Collection_OrderedDictionary) {
    var Admin_Main_DataService_Departments;
    return Admin_Main_DataService_Departments = (function(_super) {
      __extends(Admin_Main_DataService_Departments, _super);

      function Admin_Main_DataService_Departments(Api, $q) {
        Admin_Main_DataService_Departments.__super__.constructor.call(this);
        this.$q = $q;
        this.Api = Api;
        this.deps = null;
        this.default_dep = null;
      }

      Admin_Main_DataService_Departments.prototype.loadDepList = function() {
        var deferred, http_def,
          _this = this;
        deferred = this.$q.defer();
        http_def = this.Api.sendGet('/ticket_deps').success(function(data, status, headers, config) {
          var dep, model, _i, _len, _ref;
          _this.deps = new Admin_Main_Collection_OrderedDictionary();
          _ref = data.departments;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            dep = _ref[_i];
            model = new Admin_Main_Model_Base();
            model.setData(dep);
            _this.deps.set(model.id, model);
          }
          _this.default_dep = new Admin_Main_Model_Base();
          _this.default_dep.default_id = data.default_id;
          return deferred.resolve(_this.deps, _this.default_dep);
        }, function(data, status, headers, config) {
          return deferred.reject();
        });
        return deferred.promise;
      };

      Admin_Main_DataService_Departments.prototype._cleanup = function() {
        this.deps = null;
      };

      return Admin_Main_DataService_Departments;

    })(Admin_Main_DataService_Base);
  });

}).call(this);

/*
//@ sourceMappingURL=Departments.map
*/
