parameters:
  kernel.include_core_classes: false
  http_kernel.class: "Application\DeskPRO\HttpKernel\HttpKernel"
  controller_resolver.class: "Application\DeskPRO\HttpKernel\Controller\ControllerResolver"
  session.class: "Application\DeskPRO\HttpFoundation\Session"
  swiftmailer.class: "Application\DeskPRO\Mail\Mailer"
  #exception_listener.class: "Application\DeskPRO\Debug\ExceptionListener"
  twig.loader.class: "Application\DeskPRO\Twig\\Loader\HybridLoader"
  file_locator.class: "Application\DeskPRO\HttpKernel\Config\FileLocator"
  routing.file_locator.class: "Application\DeskPRO\HttpKernel\Config\FileLocator"
  router.options.generator_class: "Application\DeskPRO\Routing\Generator\UrlGenerator"
  router.options.generator_base_class: "Application\DeskPRO\Routing\Generator\UrlGenerator"
  templating.globals.class: "Application\DeskPRO\Templating\GlobalVariables"

services:
  templating.engine.jsonphp:
    class: Orb\Templating\Engine\PhpVarJsonEngine
    arguments: [@templating.name_parser, @service_container, @templating.loader, @templating.globals]
    tags:
      - { name: templating.engine, alias: jsonphp }
  twig.helpers.deskpro_templating:
    class: Application\DeskPRO\Twig\Extension\TemplatingExtension
    arguments: [@service_container]
    tags:
      - { name: twig.extension }
  session.storage:
    class: Application\DeskPRO\HttpFoundation\SessionStorage\SessionEntityStorage
    arguments: [@doctrine.orm.entity_manager, %session.storage.options%]
  swiftmailer.transport.dp_delegating:
    class: Application\DeskPRO\Mail\Transport\DelegatingTransport
    arguments: [@swiftmailer.transport.eventdispatcher]
  doctrine.dbal.connection_factory:
    class: Application\DeskPRO\DBAL\ConnectionFactory
    arguments: [[], @service_container]

framework:
  charset: UTF-8
#  profiler: { only_exceptions: false }
  secret: mube224etsmhxky1gvwixc4b
  templating:
    engines: ['twig', 'php', 'jsonphp']
    assets_base_urls: "/dp_400/static/" # replace with your real basepath
  validation:
    enabled: true
  session:
    default_locale: en
    lifetime: 3600
    auto_start: true

doctrine:
  orm:
    auto_generate_proxy_classes: false
    default_entity_manager: default
    entity_managers:
      default:
          mappings:
            DeskPRO: ~
  dbal:
    default_connection: default
    connections:
      default:
        host: 'from_user_config.db'
        logging: true

swiftmailer:
  transport: 'dp_delegating'

deskpro_cache:
  common: ~

deskpro_core: ~
deskpro_elastica: ~