parameters:
    kernel.include_core_classes: false
    templating.engine.delegating.class: "Application\DeskPRO\Templating\DelegatingEngine"
    http_kernel.class: "Application\DeskPRO\HttpKernel\HttpKernel"
    controller_resolver.class: "Application\DeskPRO\HttpKernel\Controller\ControllerResolver"
    session.class: "Application\DeskPRO\HttpFoundation\Session"

services:
  templating.engine.jsonphp:
    class: Orb\Templating\Engine\PhpVarJsonEngine
    arguments: [@templating.loader]
    tags:
      - { name: templating.engine, alias: jsonphp }

app.config:
  charset: UTF-8
  router: { resource: "%kernel.root_dir%/config/routing.yml" }
#  profiler: { only_exceptions: false }
  templating:
    escaping: htmlspecialchars
    assets_base_urls: "/dp_400/static/" # replace with your real basepath
  validation:
    enabled: true

doctrine.orm:
  auto_generate_proxy_classes: %kernel.debug%
  mappings:
    DeskPRO: ~

doctrine.dbal:
  dp_from_user_config: db
  wrapper_class: "Application\DeskPRO\DBAL\Connection"

deskpro_cache.caches:
  phrases: ~

deskpro_core.config: ~
deskpro_agent_core.config: ~
deskpro_api_core.config: ~
