parameters:
  kernel.include_core_classes: false
  http_kernel.class: "Application\DeskPRO\HttpKernel\HttpKernel"
  controller_resolver.class: "Application\DeskPRO\HttpKernel\Controller\ControllerResolver"
  session.class: "Application\DeskPRO\HttpFoundation\Session"
  swiftmailer.class: "Application\DeskPRO\Mail\Mailer"
  twig.loader.class: "Application\DeskPRO\Twig\\Loader\\HybridLoader"
  twig.class: "Application\DeskPRO\Twig\Environment"
  file_locator.class: "Application\DeskPRO\HttpKernel\Config\FileLocator"
  routing.file_locator.class: "Application\DeskPRO\HttpKernel\Config\FileLocator"
  router.options.generator_class: "Application\DeskPRO\Routing\Generator\UrlGenerator"
  router.options.generator_base_class: "Application\DeskPRO\Routing\Generator\UrlGenerator"
  templating.globals.class: "Application\DeskPRO\Templating\GlobalVariables"
  templating.asset.url_package.class: "Application\DeskPRO\\Templating\Asset\UrlPackage"
  router.class: "Application\\DeskPRO\\Routing\\Router"
  router.options.generator_dumper_class: "Application\DeskPRO\Routing\Generator\Dumper\\PhpGeneratorDumper"
  router.options.generator_class: "Application\DeskPRO\\Routing\Generator\UrlGenerator"
  router.options.generator_base_class: "Application\DeskPRO\\Routing\Generator\UrlGenerator"
  doctrine.data_collector.class: Application\DeskPRO\Profiler\DataCollector\DoctrineDataCollector
  profiler.storage.dsn: "mysql:host=slinky;dbname=deskpro_dev"
  profiler.storage.username: deskpro_dev
  profiler.storage.password: deskpro_dev
  profiler.storage.class: Profiler\LiveBundle\Profiler\Storage\MysqlProfilerStorage
  profiler.storage.lifetime: 1800

services:
  templating.engine.jsonphp:
    class: Orb\Templating\Engine\PhpVarJsonEngine
    arguments: [@templating.name_parser, @service_container, @templating.loader, @templating.globals]
    tags:
      - { name: templating.engine, alias: jsonphp }
  twig.helpers.deskpro_templating:
    class: Application\DeskPRO\Twig\Extension\TemplatingExtension
    arguments: [@service_container]
    tags:
      - { name: twig.extension }
  session.storage:
    class: Application\DeskPRO\HttpFoundation\SessionStorage\SessionEntityStorage
    arguments: [@doctrine.orm.entity_manager, %session.storage.options%]
  swiftmailer.transport.dp_delegating:
    class: Application\DeskPRO\Mail\Transport\DelegatingTransport
    arguments: [@swiftmailer.transport.eventdispatcher]
  doctrine.dbal.connection_factory:
    class: Application\DeskPRO\DBAL\ConnectionFactory
    arguments: [%doctrine.dbal.connection_factory.types%]
    calls:
      - [ setContainer, [@service_container] ]
  deskpro.exception_logger:
    class: Application\DeskPRO\HttpKernel\ExceptionListener
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: -128 }

framework:
  charset: UTF-8
  secret: mube224etsmhxky1gvwixc4b
  templating:
    engines: ['twig', 'php', 'jsonphp']
    assets_base_urls: "CONFIG_HTTP"
  validation:
    enabled: true
  session:
    default_locale: en
    lifetime: 3600
    auto_start: true
  form:
    enabled: true

doctrine:
  orm:
    auto_generate_proxy_classes: false
    default_entity_manager: default
    entity_managers:
      default:
        mappings:
          DeskPRO: ~
  dbal:
    default_connection: default
    connections:
      default:
        host: 'from_user_config.db'
        logging: true

swiftmailer:
  transport: 'deskpro.mail.delegating_transport'

deskpro_cache:
  common: ~
  portal: ~

deskpro_core: ~
deskpro_search: ~
