imports:
    - { resource: config.yml }

parameters:
    kernel.debug: true

#webprofiler.config:
#  toolbar: true
#  intercept_redirects: false

twig.config:
  auto_reload: true

zend.config:
  logger:
    priority: debug
    path:     %kernel.root_dir%/logs/%kernel.environment%.log
