core:
  resource: CoreBundle/Resources/config/routing.yml

user:
  resource: UserBundle/Resources/config/routing.yml

tech:
  prefix: /tech
  resource: TechBundle/Resources/config/routing.yml

dev:
  prefix: /dev
  resource: DevBundle/Resources/config/routing.yml
