#deskpro:
#  resource: DeskPRO/Resources/config/routing.yml

user:
  resource: UserBundle/Resources/config/routing.yml

tech:
  prefix: /tech
  resource: TechBundle/Resources/config/routing.yml

dev:
  prefix: /dev
  resource: DevBundle/Resources/config/routing.yml

api:
  prefix: /api
  resource: ApiBundle/Resources/config/routing.yml