deskpro:
  resource: "%DP_ROOT%/src/Application/DeskPRO/Resources/config/routing.yml"

user:
  resource: "%DP_ROOT%/src/Application/UserBundle/Resources/config/routing.yml"

agent:
  prefix: /agent
  resource: "%DP_ROOT%/src/Application/AgentBundle/Resources/config/routing.yml"

admin:
  prefix: /admin
  resource: "%DP_ROOT%/src/Application/AdminBundle/Resources/config/routing.yml"

report:
  prefix: /report
  resource: "%DP_ROOT%/src/Application/ReportBundle/Resources/config/routing.yml"
  
api:
  prefix: /api
  resource: "%DP_ROOT%/src/Application/ApiBundle/Resources/config/routing.yml"
