services:

  # the LanguageBundle replaces the router by decorating it (see "decorates:")
  language_router:
    public: false
    class: Application\LanguageBundle\Routing\Router
    decorates: router
    arguments:
      - @language_router.inner
      - @language_manager
      - @portal_mode_storage

  router.cache_warmer:
    public: false
    class: Symfony\Bundle\FrameworkBundle\CacheWarmer\RouterCacheWarmer
    arguments: [@language_router]
    tags:
      - { name: kernel.cache_warmer }