services:
  language_router:
    public: false
    class: Application\LanguageBundle\Routing\Router
    decorates: router
    arguments: [@language_router.inner, @language_manager]

  default_language:
    class: Application\DeskPRO\Entity\Language
    factory_class: Application\DeskPRO\Translate\SystemLanguage
    factory_method: getInstance

  language_stack:
    class: Application\LanguageBundle\Language\LanguageStack
    arguments: [@default_language]

  language_manager:
    class: Application\LanguageBundle\Language\LanguageManager
    arguments: [@deskpro.core.translate, @language_stack]

  deskpro.core.translate_loader_system:
    class: Application\DeskPRO\Translate\Loader\SystemLoader
    arguments: [ [ %kernel.root_dir% ~ '/../languages' ] ]

  deskpro.core.translate_loader_db:
    class: Application\DeskPRO\Translate\Loader\DbLoader
    arguments: [ @doctrine.dbal.default_connection ]

  deskpro.core.translate_loader:
    class: Application\DeskPRO\Translate\Loader\DeskproLoader
    calls:
     - [setSystemLoader, [@deskpro.core.translate_loader_system] ]
     - [setDbLoader, [@deskpro.core.translate_loader_db] ]

  deskpro.core.translate:
    class: Application\DeskPRO\Translate\Translate
    arguments: [ @deskpro.core.translate_loader, @event_dispatcher ]