services:
  language_router:
    public: false
    class: Application\LanguageBundle\Routing\Router
    decorates: router
    arguments: [@language_router.inner, @language_manager]

  language_stack:
    class: Application\LanguageBundle\Language\LanguageStack
    arguments: [ @settings_resolver, @language_repository ]

  language_repository:
    class: Application\DeskPRO\EntityRepository\Language
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments: ['DeskPRO:Language']

  language_manager:
    class: Application\LanguageBundle\Language\LanguageManager
    arguments: [@deskpro.core.translate, @language_stack, @language_repository]

  deskpro.core.translate_loader_system:
    class: Application\DeskPRO\Translate\Loader\SystemLoader
    arguments: [ [ %kernel.root_dir% ~ '/../languages' ] ]

  deskpro.core.translate_loader_db:
    class: Application\DeskPRO\Translate\Loader\DbLoader
    arguments: [ @doctrine.dbal.default_connection ]

  deskpro.core.translate_loader:
    class: Application\DeskPRO\Translate\Loader\DeskproLoader
    calls:
     - [setSystemLoader, [@deskpro.core.translate_loader_system] ]
     - [setDbLoader, [@deskpro.core.translate_loader_db] ]

  deskpro.core.translate:
    class: Application\DeskPRO\Translate\Translate
    arguments: [ @deskpro.core.translate_loader, @event_dispatcher ]

  redirect_exception.language.listener:
    class: Application\LanguageBundle\EventListener\RedirectExceptionListener
    arguments: [@logger]
    tags:
      - { name: kernel.event_subscriber }

  last_language.listener:
    class: Application\LanguageBundle\EventListener\LastLanguageListener
    arguments: [@language_stack]
    tags:
      - { name: kernel.event_subscriber }