api_test:
  pattern: /test
  defaults: { _controller: ApiBundle:Test:test }
  requirements: { _method: GET }

api_test_post:
  pattern: /test
  defaults: { _controller: ApiBundle:Test:postTest }
  requirements: { _method: POST }

api_deskpro_time:
  pattern: /deskpro/time
  defaults: { _controller: ApiBundle:Deskpro:time }
  requirements: { _method: GET }

api_deskpro_setting:
  pattern: /deskpro/setting/:setting_name
  defaults: { _controller: ApiBundle:Deskpro:setting }
  requirements: { _method: GET }

api_deskpro_setting_post:
  pattern: /deskpro/setting/:setting_name
  defaults: { _controller: ApiBundle:Deskpro:postSetting }
  requirements: { _method: POST }

api_ping_object_updated:
  pattern: /ping/object-updated/:resource_id/:object_id
  defaults: { _controller: ApiBundle:ResourcePing:postObjectUpdated }
  requirements: { _method: POST }

api_ticketsearch_queues_getnames:
  pattern: /ticket-search/get-queue-names
  defaults: { _controller: ApiBundle:TicketSearch:getQueueNames }
  requirements: { _method: GET }

api_ticketsearch_queues_getcounts:
  pattern: /ticket-search/get-queue-counts
  defaults: { _controller: ApiBundle:TicketSearch:getQueueCounts }
  requirements: { _method: GET }

api_ticketsearch_queues_getresults:
  pattern: /ticket-search/queues/:queue_id/get-results
  defaults: { _controller: ApiBundle:TicketSearch:getQueueResults }
  requirements: { _method: GET, queue_id: "\d+" }