#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPT_DIR/../../

if [ ! -d app/tests/build ]; then
	mkdir app/tests/build
fi

app/bin/phpmd app/src text app/tests/phpmd/ruleset.xml
