#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPT_DIR

if [ -d build ]; then
	echo "Resetting build files"
	rm -rf build
	echo "--> Done"
fi

mkdir build

IS_ERROR=0

echo ""
echo "=========================="
echo "Running phpUnit Test Suite"
echo "=========================="
echo ""

bin/phpunit --coverage-clover build/clover.xml
if [[ $? -ne 0 ]] ; then
	echo "!!! phpUnit Test Failure !!!"
	IS_ERROR=1
fi

if [ $IS_ERROR -ne 1 ] ; then

	# phpunit will have created cache dirs owned by the cli user
	# but we'll be making web requests now, so we need to make sure
	# the web server can write too
	sudo chmod -R 0777 ../sys/cache

	echo ""
	echo "========================"
	echo "Running Behat Test Suite"
	echo "========================"
	echo ""

	bin/behat
	if [[ $? -ne 0 ]] ; then
		echo "!!! Behat Test Failure !!!"
		IS_ERROR=1
	fi
fi

if [ $IS_ERROR -ne 0 ] ; then
	exit 1
fi
exit 0