#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPT_DIR

IS_ERROR=0

echo ""
echo "=========================="
echo "Running phpUnit Test Suite"
echo "=========================="
echo ""

bin/phpunit
if [[ $? -ne 0 ]] ; then
	echo "!!! phpUnit Test Failure !!!"
	IS_ERROR=1
fi

if [ $IS_ERROR -ne 1 ] ; then
	echo ""
	echo "========================"
	echo "Running Behat Test Suite"
	echo "========================"
	echo ""

	bin/behat
	if [[ $? -ne 0 ]] ; then
		echo "!!! Behat Test Failure !!!"
		IS_ERROR=1
	fi
fi

if [ $IS_ERROR -ne 0 ] ; then
	exit 1
fi
exit 0