services:

  data_serializer:
    class: DeskPRO\Bundle\AppBundle\DataSerializer\DataSerializer
    arguments: [@data_serializer.event_dispatcher, @data_serializer.type_id_finder]

  data_serializer.type_map:
    class: DeskPRO\Bundle\AppBundle\DataSerializer\DataTypeMap
    arguments:
      - %data_serializer.types%

  data_serializer.type_id_finder:
    class: DeskPRO\Bundle\AppBundle\DataSerializer\DataTypeIdFinder
    arguments:
      - @property_accessor

  data_serializer.data_transformer:
    class: DeskPRO\Bundle\AppBundle\DataSerializer\DataTransformer
    arguments:
      - @data_serializer.data_transformer_registry
      - @data_serializer.transformer_factory
      - @data_serializer.type_map
      - @data_serializer.type_id_finder

  data_serializer.data_transformer_registry:
    class: DeskPRO\Bundle\AppBundle\DataSerializer\DataTransformerRegistry

  data_serializer.transformer_factory:
    class: DeskPRO\Bundle\AppBundle\DataSerializer\DataTransformerFactory
    arguments:
      - @service_container
      - @data_serializer.property_transformer
      - @logger

  # SERIALIZER EVENTS
  data_serializer.event_dispatcher:
    class: Symfony\Component\EventDispatcher\EventDispatcher

  data_serializer.listener.type:
    class: DeskPRO\Bundle\AppBundle\DataSerializer\EventListener\TypeListener
    arguments: [@data_serializer.type_map]
    tags:
      - { name: data_serializer.event_subscriber }

  data_serializer.listener.pagination:
    class: DeskPRO\Bundle\AppBundle\DataSerializer\EventListener\PaginationListener
    tags:
      - { name: data_serializer.event_subscriber }

  data_serializer.listener.transformer:
    class: DeskPRO\Bundle\AppBundle\DataSerializer\EventListener\TransformerListener
    arguments: [@data_serializer.data_transformer, @logger]
    tags:
      - { name: data_serializer.event_subscriber }

  data_serializer.listener.deferred_properties:
    class: DeskPRO\Bundle\AppBundle\DataSerializer\EventListener\DeferredPropertiesListener
    arguments: [ @data_serializer.property_transformer, @logger]
    tags:
      - { name: data_serializer.event_subscriber }

  data_serializer.listener.sideload:
    class: DeskPRO\Bundle\AppBundle\DataSerializer\EventListener\SideloadListener
    arguments:
      - @data_serializer.data_transformer
      - @data_serializer.property_transformer
      - @data_serializer.listener.deferred_properties
      - @logger
    tags:
      - { name: data_serializer.event_subscriber }

  data_serializer.listener.json_api:
    class: DeskPRO\Bundle\AppBundle\DataSerializer\EventListener\JsonApiFormatListener
    tags:
      - { name: data_serializer.event_subscriber }

  # PROPERTY TRANSFORMERS
  data_serializer.property_transformer:
    class: DeskPRO\Bundle\AppBundle\DataSerializer\DataPropertyTransformer
    arguments:
      "property_transformers":
        - @data_serializer.property_transformer.doctrine
        - @data_serializer.property_transformer.date
        - @data_serializer.property_transformer.callback

  data_serializer.property_transformer.date:
    class: DeskPRO\Bundle\AppBundle\DataSerializer\PropertyTransformer\DatePropertyTransformer

  data_serializer.property_transformer.doctrine:
    class: DeskPRO\Bundle\AppBundle\DataSerializer\PropertyTransformer\Doctrine\DoctrinePropertyTransformer
    arguments: [@doctrine_association_manager, @data_serializer.type_map]

  data_serializer.property_transformer.callback:
    class: DeskPRO\Bundle\AppBundle\DataSerializer\PropertyTransformer\Callback\CallbackPropertyTransformer
