services:

  # Note: SecurityHeadersResponseListener's service is defined in config.shared.php as it is used globally

  event_listener.auto_post_on_get_request:
    class: DeskPRO\Bundle\AppBundle\EventListener\AutoPostOnGetRequestListener
    tags:
      - { name: kernel.event_subscriber }

  event_listener.anti_abuse_exception_listener:
    class: DeskPRO\Bundle\AppBundle\EventListener\AntiAbuse\AntiAbuseExceptionListener
    tags:
      - { name: kernel.event_subscriber }

  dp.api.event_listeners.label_entity:
    class: DeskPRO\Bundle\AppBundle\EventListener\Labels\LabelListener
    tags:
      - { name: doctrine.event_listener, event: postPersist }
      - { name: doctrine.event_listener, event: postRemove }

  event_listener.listener.client_message_listener:
      class: DeskPRO\Bundle\AppBundle\EventListener\ClientMessage\ClientMessageListener
      arguments:
          - @doctrine.orm.entity_manager
          - @data_serializer
      tags:
          - { name: kernel.event_subscriber }
