services:

  form_hierarchy_generator:
    class: DeskPRO\Bundle\AppBundle\Form\Hierarchy\HierarchyGenerator
    arguments: [@doctrine.orm.default_entity_manager, @data.departments, @data.feedback, @language_manager]

  form_field_manager:
    class: DeskPRO\Bundle\AppBundle\Form\Form\FormFieldManager
    arguments: [@doctrine.orm.default_entity_manager]

  default_value_for_ticket_layout_field:
    class: DeskPRO\Bundle\AppBundle\Form\Form\DefaultValueForTicketLayoutField
    arguments: [@doctrine.orm.default_entity_manager, @form_field_manager]

  ticket_layout_factory:
    class: DeskPRO\Bundle\AppBundle\Ticket\TicketLayoutFactory
    arguments: [@doctrine.orm.default_entity_manager, @?captcha_decider]

  ticket_layout_differ:
    class: DeskPRO\Bundle\AppBundle\Ticket\TicketLayoutDiffer

  form.html_textarea:
    class: DeskPRO\Bundle\AppBundle\Form\Type\HtmlTextareaType
    arguments: [@deskpro.core.input_cleaner]
    tags:
      - { name: form.type, alias: html_textarea }

  form.combined:
    class: DeskPRO\Bundle\AppBundle\Form\Type\CombinedType
    tags:
      - { name: form.type, alias: deskpro_combined_type }

  form.person_email_choice:
    class: DeskPRO\Bundle\AppBundle\Form\Type\PersonEmailChoiceType
    arguments:
      - @doctrine.orm.default_entity_manager
    tags:
      - { name: form.type, alias: deskpro_person_email_choice }

  form.entity_hierarchy:
    class: DeskPRO\Bundle\AppBundle\Form\Type\EntityHeirarchyType
    arguments: [@form_hierarchy_generator]
    tags:
      - { name: form.type, alias: entity_hierarchy }

  form.department:
    class: DeskPRO\Bundle\AppBundle\Form\Type\DepartmentType
    tags:
      - { name: form.type, alias: deskpro_department }

  form.cc:
    class: DeskPRO\Bundle\AppBundle\Form\Type\CcType
    arguments: [@person_factory]
    tags:
      - { name: form.type, alias: deskpro_cc }

  form.workflow:
    class: DeskPRO\Bundle\AppBundle\Form\Type\WorkflowType
    tags:
      - { name: form.type, alias: deskpro_workflow }

  form.product:
    class: DeskPRO\Bundle\AppBundle\Form\Type\ProductType
    tags:
      - { name: form.type, alias: deskpro_product }

  form.priority:
    class: DeskPRO\Bundle\AppBundle\Form\Type\PriorityType
    tags:
      - { name: form.type, alias: deskpro_priority }

  form.category:
    class: DeskPRO\Bundle\AppBundle\Form\Type\CategoryType
    tags:
      - { name: form.type, alias: deskpro_category }

  form.person_email:
    class: DeskPRO\Bundle\AppBundle\Form\Type\PersonEmailType
    tags:
      - { name: form.type, alias: deskpro_person_email }

  form.custom_data_person:
    class: DeskPRO\Bundle\AppBundle\Form\Type\CustomDataPersonType
    arguments: [@form_field_manager]
    tags:
      - { name: form.type, alias: deskpro_custom_data_person }

  form.custom_data_organization:
    class: DeskPRO\Bundle\AppBundle\Form\Type\CustomDataOrganizationType
    arguments: [@form_field_manager]
    tags:
      - { name: form.type, alias: deskpro_custom_data_organization }

  form.custom_data_ticket:
    class: DeskPRO\Bundle\AppBundle\Form\Type\CustomDataTicketType
    arguments: [@form_field_manager, @doctrine.orm.default_entity_manager]
    tags:
      - { name: form.type, alias: deskpro_custom_data_ticket }

  form.deskpro_custom_per_field_data:
    class: DeskPRO\Bundle\AppBundle\Form\Type\CustomPerFieldType
    arguments: [@tickets.custom_per_field_manager, @form_field_manager]
    tags:
      - { name: form.type, alias: deskpro_custom_per_field_data }

  form.custom_field_choice:
    class: DeskPRO\Bundle\AppBundle\Form\Type\CustomFieldChoiceType
    arguments: [@form_hierarchy_generator]
    tags:
      - { name: form.type, alias: deskpro_custom_field_choice }

  form.api_date:
    class: DeskPRO\Bundle\AppBundle\Form\Type\ApiDateType
    tags:
      - { name: form.type, alias: api_date }

  form.api_labels_collection:
    class: DeskPRO\Bundle\AppBundle\Form\Type\Labels\LabelsCollectionType
    arguments: [@doctrine.orm.default_entity_manager]
    tags:
        - { name: form.type, alias: api_labels_collection }

  dp.app.form.person_type:
    class: DeskPRO\Bundle\AppBundle\Form\Type\People\PersonType
    arguments: [@doctrine.orm.default_entity_manager]
    tags:
        - { name: form.type, alias: api_person }

  form.api_boolean:
    class: DeskPRO\Bundle\AppBundle\Form\Type\ApiBooleanType
    tags:
        - { name: form.type, alias: api_boolean }

  form.auth_blob:
    class: DeskPRO\Bundle\AppBundle\Form\Type\BlobAuthType
    arguments: [@doctrine.orm.default_entity_manager]
    tags:
      - { name: form.type, alias: auth_blob }

  form.single_checkbox:
    class: DeskPRO\Bundle\PortalBundle\Form\Form\Type\SingleCheckboxType
    tags:
        - { name: form.type, alias: single_checkbox }

  form.filter:
    class: DeskPRO\Bundle\AppBundle\Form\Type\FilterType
    tags:
        - { name: form.type, alias: filter }

  form.dp_auth:
    class: DeskPRO\Bundle\AppBundle\Form\Type\AuthenticationType
    tags:
        - { name: form.type, alias: dp_auth }

  form.task:
    class: DeskPRO\Bundle\AppBundle\Form\Type\TaskType
    tags:
        - { name: form.type, alias: task }

  form.task_attachment:
    class: DeskPRO\Bundle\AppBundle\Form\Type\TaskAttachmentType
    tags:
        - { name: form.type, alias: task_attachment }

  form.task_comment:
    class: DeskPRO\Bundle\AppBundle\Form\Type\TaskCommentType
    tags:
        - { name: form.type, alias: task_comment }

  form.task_label:
    class: DeskPRO\Bundle\AppBundle\Form\Type\TaskLabelType
    tags:
        - { name: form.type, alias: task_label }

  form.task_link:
    class: DeskPRO\Bundle\AppBundle\Form\Type\TaskLinkType
    tags:
        - { name: form.type, alias: task_link }

  form.subtask:
    class: DeskPRO\Bundle\AppBundle\Form\Type\TaskSubtaskType
    tags:
        - { name: form.type, alias: subtask }

  form.project:
    class: DeskPRO\Bundle\AppBundle\Form\Type\ProjectType
    tags:
        - { name: form.type, alias: project }

  form.projectmember:
    class: DeskPRO\Bundle\AppBundle\Form\Type\ProjectMemberType
    tags:
        - { name: form.type, alias: projectmember }

  form.term_engine.term:
    class: DeskPRO\Bundle\AppBundle\Form\Type\TermEngineTermType
    arguments:
        - @form.term_engine.term_transformer
    tags:
        - { name: form.type, alias: term_engine_term }

  form.term_engine.term_options:
    class: DeskPRO\Bundle\AppBundle\Form\Type\TermEngineTermOptionsType
    tags:
        - { name: form.type, alias: term_engine_term_options }

  form.term_engine.term_transformer:
    class: DeskPRO\Bundle\AppBundle\Form\DataTransformer\TermEngineTermTransformer
    arguments:
        - @term_to_json_converter

  form.filter_set:
    class: DeskPRO\Bundle\AppBundle\Form\Type\FilterSetType
    tags:
        - { name: form.type, alias: filter_set }

  form.feedback_comment:
    class: DeskPRO\Bundle\AppBundle\Form\Type\FeedbackCommentType
    tags:
        - { name: form.type, alias: feedback_comment }

  form.person_profile:
    class: DeskPRO\Bundle\AppBundle\Form\Type\PersonProfileType
    tags:
        - { name: form.type, alias: person_profile }

  form.widget_setup:
    class: DeskPRO\Bundle\AppBundle\Form\Type\WidgetSetup\WidgetSetupType
    tags:
       - { name: form.type, alias: widget_setup }

  form.ticket_message_attachment:
    class: DeskPRO\Bundle\AppBundle\Form\Type\Tickets\TicketMessageAttachmentType
    arguments: [@blob.storage, @blob_repository, @attachment_accepter]
    tags:
      - { name: form.type, alias: ticket_message_attachment }

  form.ticket_message_attachment_collection:
    class: DeskPRO\Bundle\AppBundle\Form\Type\Tickets\TicketMessageAttachmentCollectionType
    tags:
      - { name: form.type, alias: ticket_message_attachment_collection }

  form.ticket:
    class: DeskPRO\Bundle\AppBundle\Form\Type\Tickets\TicketType
    arguments:
      - @form_field_manager
      - @ticket_layout_factory
      - @ticket_layout_differ
      - @form_hierarchy_generator
      - @doctrine.orm.default_entity_manager
      - @language_manager
      - @tickets.custom_per_field_manager
      - @default_value_for_ticket_layout_field
    tags:
      - { name: form.type, alias: ticket }

  form.ticket_description:
    class: DeskPRO\Bundle\AppBundle\Form\Type\Tickets\TicketDescriptionType
    arguments: [@language_manager]
    tags:
      - { name: form.type, alias: ticket_description }
