services:

  form_field_manager:
    class: DeskPRO\Bundle\AppBundle\Form\Form\FormFieldManager
    arguments: [@doctrine.orm.default_entity_manager]

  ticket_layout_factory:
    class: DeskPRO\Bundle\AppBundle\Ticket\TicketLayoutFactory
    arguments: [@doctrine.orm.default_entity_manager]

  ticket_layout_differ:
    class: DeskPRO\Bundle\AppBundle\Ticket\TicketLayoutDiffer