services:

  deskpro.notification.strategy_factory:
    class: DeskPRO\Bundle\AppBundle\Notification\Strategy\StrategyFactory
    arguments:
      - @service_container

  deskpro.notification.event_manager:
    class: DeskPRO\Bundle\AppBundle\Notification\EventManager
    arguments:
      - @deskpro.notification.strategy_factory
    tags:
      - { name: kernel.event_subscriber }

  deskpro.notification.peristance.adapter.db:
    class: DeskPRO\Bundle\AppBundle\Notification\Persistance\DbAdapter
    arguments:
      - @doctrine.orm.default_entity_manager

  deskpro.notification.delivery.delivery_service:
    class: DeskPRO\Bundle\AppBundle\Notification\Delivery\DeliveryService
    factory: [DeskPRO\Bundle\AppBundle\Notification\Delivery\DeliveryService, create]
    arguments:
      - @service_container

  deskpro.notification.delivery.handler.db:
    class: DeskPRO\Bundle\AppBundle\Notification\Delivery\Handler\DbDeliveryHandler
    arguments:
      - @doctrine.orm.default_entity_manager

  deskpro.notification.delivery.handler.redis:
    class: DeskPRO\Bundle\AppBundle\Notification\Delivery\Handler\RedisDeliveryHandler
    arguments:
      - @deskpro.notification.redis_client

  deskpro.notification.notify_handler.action_alert:
    class: DeskPRO\Bundle\AppBundle\Notification\ActionAlertHandler
    calls:
      - [attachGenerator, [@deskpro.notification.generator.action_alert.agent_chat_new_message]]

  deskpro.notification.notify_handler.user_notify:
      class: DeskPRO\Bundle\AppBundle\Notification\UserNotificationHandler
      calls:
        - [attachGenerator, [@deskpro.notification.generator.user_notify.agent_chat_new_message]]

  deskpro.notification.redis_client:
    class: Predis\Client

  #
  # UserNotification message generators
  #
  deskpro.notification.generator.user_notify.agent_chat_new_message:
    class: DeskPRO\Bundle\AppBundle\Notification\Message\Generator\Notification\NewAgentChatMessageGenerator
    arguments:
      - @doctrine.orm.default_entity_manager

  #
  # ActionAlert message generators
  #
  deskpro.notification.generator.action_alert.agent_chat_new_message:
    class: DeskPRO\Bundle\AppBundle\Notification\Message\Generator\ActionAlert\NewAgentChatMessageGenerator
    arguments:
      - @doctrine.orm.default_entity_manager