services:

  quick_search:
    class: DeskPRO\Bundle\AppBundle\QuickSearch\QuickSearch
    arguments:
      - @quick_search.adapter.db
      - @quick_search.adapter.elastic_search
      - @settings_resolver

  quick_search.adapter.db:
    class: DeskPRO\Bundle\AppBundle\QuickSearch\Adapter\Doctrine

  quick_search.adapter.elastic_search:
    class: DeskPRO\Bundle\AppBundle\QuickSearch\Adapter\ElasticSearch
