services:

  blob.storage:
    class: Application\DeskPRO\BlobStorage\DeskproBlobStorage
    factory_class: Application\DeskPRO\DependencyInjection\SystemServices\BlobStorageService
    factory_method: create
    arguments: [@service_container]

  avatar_resolver:
    class: DeskPRO\Bundle\AppBundle\Content\AvatarResolver
    #todo #portal second param here needs to be setting for gravatar
    arguments: [@router.default, true]

  translator.noop:
      class: DeskPRO\Bundle\AppBundle\Translator\NoopTranslator

  file_locator.root_dir:
      class: Symfony\Component\Config\FileLocator
      arguments: [[%kernel.root_dir%]]

  routing.resolver.copy_missing_routes:
      class: DeskPRO\Bundle\AppBundle\Routing\CopyMissingRoutesLoader
      arguments: [@file_locator.root_dir]
      tags:
        - { name: routing.loader }
