services:

  deskpro_config:
    class: DeskPRO\Bundle\AppBundle\Config\DeskproConfigService

  blob.storage:
    class: Application\DeskPRO\BlobStorage\DeskproBlobStorage
    factory_class: Application\DeskPRO\DependencyInjection\SystemServices\BlobStorageService
    factory_method: create
    arguments: [@service_container]

  avatar_resolver:
    class: DeskPRO\Bundle\AppBundle\Content\AvatarResolver
    #todo #portal second param here needs to be setting for gravatar
    arguments: [@router.default, true]

  translator.noop:
      class: DeskPRO\Bundle\AppBundle\Translator\NoopTranslator

  monolog.handler.deskpro:
    class: DeskPRO\Bundle\AppBundle\Logging\DeskproFilesystemHandler
    arguments:
      - @deskpro_config
      - %kernel.name%
      - %kernel.environment%
