services:

    #
    # ENGINE
    #

    term_engine.dbal_ticket_filters.engine:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Engine\Dbal\TicketFilter\DbalTicketFilterEngine
        arguments:
            - @term_engine.dbal_ticket_filters.engine.compiler
            - @term_engine.dbal_ticket_filters.engine.query_manipulator
            - @doctrine.dbal.default_connection

    term_engine.dbal_ticket_filters.engine.query_manipulator:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Engine\Dbal\DbalQueryManipulator
        arguments:
            - @term_engine.expression_language

    term_engine.dbal_ticket_filters.engine.compiler:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Engine\Dbal\TicketFilter\DbalTicketFilterEngineCompiler
        arguments:
            - @term_engine.dbal_ticket_filters.compiler
            - @term_engine.dbal.compiled_query_cacher

    term_engine.dbal_ticket_filters.compiler:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Engine\Dbal\TicketFilter\Compiler\DbalTicketFilterCompiler
        arguments:
            - @term_engine.dbal_ticket_filters.compiler.factory
            - []  # the visitors added in compiler pass with tag "dbal_ticket_filter_visitor"

    term_engine.dbal_ticket_filters.compiler.factory:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Engine\Dbal\TermCompiler\DbalTermCompilerFactory
        # compiler pass will add the term compilers on tag "dbal_ticket_filter_compiler"

    term_engine.dbal.compiled_query_cacher:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Engine\Dbal\Query\DbalQueryCacher
        arguments:
            - @cache.one_day
            - @term_engine.dbal.compiled_query_serializer

    term_engine.dbal.compiled_query_serializer:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Engine\Dbal\Query\DbalQuerySerializer

    #
    # TERM COMPILERS
    #

    term_engine.dbal_ticket_filters.compiler.ticket_status:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Engine\Dbal\TicketFilter\TermCompiler\DbalTicketStatusTermCompiler
        tags:
         - { name: dbal_ticket_filter_compiler, term: 'DeskPRO\Bundle\AppBundle\TermEngine\Term\TicketStatusTerm' }

    term_engine.dbal_ticket_filters.compiler.agent:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Engine\Dbal\TicketFilter\TermCompiler\DbalAgentTermCompiler
        tags:
         - { name: dbal_ticket_filter_compiler, term: 'DeskPRO\Bundle\AppBundle\TermEngine\Term\AgentTerm' }

    term_engine.dbal_ticket_filters.compiler.department:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Engine\Dbal\TicketFilter\TermCompiler\DbalDepartmentTermCompiler
        arguments: @term_engine.dbal.entity_helper
        tags:
         - { name: dbal_ticket_filter_compiler, term: 'DeskPRO\Bundle\AppBundle\TermEngine\Term\DepartmentTerm' }

    term_engine.dbal_ticket_filters.compiler.composite:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Engine\Dbal\TicketFilter\TermCompiler\DbalCompositeTermCompiler
        tags:
         - { name: dbal_ticket_filter_compiler, term: 'DeskPRO\Bundle\AppBundle\TermEngine\Term\CompositeTerm' }

    term_engine.dbal_ticket_filters.compiler.user_email:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Engine\Dbal\TicketFilter\TermCompiler\DbalPersonEmailTermCompiler
        tags:
         - { name: dbal_ticket_filter_compiler, term: 'DeskPRO\Bundle\AppBundle\TermEngine\Term\PersonEmailTerm' }

    term_engine.dbal_ticket_filters.compiler.agent_team:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Engine\Dbal\TicketFilter\TermCompiler\DbalAgentTeamTermCompiler
        tags:
         - { name: dbal_ticket_filter_compiler, term: 'DeskPRO\Bundle\AppBundle\TermEngine\Term\AgentTeamTerm' }

    term_engine.dbal_ticket_filters.compiler.ticket_participant:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Engine\Dbal\TicketFilter\TermCompiler\DbalTicketParticipantTermCompiler
        tags:
         - { name: dbal_ticket_filter_compiler, term: 'DeskPRO\Bundle\AppBundle\TermEngine\Term\TicketParticipantTerm' }

    term_engine.dbal_ticket_filters.compiler.ticket_custom_data:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Engine\Dbal\TicketFilter\TermCompiler\DbalTicketCustomDataTermCompiler
        tags:
         - { name: dbal_ticket_filter_compiler, term: 'DeskPRO\Bundle\AppBundle\TermEngine\Term\TicketCustomDataTerm' }

    #
    # VISITORS
    #

    term_engine.dbal_ticket_filters.logger_visitor:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Visitor\LoggingVisitor
        arguments: [@logger]
        tags:
        - { name: dbal_ticket_filter_visitor }
