services:

    term_serializer:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Util\TermToJsonConverter

    term_engine.expression_language:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Expression\TermEngineExpressionLanguage

    #
    # HELPERS - inject these into your TermCompiler to help build DbalQueryPart's for you
    #

    term_engine.dbal.helper_pool:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Engine\Dbal\TermCompiler\DbalHelperPool

    term_engine.dbal.entity_helper:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Engine\Dbal\TermCompiler\Helper\DbalEntityHelper
        tags:
            - { name: dbal_term_engine_helper }

    term_engine.dbal.string_helper:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Engine\Dbal\TermCompiler\Helper\DbalStringHelper
        tags:
            - { name: dbal_term_engine_helper }

    term_engine.dbal.date_helper:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Engine\Dbal\TermCompiler\Helper\DbalDateHelper
        tags:
            - { name: dbal_term_engine_helper }

    term_engine.dbal.numeric_helper:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Engine\Dbal\TermCompiler\Helper\DbalNumericHelper
        tags:
            - { name: dbal_term_engine_helper }