services:

    term_engine.dbal:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Engine\Dbal\DbalEngine
        arguments:
            - @term_engine.dbal.compiler

    term_engine.dbal.compiler:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Engine\Dbal\DbalCompiler
        arguments:
            - @term_engine.dbal.compiler.factory
            - []  # the visitors added in compiler pass

    term_engine.dbal.compiler.factory:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Engine\Dbal\DbalCompilerFactory
        # compiler pass will add the term compilers

    term_engine.dbal.compiler.agent:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Engine\Dbal\Compiler\DbalAgentCompiler
        tags:
         - { name: dbal_compiler, term: 'DeskPRO\Bundle\AppBundle\TermEngine\Term\AgentTerm' }

    term_engine.dbal.compiler.department:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Engine\Dbal\Compiler\DbalDepartmentCompiler
        tags:
         - { name: dbal_compiler, term: 'DeskPRO\Bundle\AppBundle\TermEngine\Term\DepartmentTerm' }

    term_engine.dbal.compiler.composite:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Engine\Dbal\Compiler\DbalCompositeCompiler
        tags:
         - { name: dbal_compiler, term: 'DeskPRO\Bundle\AppBundle\TermEngine\Term\CompositeTerm' }

    term_engine.dbal.compiler.person_email:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Engine\Dbal\Compiler\DbalPersonEmailCompiler
        tags:
         - { name: dbal_compiler, term: 'DeskPRO\Bundle\AppBundle\TermEngine\Term\PersonEmailTerm' }

    term_engine.dbal.logger_visitor:
        class: DeskPRO\Bundle\AppBundle\TermEngine\Visitor\LoggingVisitor
        arguments: [@logger]
        tags:
        - { name: dbal_compiler_visitor }
