services:

    user_chat.listener.system_event_listener:
        class: DeskPRO\Bundle\AppBundle\UserChat\UserChatSystemEventListener
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: kernel.event_subscriber }
