services:

  validator.primary_key_exists:
      class: DeskPRO\Bundle\AppBundle\Validator\Constraints\PrimaryKeyExistsValidator
      arguments:
        - @doctrine.dbal.default_connection
      tags:
        - { name: validator.constraint_validator, alias: 'primary_key_exists_validator' }

  validator.phone_number:
      class: DeskPRO\Bundle\AppBundle\Validator\Constraints\PhoneNumberValidator
      arguments:
        - @doctrine.dbal.default_connection
      tags:
        - { name: validator.constraint_validator, alias: 'phone_number_validator' }

  validator.free_email:
      class: DeskPRO\Bundle\AppBundle\Validator\Constraints\FreeEmailValidator
      arguments:
        - @=service('doctrine.orm.default_entity_manager').getRepository('DeskPRO:Person')
      tags:
        - { name: validator.constraint_validator, alias: 'free_email_validator' }

  validator.not_system_email:
      class: DeskPRO\Bundle\AppBundle\Validator\Constraints\NotSystemEmailValidator
      arguments:
        - @email.email_account_manager
      tags:
        - { name: validator.constraint_validator, alias: 'not_system_email_validator' }

  validator.not_banned_email:
      class: DeskPRO\Bundle\AppBundle\Validator\Constraints\NotBannedEmailValidator
      arguments:
        - @=service('doctrine.orm.default_entity_manager').getRepository('DeskPRO:BanEmail')
      tags:
        - { name: validator.constraint_validator, alias: 'not_banned_email_validator' }
