services:

    form.csrf_double_submit_type:
      class: Application\CsrfDoubleSubmitBundle\EventListener\DoubleSubmitJavascriptListener
      tags:
        - { name: kernel.event_subscriber }

    form.csrf_double_submit_type:
      class: Application\CsrfDoubleSubmitBundle\Form\Type\CsrfDoubleSubmitType
      tags:
        - { name: form.type, alias: csrf_double_submit }

    form.csrf_double_submit_extension:
      class: Application\CsrfDoubleSubmitBundle\Form\Type\CsrfDoubleSubmitExtension
      arguments: [@request_stack]
      tags:
        - { name: form.type_extension, alias: form }