dev:
  pattern: /
  defaults: { _controller: DevBundle:Main:index }

dev_phpinfo:
  pattern: /php-info
  defaults: { _controller: DevBundle:Main:phpInfo }

dev_seefile:
  pattern: /see-file
  defaults: { _controller: DevBundle:Main:seeFile }

dev_run_workerjob:
  pattern: /run-worker-job
  defaults: { _controller: DevBundle:Main:runWorkerJob }

dev_models:
  pattern: /models
  defaults: { _controller: DevBundle:Models:index }

dev_models_getsql:
  pattern: /models/get-sql
  defaults: { _controller: DevBundle:Models:getSql }

dev_test:
  pattern: /test
  defaults: { _controller: DevBundle:Test:index }

dev_phptest:
  pattern: /php-test
  defaults: { _controller: DevBundle:Main:phpTest }

dev_phptest_run:
  pattern: /php-test/run
  defaults: { _controller: DevBundle:Main:phpTestRun }

dev_datagen:
  pattern:  /data-generator
  defaults: { _controller: DevBundle:DataGenerator:index }

dev_datagen_run:
  pattern:  /data-generator/run
  defaults: { _controller: DevBundle:DataGenerator:run }

dev_install:
  pattern:  /install
  defaults: { _controller: DevBundle:Install:index }

dev_install_check:
  pattern:  /install/check
  defaults: { _controller: DevBundle:Install:check }

dev_install_createtables:
  pattern:  /install/create-tables
  defaults: { _controller: DevBundle:Install:createTables }

dev_install_createdata:
  pattern:  /install/create-data
  defaults: { _controller: DevBundle:Install:createData }

dev_build:
  pattern: /build
  defaults: { _controller: DevBundle:Build:index }

dev_build_genclass:
  pattern: /build/gen-build-class
  defaults: { _controller: DevBundle:Build:genBuildClass }

dev_build_upgrade:
  pattern: /build/upgrade
  defaults: { _controller: DevBundle:Build:upgrade }

dev_build_upgrade_do:
  pattern: /build/upgrade-do
  defaults: { _controller: DevBundle:Build:upgradeDo }