services:

  brand_stack:
    class: Application\DeskPRO\Brand\BrandStack
    arguments: [@brand_container_factory, @default_brand]


  brand_container_factory:
    class: Application\DeskPRO\Brand\BrandContainerFactory
    arguments: [@settings_resolver, @theme_resolver]


  default_brand_finder:
    class: Application\DeskPRO\Brand\DefaultBrandFinder
    arguments: [@settings_resolver, @brand_repository]


  default_brand:
    class: Application\DeskPRO\Entity\Brand
    factory_service: default_brand_finder
    factory_method: getDefaultBrand