# Links to known existing URLs (admin, agent, etc)
admin_interface:
    path: /admin
agent_interface:
    path: /agent

dp_routing:
    resource: "@PortalBundle/Resources/config/portal_old_routing.yml"

# Annotations
portal:
    resource: "@PortalBundle/Controller"
    type:     annotation

# The following are caught by our security system, and therefore do not need to have default controllers set on them
portal_logout:
    path: /logout

portal_login_submit:
    path: /login/authenticate-password

portal_login_authenticate:
    path: /login/authenticate/{usersource_id}

portal_login_callback:
    path: /login/authenticate-callback/{usersource_id}

portal_login_usersource_sso:
    path: /login/usersource-sso/{usersource_id}

# DEV
portal_dev:
    path: /_dev
    defaults:
      _controller: Theme:Dev:dev
