parameters:
  router.options.matcher.cache_class: null

services:
  templating.portal:
    class: Application\PortalBundle\Templating\PortalTemplating
    arguments: [@templating.engine.twig]

  brand_stack:
    class: Application\DeskPRO\Brand\BrandStack
    arguments: [@brand_container_factory, @default_brand]

  theme_resolver:
    class: Application\PortalBundle\Theme\ThemeResolver
    arguments: [@service_container, @theme_repository]

  theme_repository:
    class: Application\PortalBundle\Theme\ThemeRepository

  brand_container_factory:
    class: Application\DeskPRO\Brand\BrandContainerFactory
    arguments: [@settings_resolver, @theme_resolver]

  brand_repository:
    class: Application\DeskPRO\EntityRepository\Brand
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments: ['DeskPRO:Brand']

  template_repository:
    class: Application\DeskPRO\EntityRepository\Template
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments: ['DeskPRO:Template']

  default_brand_finder:
    class: Application\DeskPRO\Brand\DefaultBrandFinder
    arguments: [@settings_resolver, @brand_repository]

  default_brand:
    class: Application\DeskPRO\Entity\Brand
    factory_service: default_brand_finder
    factory_method: getDefaultBrand

  param_converter.deskpro_slug:
    class: Application\PortalBundle\Request\DeskproSlugConverter
    arguments: [@doctrine.orm.default_entity_manager]
    tags:
      - { name: request.param_converter, priority: -1, converter: deskpro_slug }

  portal_loadder.twig:
    class: Application\PortalBundle\Twig\PortalLoader
    arguments: [@brand_stack, @template_repository]
    tags:
      - { name: twig.loader }

  portal_extension.twig:
    class: Application\PortalBundle\Twig\PortalExtension
    arguments: [@brand_stack, @settings_resolver]
    tags:
      - { name: twig.extension }

  portal_cache.template_map:
    class: Symfony\Component\Config\ConfigCache
    arguments:
      - %kernel.cache_dir%/portalTemplateMap.php
      - %kernel.debug%

  portal_cache.template_cache_warmer:
    class: Application\PortalBundle\CacheWarmer\ThemeTemplateCacheWarmer
    arguments: [@theme_resolver]
    tags:
      - { name: 'kernel.cache_warmer' }

  data_collector.portal:
    class: Application\PortalBundle\DataCollector\PortalCollector
    arguments: [@brand_stack]
    tags:
      - { name: data_collector, template: "PortalBundle:Collector:portal.html.twig", id: "portal" }


  ##
  ## Event Listeners
  ##

  brand_detector.listener:
    class: Application\PortalBundle\EventListener\BrandDetectionListener
    arguments: [@brand_stack, @settings_resolver, @brand_repository, @default_brand]
    tags:
      - { name: kernel.event_subscriber }

  redirect_exception.listener:
    class: Application\PortalBundle\EventListener\RedirectExceptionListener
    arguments: [@router]
    tags:
      - { name: kernel.event_subscriber }

  controller_name_converter:
      class: Application\PortalBundle\HttpKernel\ControllerNameParser
      tags: [{name: monolog.logger, channel: request}]
      arguments: [@kernel, @brand_stack]
