parameters:
  router.options.matcher.cache_class: null

services:
  templating.portal:
    class: Application\PortalBundle\Templating\PortalTemplating
    arguments: [@templating.engine.twig]

  brand_stack:
    class: Application\DeskPRO\Brand\BrandStack
    factory_class: Application\DeskPRO\DependencyInjection\SystemServices\BrandStackService
    factory_method: create
    arguments: [@service_container]

  brand_repository:
    class: Application\DeskPRO\EntityRepository\Brand
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments: ['DeskPRO:Brand']

  template_repository:
    class: Application\DeskPRO\EntityRepository\Template
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments: ['DeskPRO:Template']

  default_brand_finder:
    class: Application\DeskPRO\Brand\DefaultBrandFinder
    arguments: [@settings_resolver, @brand_repository]

  default_brand:
    class: Application\DeskPRO\Entity\Brand
    factory_service: default_brand_finder
    factory_method: getDefaultBrand

  portal_loadder.twig:
    class: Application\PortalBundle\Twig\PortalLoader
    arguments: [@brand_stack, @template_repository]
    tags:
      - { name: twig.loader }

  portal_extension.twig:
    class: Application\PortalBundle\Twig\PortalExtension
    arguments: [@brand_stack]
    tags:
      - { name: twig.extension }

  data_collector.portal:
    class: Application\PortalBundle\DataCollector\PortalCollector
    arguments: [@brand_stack]
    tags:
      - { name: data_collector, template: "PortalBundle:Collector:portal.html.twig", id: "portal" }


  ##
  ## Event Listeners
  ##

  brand_detector.listener:
    class: Application\PortalBundle\EventListener\BrandDetectionListener
    arguments: [@brand_stack, @settings_resolver, @brand_repository, @default_brand]
    tags:
      - { name: kernel.event_subscriber }

  controller_name_converter:
      class: Application\PortalBundle\HttpKernel\ControllerNameParser
      tags: [{name: monolog.logger, channel: request}]
      arguments: [@kernel, @brand_stack]
