# Main
portal_index:
    path: /
    defaults:
      _controller: Theme:Portal:index

#Login
portal_login:
    path: /login
    defaults:
        _controller: Theme:Portal:login

portal_logout:
    path: /logout

portal_login_submit:
    path: /login/authenticate-password
    defaults:
        _controller: Theme:Portal:login

# Knowledgebase
portal_kb:
    path: /kb
    defaults:
      _controller: Theme:Articles:index
portal_kb_browse:
    path: /kb/{slug}
    defaults:
      _controller: Theme:Articles:browse
portal_kb_view:
    path: /kb/posts/{slug}
    defaults:
      _controller: Theme:Articles:view

# Downloads
portal_downloads:
    path: /downloads
    defaults:
      _controller: Theme:Downloads:index
portal_downloads_browse:
    path: /downloads/{slug}
    defaults:
      _controller: Theme:Downloads:browse
portal_downloads_view:
    path: /downloads/files/{slug}
    defaults:
      _controller: Theme:Downloads:view
portal_downloads_download:
    path: /downloads/files/{slug}/download
    defaults:
      _controller: Theme:Downloads:download

# News
portal_news:
    path: /news
    defaults:
      _controller: Theme:News:index
portal_news_browse:
    path: /news/{slug}
    defaults:
      _controller: Theme:News:browse
portal_news_view:
    path: /news/posts/{slug}
    defaults:
      _controller: Theme:News:view

# Feedback
portal_feedback:
    path: /feedback
    defaults:
      _controller: Theme:Feedback:index
portal_feedback_view:
    path: /feedback/view/{slug}
    defaults:
      _controller: Theme:Feedback:view

# Search
portal_search:
  path: /search
  defaults:
    _controller: Theme:Search:index

# New Ticket
portal_new_ticket:
    path: /new-ticket
    defaults:
      _controller: Theme:NewTicket:newTicket

# Tickets
portal_tickets:
    path: /tickets
    defaults:
      _controller: Theme:Tickets:index
portal_tickets_view:
    path: /tickets/{ref}
    defaults:
      _controller: Theme:Tickets:view

# User Account / Profile / Login / Registration
portal_user_profile:
    path: /profile
    defaults:
      _controller: Theme:Profile:edit

portal_user_registration:
    path: /register
    defaults:
      _controller: Theme:Profile:register


# DEV
portal_dev:
    path: /_dev
    defaults:
      _controller: Theme:Dev:dev
