# Annotations
portal:
    resource: "@PortalBundle/Controller"
    type:     annotation

# The following are caught by our security system, and therefore do not need to have default controllers set on them
portal_logout:
    path: /logout

portal_login_submit:
    path: /login/authenticate-password

portal_login_authenticate:
    path: /login/authenticate/{usersource_id}

portal_login_callback:
    path: /login/authenticate-callback/{usersource_id}

portal_login_usersource_sso:
    path: /login/usersource-sso/{usersource_id}



# Tickets
portal_tickets:
    path: /tickets
    defaults:
      _controller: PortalBundle:Tickets:index
portal_tickets_view:
    path: /tickets/view/{id}
    defaults:
      _controller: PortalBundle:Tickets:view
portal_tickets_edit:
    path: /tickets/{id}
    defaults:
      _controller: PortalBundle:Tickets:edit

# User Account / Profile / Login / Registration
portal_user_profile:
    path: /profile
    defaults:
      _controller: PortalBundle:Profile:edit

portal_user_registration:
    path: /register
    defaults:
      _controller: PortalBundle:Profile:register


# DEV
portal_dev:
    path: /_dev
    defaults:
      _controller: Theme:Dev:dev
