# Links to known existing URLs (admin, agent, file.php, etc)
# these are duplicates from DpKernel's config
admin_interface:
    path: /admin
agent_interface:
    path: /agent
serve_blob:
    path: '/file.php/{blob_auth_id}/{filename}'

# Annotations
portal:
    resource: "@PortalBundle/Controller"
    type:     annotation

# DEV
portal_dev:
    path: /_dev
    defaults:
      _controller: Theme:Dev:dev
