// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['Admin/Main/Ctrl/Base', 'Admin/App'], function(Admin_Ctrl_Base) {
    var Admin_Main_Ctrl_NavTickets, _ref;
    Admin_Main_Ctrl_NavTickets = (function(_super) {
      __extends(Admin_Main_Ctrl_NavTickets, _super);

      function Admin_Main_Ctrl_NavTickets() {
        _ref = Admin_Main_Ctrl_NavTickets.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Admin_Main_Ctrl_NavTickets.CTRL_ID = 'Admin_Main_Ctrl_NavTickets';

      Admin_Main_Ctrl_NavTickets.prototype.init = function() {};

      return Admin_Main_Ctrl_NavTickets;

    })(Admin_Ctrl_Base);
    return Admin_Main_Ctrl_NavTickets.EXPORT_CTRL();
  });

}).call(this);

/*
//@ sourceMappingURL=NavTickets.map
*/
